TomHarte/CLK

OSBindings/Mac/Clock Signal/Views/CSOpenGLView.m, Outputs/CRT/CRT.cpp, Outputs/CRT/Internals/CRTInputBufferBuilder.cpp, Outputs/CRT/Internals/CRTInputBufferBuilder.hpp, Outputs/CRT/Internals/CRTOpenGL.cpp, Outputs/CRT/Internals/CRTOpenGL.hpp
Being:
* a basic threading error; and
* failure properly to correct for an asynchonrously reset texture write cursor.
These together appear fully to repair the Electron emulation but leave an occasional rolling blank line in the Atari. So at least one further error lurks.
=> Fixes the two most obvious potential causes of garbage lines

Outputs/CRT/Internals/CRTConstants.hpp, Outputs/CRT/Internals/CRTOpenGL.cpp, Outputs/CRT/Internals/CRTOpenGL.hpp
This primarily sets the stage for instanced drawing; it temporarily produces a more solid foundation for chasing the one remaining graphics output artefact.
=> Switches to always filling GL-headed arrays from 0

Outputs/CRT/CRT.cpp, Outputs/CRT/Internals/CRTConstants.hpp, Outputs/CRT/Internals/CRTOpenGL.cpp, Outputs/CRT/Internals/CRTOpenGL.hpp, Outputs/CRT/Internals/Shaders/OutputShader.cpp
Thereby reducing the amount of data passed to OpenGL from 48 bytes per output run to 8 bytes per output run — a 5/6ths reduction.
=> Introduces use of array instancing for output runs.

Processors/6502/CPU6502.hpp
… causing all unit tests once again to pass.
=> Ensured that calling `return_from_subroutine` really does unjam the processor if required

Machines/Atari2600/Atari2600.cpp, Outputs/CRT/Internals/Shaders/IntermediateShader.cpp, Outputs/CRT/Internals/Shaders/IntermediateShader.hpp, Outputs/CRT/Internals/Shaders/OutputShader.cpp, Outputs/CRT/Internals/Shaders/OutputShader.hpp, Outputs/CRT/Internals/Shaders/Shader.cpp, Outputs/CRT/Internals/Shaders/Shader.hpp
Changes are queued within `Shader` and take place only after the next time the shader is bound. This means that:
* changing uniforms no longer affects the current shader bounding;
* it is more likely that good OpenGL batching will occur; and
* whomever calls `bind` is now the only person that need be able to guarantee that the appropriate OpenGL context is available. So uniforms become safe to set from machine emulation code
=> Implemented deferred setting of shader uniforms

Machines/Atari2600/Atari2600.cpp, Machines/Atari2600/Atari2600.hpp, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm
Which is used specifically so that the 2600 now implements its different PAL and NTSC operation frequencies.
... it's lucky the sound code was generalised to accept non-integral input and output rates.
=> Completes the loop on machines changing clock rate dynamically

Components/6560/6560.cpp, Machines/Atari2600/Atari2600.cpp, Machines/Electron/Electron.cpp, Machines/Vic-20/Vic20.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock SignalTests/6502InterruptTests.swift, OSBindings/Mac/Clock SignalTests/6502TimingTests.swift, OSBindings/Mac/Clock SignalTests/KlausDormannTests.swift, OSBindings/Mac/Clock SignalTests/TestMachine.h, OSBindings/Mac/Clock SignalTests/TestMachine.mm, Processors/6502/CPU6502.hpp, Processors/6502/CPU6502AllRAM.cpp
Simultaneously:
* makes per-operation decision slightly cheaper;
* extends IRQ and NMI to their proper lengths;
* adds a more convenient way for machines to cause a power-on reset, fixing a break-button bug in the Electron;
* slightly improves 6560 timing; and
* makes some attempt at allowing NMIs to usurp IRQs and BRKs.
=> Adds a small amount of test coverage to the functioning of 6502 interrupts

Components/6560/6560.hpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Commodore/Vic-20/Vic20.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Documents/Vic20Document.swift, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSVic20.h, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSVic20.mm, Storage/Tape/Formats/CommodoreTAP.cpp, Storage/Tape/Formats/CommodoreTAP.hpp, Storage/Tape/Formats/TapePRG.cpp, Storage/Tape/Formats/TapePRG.hpp
Albeit that the test for "is or is not a ROM" is terrible. The intention is that this gives another route in for PRGs and therefore shifts the ball into the court of accelerated tape loading and proper loading configuration and command issuing.
=> Adjusts non-ROM PRG loading to be via the tape interface

OSBindings/Mac/Clock Signal/Audio/CSAudioQueue.h, OSBindings/Mac/Clock Signal/Audio/CSAudioQueue.m, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift
... because there's no benefit to doing so and lots of opportunity for error.
=> Removes the locking attempt at enforcing a circular audio buffer on the Mac

Components/AY38910/AY38910.cpp, Components/AY38910/AY38910.hpp, Concurrency/AsyncTaskQueue.cpp, Concurrency/AsyncTaskQueue.hpp, OSBindings/Mac/Clock Signal/Audio/CSAudioQueue.m
While switching to a simpler, directly conditional implementation, because that part turns out not to be too significant a cost after all, so clarity is preferential. Also switched to loading counters immediately upon setting of periods. I've no idea whether that's correct but it subjectively sounds it. Must try to find better documentation.
=> Reduces AY processor load

Components/6522/6522.hpp, Machines/Commodore/1540/C1540.cpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Oric/Oric.cpp, Machines/Oric/Video.cpp
Partly by introducing a full-cycle execution mode, partly by taking the phase 1/2 test outside the loop when running in half cycles, making it more amenable to branch prediction.
=> Reduces 6522 emulation costs

Components/6522/6522.hpp, Processors/6502/CPU6502.hpp
(and corrects a 6522 cycle-counting bug, as the other step necessary to correct unit tests)
=> Switches to storing the IRQ line in the inverse, to simplify its per-cycle logic

Machines/Oric/Oric.cpp, Machines/Oric/Oric.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, StaticAnalyser/Acorn/Tape.cpp, StaticAnalyser/Commodore/Disk.cpp, StaticAnalyser/Commodore/Tape.cpp, StaticAnalyser/Oric/StaticAnalyser.cpp, StaticAnalyser/Oric/Tape.cpp, StaticAnalyser/Oric/Tape.hpp, StaticAnalyser/TapeParser.hpp, Storage/Data/Commodore.cpp, Storage/Data/Commodore.hpp, Storage/Tape/Formats/OricTAP.cpp, Storage/Tape/Parsers/Acorn.cpp, Storage/Tape/Parsers/Acorn.hpp, Storage/Tape/Parsers/Commodore.cpp, Storage/Tape/Parsers/Commodore.hpp, Storage/Tape/Parsers/Oric.cpp, Storage/Tape/Parsers/Oric.hpp, Storage/Tape/Parsers/TapeParser.hpp
While also pulling out and expanding the Oric parser, to introduce a meaningful (albeit presently redundant) static analysis step for the Oric. And adjusting both the Vic and Electron parsers to the new standard.
=> Clarifies that a tape parser does not own a tape, it is merely lent one

Outputs/CRT/CRT.cpp, Outputs/CRT/CRT.hpp, Outputs/CRT/Internals/ArrayBuilder.cpp, Outputs/CRT/Internals/ArrayBuilder.hpp, Outputs/CRT/Internals/CRTOpenGL.hpp, Outputs/CRT/Internals/TextureBuilder.cpp, Outputs/CRT/Internals/TextureBuilder.hpp
... to avoid random blank lines, and to reunify locking.
=> Pulls the texture builder into flush/submit orthodoxy

Machines/Atari2600/Atari2600.cpp, Machines/Electron/Electron.cpp, Machines/Electron/Electron.hpp, Machines/Oric/Oric.cpp, Machines/Oric/Oric.hpp, Machines/Oric/Video.cpp, Machines/Oric/Video.hpp, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSOric.mm, Outputs/CRT/CRT.cpp, Outputs/CRT/CRT.hpp, Outputs/CRT/Internals/ArrayBuilder.cpp, Outputs/CRT/Internals/ArrayBuilder.hpp, Outputs/CRT/Internals/CRTConstants.hpp, Outputs/CRT/Internals/CRTOpenGL.cpp, ROMImages/Oric/readme.txt
Simultaneously introducing a simplified default colour burst route for computers that are known to keep phase consistently, and attempting to do a bit better at composite rendering, albeit at a heavy GPU cost for the time being.
=> Switches to using the original Oric colour ROM to generate Oric composite values

OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Views/CSOpenGLView.h
Specifically, between creation of the best-effort updater and initial draw requests from the OpenGL view.
=> Resolves a race condition on machine startup

Machines/Atari2600/TIA.cpp, Outputs/CRT/CRT.cpp
A typing error transposed a digit; it was running at 272.5 cycles per line, rather than 227.5.
Corrected the 2600's expectation of phase appropriately.
=> Fixes NTSC colour cycle count

Outputs/CRT/CRT.cpp, Outputs/CRT/CRT.hpp
... by pulling it out of the inner loop and ensuring that vertical sync is not triggered prematurely.
=> Improves vertical sync recognition

Components/6560/6560.hpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Commodore/Vic-20/Vic20.hpp, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSVic20.mm, StaticAnalyser/Acorn/StaticAnalyser.cpp, StaticAnalyser/Commodore/StaticAnalyser.cpp, StaticAnalyser/Oric/Tape.cpp, StaticAnalyser/StaticAnalyser.cpp, Storage/Tape/Parsers/Commodore.cpp, Storage/Tape/Parsers/Commodore.hpp
Specifically:
* corrects failure of the Vic-20 static analyser to rewind tapes by centralising that responsibility;
* finishes wiring up of the Vic-20 tape player so that it now receives motor control actions, and the machine's tape sense works; and
* introduces a ROM-trapping implementation of fast tape loading, making that close to instantaneous.
=> Corrects — and improves — Vic-20 tape loading

StaticAnalyser/Commodore/Disk.cpp
Specifically resulting from disk controllers having a functioning motor control now.
=> Corrects infinite loop when performing GCR analysis

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock SignalTests/Bridges/TestMachine+ForSubclassEyesOnly.h, OSBindings/Mac/Clock SignalTests/Bridges/TestMachine.h, OSBindings/Mac/Clock SignalTests/Bridges/TestMachine.mm, OSBindings/Mac/Clock SignalTests/Bridges/TestMachine6502.h, OSBindings/Mac/Clock SignalTests/Bridges/TestMachine6502.mm, OSBindings/Mac/Clock SignalTests/Bridges/TestMachineZ80.h, OSBindings/Mac/Clock SignalTests/Bridges/TestMachineZ80.mm, OSBindings/Mac/Clock SignalTests/WolfgangLorenzTests.swift, OSBindings/Mac/Clock SignalTests/ZexallTests.swift, Processors/6502/6502.cpp, Processors/6502/6502.hpp, Processors/6502/6502AllRAM.cpp, Processors/6502/6502AllRAM.hpp, Processors/AllRAMProcessor.cpp, Processors/AllRAMProcessor.hpp
Thereby allowing the elimination of the 6502's custom jam handler. Also switches the 6502 test class to a private implementation with an inline step handler, and eliminates the 6502's function call when decoding instructions.
=> Generalises the Z80 test machine's trap handler also to cover the 6502

Machines/Commodore/Vic-20/Vic20.cpp, Machines/Oric/Oric.cpp, Machines/ZX8081/ZX8081.cpp, Storage/Tape/Tape.cpp
Fixing that logical misdirection fixes normal-speed tape loading on the ZX80 and ZX81. Especially given that it still doesn't work on the '81, the fast-loading hack is dutifully disabled.
=> Switches the binary tape player to low = false, high = true

OSBindings/Mac/Clock SignalTests/Bridges/TestMachineZ80.h, OSBindings/Mac/Clock SignalTests/Bridges/TestMachineZ80.mm, OSBindings/Mac/Clock SignalTests/Z80InterruptTests.swift, Processors/Z80/Z80.hpp, Processors/Z80/Z80AllRAM.cpp, Processors/Z80/Z80AllRAM.hpp
… and adjusts the Z80 to pass it.
Proper wait cycle location is cribbed from information posted by Wilf Rigter; as per comment it's also potentially helpful in making me more confident about those long opcode fetches.
Effect on the ZX81 is to eliminate the remaining timing misstep: there's no more maladjusted hsync now.
=> Introduces an NMI/wait interrupt timing test

Machines/ZX8081/ZX8081.cpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme
Also blocks access to programmatic sync while the NMI generator is enabled. Both of these I currently believe to be accurate.
Also toggles the Xcode project to run as debug, with the address sanitiser. Which really should be the only configuration I commit.
=> Increases port decoding on the ZX81

Machines/Typer.cpp, Machines/Typer.hpp
Specifically resulting from a delegate freeing its caller.
=> Corrects a potential invalid memory dereference in the default typer implementation

Components/6560/6560.hpp, Outputs/CRT/CRT.cpp, Outputs/CRT/CRT.hpp, Outputs/CRT/Internals/TextureBuilder.cpp, Outputs/CRT/Internals/TextureBuilder.hpp
That desynchronisation potentially leading to out-of-bounds buffer accesses. Adds an assert on synchronisation to catch potential future errors.
Also codifies a standard definition of colour subcarrier amplitude, at 40 IRE.
=> Corrects a source of potential desynchronisation between the texture and geometry builders

Machines/ZX8081/Video.cpp, Machines/ZX8081/ZX8081.cpp, Machines/ZX8081/ZX8081.hpp
Including:
* accidental ORing of bit 8 of the refresh address with the character value;
* reliance on the latched value, rather than merely its existence, in determining whether pixels are outgoing;
* accidental queuing of pixel data during times of sync;
* an incorrect end-of-sync trigger; and
* failure properly to model line counter reset as held during programmatic sync if the running program signals end of sync multiple times.
=> Corrects various ZX80/81 video deficiencies

Outputs/CRT/CRT.cpp, Outputs/CRT/Internals/TextureBuilder.cpp, Outputs/CRT/Internals/TextureBuilder.hpp
Specifically by resolving an internal conflict of meaning within the `TextureBuilder`.
Improved documentation slightly to emphasise the intended multiple identity callers.
=> Eliminates occasional on-screen noise

Machines/ZX8081/Video.cpp, Outputs/CRT/CRT.cpp, Outputs/CRT/Internals/TextureBuilder.cpp, Outputs/CRT/Internals/TextureBuilder.hpp
Particularly those that could lead to 'negative' (i.e. very large) run timings.
Also adds a further texture/geometry tie, by ensuring that lack of available geometry acts post hoc to remove a submitted write area from the texture.
=> Corrects accounting errors in ZX80/81 video

Machines/Electron/Tape.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Info.plist, StaticAnalyser/Acorn/StaticAnalyser.cpp, StaticAnalyser/Acorn/Tape.cpp, StaticAnalyser/Commodore/StaticAnalyser.cpp, StaticAnalyser/Oric/StaticAnalyser.cpp, StaticAnalyser/StaticAnalyser.cpp, StaticAnalyser/ZX8081/StaticAnalyser.cpp, Storage/Data/ZX8081.cpp, Storage/Tape/Formats/CSW.cpp, Storage/Tape/Formats/CSW.hpp, Storage/Tape/Formats/ZX80O81P.hpp, Storage/Tape/Parsers/Acorn.cpp, Storage/Tape/Tape.hpp
... and allows its consumption by all four existing tape-based machines.
Taking the opportunity of an additional source of testing to try to shift Acorn tape comprehension closer to the original hardware. I'm starting to think a formal PLL implementation might be the proper way forwards.
=> Adds support for the CSW file format

Storage/Tape/Formats/CSW.cpp
Specifically that n waves means n bytes. It may mean up to 5n bytes.
=> Corrects a false assumption about decompressed CSW size

Machines/ZX8081/ZX8081.cpp, Machines/ZX8081/ZX8081.hpp, NumberTheory/Factors.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Info.plist, StaticAnalyser/StaticAnalyser.cpp, StaticAnalyser/ZX8081/StaticAnalyser.cpp, Storage/Data/ZX8081.cpp, Storage/Data/ZX8081.hpp, Storage/FileHolder.hpp, Storage/Storage.hpp, Storage/Tape/Formats/CSW.cpp, Storage/Tape/Formats/TZX.cpp, Storage/Tape/Formats/TZX.hpp, Storage/Tape/Formats/TapeUEF.cpp, Storage/Tape/Formats/TapeUEF.hpp, Storage/Tape/Parsers/ZX8081.cpp, Storage/Tape/PulseQueuedTape.cpp, Storage/Tape/PulseQueuedTape.hpp, Storage/Tape/Tape.cpp, Storage/Tape/Tape.hpp
Really only for the ZX80 and ZX81 at present, but it'll be here if I ever decide to add ZX Spectrum support, I guess.
TZX support ends up sharing some code with UEF support so this factors out from the UEF class the very basic stuff of having a prepared queue of pulses and vending those as a tape.
As per the CSW/Electron experience, having an imperfect input stream that I didn't generate myself has also given me an opportunity to improve the ZX80 and ZX81 tape parsing.
=> Adds partial TZX file format support

Machines/ZX8081/ZX8081.cpp, Machines/ZX8081/ZX8081.hpp, Processors/AllRAMProcessor.hpp, Processors/Z80/Z80.hpp, Processors/Z80/Z80AllRAM.cpp, Processors/Z80/Z80AllRAM.hpp
As a preparatory step to moving WAIT sampling to the falling edges of appropriate cycles. At the minute it's always sampled half a clock askew. Also that will cause opcode fetches to have an explicit end part, like all the other bus cycles, so besides improving accuracy will also aid greatly in uniformity.
=> Doubles the timing precision used by the Z80 up to HalfCycles

Machines/ZX8081/ZX8081.cpp, Machines/ZX8081/ZX8081.hpp, Processors/AllRAMProcessor.hpp, Processors/Z80/Z80.hpp, Processors/Z80/Z80AllRAM.cpp, Processors/Z80/Z80AllRAM.hpp
... replacing it for now with a wrapper that callers can impose at will to deal with half->full conversions, and allowing full->half conversions to occur naturally via the type conversion.
It'd be nice to come up with an SFINAE-type method to allow the same template to be used to hold all clock receivers, but I've decided to deploy only the simplest unblocker for now.
=> Revokes ClockReceiver as an inappropriate attempt at compile-time polymorphism

Components/6522/6522.hpp, Components/6532/6532.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock SignalTests/Bridges/TestMachineZ80.h, OSBindings/Mac/Clock SignalTests/Bridges/TestMachineZ80.mm, OSBindings/Mac/Clock SignalTests/Z80MemptrTests.swift, Processors/Z80/Z80.hpp
Proposed for merging as a presently incomplete set to avoid merge conflicts with the upcoming Z80 switch to full half-cycle timing.
=> Introduces a subset of necessary test cases for the Z80 memptr register, and corrects implementation to match

Machines/ZX8081/ZX8081.cpp, OSBindings/Mac/Clock SignalTests/6502TimingTests.swift, OSBindings/Mac/Clock SignalTests/Bridges/TestMachine6502.mm, OSBindings/Mac/Clock SignalTests/Bridges/TestMachineZ80.h, OSBindings/Mac/Clock SignalTests/Bridges/TestMachineZ80.mm, OSBindings/Mac/Clock SignalTests/FUSETests.swift, OSBindings/Mac/Clock SignalTests/Z80MachineCycleTests.swift, Processors/6502/6502AllRAM.cpp, Processors/AllRAMProcessor.cpp, Processors/AllRAMProcessor.hpp, Processors/Z80/Z80.hpp, Processors/Z80/Z80AllRAM.cpp, Processors/Z80/Z80AllRAM.hpp
Simultaneously adjusts test machines to talk in half cycles since that's a new potential failure case to test for: for some reason the Z80 finishes a complete machine cycle on a half clock cycle.
Various affected tests are updated in response.
=> Adjusts the timing of the Z80's wait line sampling to be on a half clock and better regularises 'action' partial bus cycles

ClockReceiver/ClockReceiver.hpp, Machines/Electron/Electron.cpp, Processors/Z80/Z80AllRAM.cpp
Specifically to avoid accidental to-int conversions that go via the `bool` and therefore get entirely the wrong result, and so that objects counting `HalfCycle`s for communication with a `run_for(Cycles)` don't have to duplicate storage.
=> Revokes the operator bool() on WrappedInt and simplifies/generalises HalfClockReceiver

ClockReceiver/ClockReceiver.hpp, Machines/Electron/Electron.cpp, Machines/Electron/Electron.hpp, Machines/Electron/Typer.cpp, Machines/Typer.cpp, Machines/Typer.hpp, Machines/ZX8081/ZX8081.cpp, Machines/ZX8081/ZX8081.hpp
Thereby making it easier to clock consistently regardless of unit.
... which necessitated adding a negative operator for WrappedInts.
=> Brings `Typer` into the new `run_for` orthodoxy

Outputs/CRT/CRT.cpp, Outputs/CRT/CRT.hpp
It now triggers the format-defined period from the start of vertical sync, rather than shortly after the end provided that sync was long enough.
=> Adjusts vertical sync detection

Machines/AmstradCPC/AmstradCPC.hpp, Machines/ZX8081/ZX8081.hpp
Which means not having to repeat the meaning of set_key_state and clear_all_keys. So: a minor DRY improvement.
=> Publicly declares the ZX80/81 and Amstrad CPC as keyboard machines

Components/6845/CRTC6845.hpp, Machines/AmstradCPC/AmstradCPC.cpp
... and makes the CRTC's vertical sync timing dependent on the programmed value, though that should probably depend on CRTC manufacturer. So a WD177x-esque 'personality' property will be forthcoming.
=> Corrects two misimplementations of the CPC's interrupt counter

Machines/AmstradCPC/AmstradCPC.cpp
Specifically to make sure it doesn't inadvertently compact register writes.
=> Corrects the CPC's handling of AY time accumulation

Components/1770/1770.cpp, Components/8272/i8272.cpp, Components/8272/i8272.hpp, Machines/AmstradCPC/AmstradCPC.cpp, Machines/AmstradCPC/AmstradCPC.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, StaticAnalyser/AmstradCPC/StaticAnalyser.cpp, StaticAnalyser/StaticAnalyser.hpp, Storage/Disk/DiskController.cpp, Storage/Disk/DiskController.hpp, Storage/Disk/Formats/CPCDSK.cpp, Storage/Disk/MFMDiskController.cpp, Storage/Disk/MFMDiskController.hpp
This is achieved partly by copying out the PLL stream -> event stream code of the WD1770. A next step will be to turn that into a proper outward factoring; several other divergent possibilities present themselves though so this is offered for a merge.
Also included:
* improved .DSK support, including the EXTENDED version.
=> Introduces the beginning seeds 8272 emulation, and therefore floppy emulation for the CPC

Components/8255/i8255.hpp, Components/AY38910/AY38910.cpp, Components/AY38910/AY38910.hpp
Specifically, on the AY, to ensure that ports configured as output return their outputting values as input, and to treat selection of an invalid register as a way of avoiding any effect from future writes. On the 8255, to introduce some respect for input/output selection in the control word.
=> Makes various AY input/output fixes, and a few 8255 fixes along the way

Components/6845/CRTC6845.hpp
Which was making frames 304 lines by default, and explains why Robocop and Elite had their mode splits so incorrectly placed.
=> Corrects an off-by-one error in [character] line counting within the 6845

Components/AY38910/AY38910.cpp
Based on empirical evidence only: my comparison of the Robocop theme music versus that captured on Youtube.
=> Switches to guessing that the AY doesn't reset its dividers upon frequency changes

StaticAnalyser/AmstradCPC/StaticAnalyser.cpp
They have a catalogue that is correctly read, but can be launched without reference to it.
=> Corrects analysis of CPC system disks

StaticAnalyser/AmstradCPC/StaticAnalyser.cpp, Storage/Disk/Encodings/MFM.cpp
1. treating ".   " as a special case, rather than in combination with ".BIN" and ".BAS" (i.e. the three that AMSDOS is happy to take an implicit suffix for);
2. not recognising that some files have no storage whatsoever, and therefore no header to check for a BASIC flag in.
=> Corrects a couple of CPC static analysis pitfalls

Components/1770/1770.cpp, Components/8272/i8272.cpp, Components/8272/i8272.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, Storage/Disk/Disk.cpp, Storage/Disk/DiskController.cpp, Storage/Disk/DiskController.hpp, Storage/Disk/MFMDiskController.cpp, Storage/Disk/MFMDiskController.hpp, Storage/Disk/PCMPatchedTrack.cpp, Storage/Disk/PCMPatchedTrack.hpp, Storage/Disk/UnformattedTrack.cpp, Storage/Disk/UnformattedTrack.hpp
Specifically to fix:
* an issue with patches on PCM patched tracks that have been left trimmed;
* to add asserts generally around that area;
* better to handle writes that run over the index hole;
* to make it easy for controllers to avoid writing over the index hole if desired; and
* in the 8272, to collect a bunch of repetitive actions into a common location and better to find error conditions.
=> Improves the 8272 and the whole disk infrastructure behind it

Components/6560/6560.hpp
Undoing a phoney adjustment in the other direction.
=> Corrects Vic-I NTSC colour output

Machines/AmstradCPC/AmstradCPC.cpp, StaticAnalyser/AmstradCPC/StaticAnalyser.cpp
Also removes from the loading command any extraneous spaces and adds the logic to type the file extension if required, though at the minute such a file is never selected.
=> Corrects a couple of cases in which the CPC analyser could pick an incorrect loading command

StaticAnalyser/AmstradCPC/StaticAnalyser.cpp, Storage/Disk/Parsers/CPM.cpp
Specifically by considering that:
* it won't be anything with a special character in it;
* if all that's left is system files, it might actually be a system file;
* another potential way that one file can be intended to draw a reader's eye is if it is the only one with a different name.
Also adjusts the CP/M catalogue fetcher: the catalogue allocation bitmap is supposed to be in units of a block, not units of a sector. So on the CPC I was throwing half the catalogue away.
=> Improves the CPC static analyser's correct file name predictions

Storage/Disk/Disk.cpp, Storage/Disk/Encodings/MFM.cpp, Storage/Disk/Formats/CPCDSK.cpp
* imposes a maximum track size (conservatively) when encoding MFM content;
* applies slightly smarter logic when parsing MFM streams for static analysis so that sectors that cross the index hole don't usually lead to an infinite loop. Should find a way to track the actual index hole though; and
* ensured that the extended DSK format does the proper thing when faced with zero-length tracks (i.e. tracks that are declared to exist but for which no data is provided).
=> Various MFM and DSK fixes

Storage/Disk/Encodings/MFM.cpp
Also increases the limit offered to disks encoded from sector-oriented file formats: they may provide up to 10% more data than an archetypal track.
=> Improves the variability of the MFM parser used for static analysis

Components/8272/i8272.cpp, Components/8272/i8272.hpp, Machines/AmstradCPC/AmstradCPC.cpp, Machines/Typer.hpp, Storage/Disk/Drive.cpp, Storage/Disk/Drive.hpp
Primarily:
* being smarter about which parts of the palette tables to touch upon palette changes;
* ensuring a timed typer stops being talked to once finished (which will benefit the Electron too);
* applying an even broader sleep test in the 8272, and ensuring it starts up in a valid state; and
* applying a slightly faster has_disk test in drives (which will benefit all disk-based machines).
=> Makes a variety of minor performance improvements to the CPC

Processors/Z80/Z80.hpp
It's now checked only after each outward `perform_machine_cycle`.
=> Removes repeated checking of bus_request_line_ by the Z80.

Machines/AmstradCPC/AmstradCPC.cpp, Storage/Tape/Tape.cpp
Specifically:
* the false belief that `this` will always be the address known to the object owner (it won't be, because of inheritance); and
* the binary tape player's habit of announcing upon every message it receives about the tape motor, which in a CPC is wired to the same atomic output as keyboard row selection.
=> Cleans up issues affecting the sleeper mechanism and the CPC

ClockReceiver/ForceInline.hpp, Machines/AmstradCPC/AmstradCPC.cpp, Machines/Atari2600/Cartridges/Cartridge.hpp, Machines/Commodore/1540/C1540.hpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Electron/Electron.cpp, Machines/Oric/Oric.cpp, Machines/ZX8081/ZX8081.cpp, OSBindings/Mac/Clock SignalTests/Bridges/TestMachine6502.h, OSBindings/Mac/Clock SignalTests/Bridges/TestMachine6502.mm, OSBindings/Mac/Clock SignalTests/PCMPatchedTrackTests.mm, Processors/6502/6502.hpp, Processors/6502/6502AllRAM.cpp, Processors/6502/6502AllRAM.hpp, Processors/Z80/Z80.hpp, Processors/Z80/Z80AllRAM.cpp
Also:
* gets a bit more explicit with `override final` in all files that were touched anyway for forceinline;
* removes `return_from_subroutine` from the 6502 on the grounds that (i) nobody uses it; and (ii) doing so reduces the number of call sites to `perform_bus_cycle` to just one for 6502 machines that don't use the ready line; and
* fixes the 6502 test vehicle.
=> Introduces compile-time selection of minor CPU core features and applies forceinline when appropriate

Components/6845/CRTC6845.hpp, Machines/AmstradCPC/AmstradCPC.cpp
Specifically to allow for sync signals becoming active during phase 2 of a clock cycle (which is accurate to my current understanding). Also adjusts the CPC to catch and react appropriately.
=> Refines observable 6845 behaviour

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, StaticAnalyser/StaticAnalyser.cpp, StaticAnalyser/ZX8081/StaticAnalyser.cpp, StaticAnalyser/ZX8081/StaticAnalyser.hpp, Storage/Cartridge/Cartridge.hpp, Storage/Tape/Formats/TapeUEF.cpp, Storage/Tape/Formats/TapeUEF.hpp, Storage/Tape/Formats/ZX80O81P.cpp, Storage/Tape/Formats/ZX80O81P.hpp, Storage/TargetPlatforms.hpp
Which specifically resolves .o/.p ZX80/81 confusion as a first step, causes the UEF's 0005 chunk to be obeyed, and will likely permit similar support for TZX's hardware info in the future.
=> Factors the concept of a target platform out from the static analyser, allowing file formats to opine

Machines/Electron/Electron.cpp, Machines/Electron/Plus3.cpp, Machines/Electron/Plus3.hpp, Machines/Electron/Speaker.hpp, Machines/Electron/Tape.cpp, Machines/Electron/Tape.hpp, Machines/Electron/Video.cpp, Machines/Electron/Video.hpp
Specifically to resolve an error with shift being pressed at startup due to a failure to establish a default value for that flag, but applying the same principle across the board.
=> Ensures all parts of the Electron have a fully-defined initial state.

Processors/Z80/Implementation/Z80Base.cpp, Processors/Z80/Implementation/Z80Implementation.hpp, Processors/Z80/Implementation/Z80Storage.hpp
Almost all opcode table generation macros and code now resides neatly in the world of .CPP.
=> Further strips back the amount exposed in Z80-related headers.

Components/1770/1770.cpp, Components/1770/1770.hpp, Components/8272/i8272.cpp, Components/8272/i8272.hpp, Machines/AmstradCPC/AmstradCPC.cpp, Machines/Commodore/1540/Implementation/C1540.cpp, Machines/Commodore/1540/Implementation/C1540Base.hpp, Machines/Electron/Plus3.cpp, Machines/Electron/Plus3.hpp, Machines/Oric/Microdisc.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, StaticAnalyser/Commodore/Disk.cpp, Storage/Disk/DiskController.cpp, Storage/Disk/DiskController.hpp, Storage/Disk/Drive.cpp, Storage/Disk/Drive.hpp, Storage/Disk/Encodings/MFM.cpp, Storage/Disk/Encodings/MFM.hpp, Storage/Disk/MFMDiskController.cpp, Storage/Disk/MFMDiskController.hpp, Storage/Disk/SingleTrackDisk.cpp, Storage/Disk/SingleTrackDisk.hpp, Storage/TimedEventLoop.cpp, Storage/TimedEventLoop.hpp
Thereby eliminating an improper coupling of concerns, better to match real life.
Reshuffle side effects:
* the base controller constructor now takes a clock rate only; it has no business knowing RPM and I decided to withdraw the multiplier while I was at it, being an implementation detail;
* drives supply a more accurate ready signal;
* the 8272 refuses access commands while ready is inactive (partly as a test);
* the 8272 also no longer owns drives. It just knows how to signal its selection;
* similarly, the WD1770 now announces motor control for the benefit of its subclasses, not directly to its drives. So the Plus 3 has to propagate that itself. The Oric Microdisc is 1793-based where there is no direct motor control, so is unaffected;
* the C1540 has been brought into line with the …
=> Devolves `TimedEventLoop` ownership from disk controllers to drives

Components/8272/i8272.cpp, Components/8272/i8272.hpp, Machines/AmstradCPC/AmstradCPC.cpp, Machines/Commodore/1540/Implementation/C1540.cpp, Machines/Electron/Plus3.cpp, Machines/Oric/Microdisc.cpp, StaticAnalyser/Commodore/Disk.cpp, Storage/Disk/DiskController.cpp, Storage/Disk/Drive.cpp, Storage/Disk/Drive.hpp, Storage/Disk/Encodings/MFM.cpp
* the drive now really is single sided;
* the 8272 can no longer end up with a surplus of result bytes upon overrun;
* the 8272 reacts if a drive ceases to be ready while a command is ongoing.
=> Improves CPC disk emulation

Components/AY38910/AY38910.cpp, Machines/AmstradCPC/AmstradCPC.cpp, Machines/Atari2600/Cartridges/Pitfall2.hpp, Machines/Atari2600/TIA.cpp, Machines/Commodore/1540/Implementation/C1540.cpp, Machines/Commodore/SerialBus.cpp, Machines/Electron/Video.cpp, Machines/Utility/Typer.cpp, Machines/ZX8081/ZX8081.cpp, Outputs/CRT/CRT.cpp, Outputs/CRT/Internals/CRTOpenGL.cpp, Processors/6502/Implementation/6502Implementation.hpp, Processors/Z80/Implementation/Z80Implementation.hpp, Storage/Data/ZX8081.cpp, Storage/Disk/Controller/DiskController.cpp, Storage/Disk/Drive.cpp, Storage/Tape/Formats/TZX.cpp, Storage/Tape/Formats/TapeUEF.cpp, Storage/Tape/Tape.cpp
For the benefit of cross-platform compatibility.
=> Commutes cross-platform `#pragma mark`s to `//MARK:`s.

OSBindings/SDL/main.cpp
This makes my pervasive use of `#version 150` GLSL valid.
=> Adds an explicit request for OpenGL 3.2 under SDL.

Outputs/CRT/Internals/CRTOpenGL.cpp, Outputs/CRT/Internals/Shaders/IntermediateShader.cpp, Outputs/CRT/Internals/Shaders/OutputShader.cpp
Without this change, GCC versions >4.8 will error with things like:
```
./CLK/Outputs/CRT/Internals/CRTOpenGL.cpp:154:2:error: uninitialized const member
'Outputs::CRT::OpenGLOutputBuilder::draw_frame(unsigned int, unsigned int, bool)::RenderStage::target'
```
=> Initialize all `const` members.

Components/9918/9918.cpp
Thereby corrects sprites on line 0.
=> Adds one-before-the-graphics as a line for TMS video collection.

OSBindings/Mac/Clock Signal/AppDelegate.swift, OSBindings/Mac/Clock Signal/Info.plist, StaticAnalyser/Acorn/StaticAnalyser.cpp, StaticAnalyser/MSX/StaticAnalyser.cpp, Storage/Cartridge/Cartridge.hpp
Also corrects UTI declarations so that File->Open..., etc, work for files named .rom on the Mac (hopefully) regardless of any other applications you might have installed that accept things called .rom.
=> Allows 8kb and not-quite-multiple-of-8kb MSX ROMs

Storage/Tape/Formats/CSW.cpp, Storage/Tape/Formats/CSW.hpp, Storage/Tape/Formats/TZX.cpp, Storage/Tape/Formats/TZX.hpp, Storage/Tape/PulseQueuedTape.cpp, Storage/Tape/PulseQueuedTape.hpp
Towards that aim, simplifies CSW handling so that even regular RLE compression uses a static grab of file contents.
Deals with https://github.com/TomHarte/CLK/issues/342
=> Makes an attempt at implementing all missing TZX 1.20 blocks.

OSBindings/Mac/Clock SignalTests/Z80MemptrTests.swift, Processors/Z80/Implementation/Z80Implementation.hpp, Processors/Z80/Implementation/Z80Storage.cpp, Processors/Z80/Implementation/Z80Storage.hpp
A further step towards https://github.com/TomHarte/CLK/issues/312
Improves success rate on the Raxoft tests from 0% to 28%, albeit only because a failed test was causing memptr never to be exposed.
=> Improves Z80 memptr behaviour.

Components/6560/6560.cpp, Components/6560/6560.hpp, Components/AY38910/AY38910.cpp, Components/AY38910/AY38910.hpp, Components/KonamiSCC/KonamiSCC.cpp, Components/KonamiSCC/KonamiSCC.hpp, Components/SN76489/SN76489.cpp, Components/SN76489/SN76489.hpp, Machines/Atari2600/TIASound.cpp, Machines/Atari2600/TIASound.hpp, Machines/Electron/SoundGenerator.cpp, Machines/Electron/SoundGenerator.hpp, Machines/MSX/MSX.cpp, Outputs/Speaker/Implementation/CompoundSource.hpp, Outputs/Speaker/Implementation/LowpassSpeaker.hpp, Outputs/Speaker/Implementation/SampleSource.hpp
Previously every output device was making its own decision. Which is increasingly less sustainable due to the CompoundSource.
=> Introduces formal setting of the output volume to `SampleSource`.

Machines/AmstradCPC/AmstradCPC.cpp, Machines/AmstradCPC/AmstradCPC.hpp, Machines/Atari2600/Atari2600.cpp, Machines/Atari2600/Atari2600.hpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Commodore/Vic-20/Vic20.hpp, Machines/Electron/Electron.cpp, Machines/Electron/Electron.hpp, Machines/KeyboardMachine.hpp, Machines/Oric/Oric.cpp, Machines/Oric/Oric.hpp, Machines/Utility/Typer.hpp, Machines/ZX8081/ZX8081.cpp, Machines/ZX8081/ZX8081.hpp
Specifically by pulling the key action stuff into a purely abstract class [/interface]. Takes the opportunity to unpublish a bunch of machine details.
Thereby resolves https://github.com/TomHarte/CLK/issues/308
=> Eliminates diamond inheritance of KeyboardMachine::Machine by typers.

Analyser/Dynamic/MultiMachine/Implementation/MultiCRTMachine.cpp, Analyser/Dynamic/MultiMachine/Implementation/MultiCRTMachine.hpp, Analyser/Dynamic/MultiMachine/Implementation/MultiSpeaker.cpp, Analyser/Dynamic/MultiMachine/Implementation/MultiSpeaker.hpp, ClockReceiver/TimeTypes.hpp, Concurrency/BestEffortUpdater.cpp, Concurrency/BestEffortUpdater.hpp, Machines/CRTMachine.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/Mac/Clock Signal/Updater/CSBestEffortUpdater.h, OSBindings/Mac/Clock Signal/Updater/CSBestEffortUpdater.mm, OSBindings/SDL/main.cpp, Outputs/Speaker/Implementation/LowpassSpeaker.hpp, Outputs/Speaker/Speaker.hpp
As well as reducing per-target code (albeit just predictable wiring, as the BestEffortUpdater handled this), this simplifies the concept of a multimachine somewhat.
=> Devolves time -> clock rate mapping to machines.

Analyser/Dynamic/MultiMachine/Implementation/MultiJoystickMachine.cpp, Analyser/Dynamic/MultiMachine/Implementation/MultiJoystickMachine.hpp, Analyser/Dynamic/MultiMachine/Implementation/MultiSpeaker.cpp
Thereby 'completes' (i.e. for now) multimachine implementation.
This should resolve https://github.com/TomHarte/CLK/issues/361 for the time being, at least unless or until I find something that doesn't cause the 2600 to detect failure.
=> Implements multimachine joystick support.

Analyser/Static/Commodore/StaticAnalyser.cpp, Components/6560/6560.cpp, Components/6560/6560.hpp, Machines/Commodore/Vic-20/Vic20.cpp, OSBindings/Mac/Clock Signal/New Group/Base.lproj/MachinePicker.xib
Also ensures that pressing 'enter' can confirm the machine selector, and that the 'has C1540' box works for a Vic-20.
This deals with the "splits ... happen at the wrong place" part of #411 though "that changes of the colour registers on real h/w take effect one hires pixel" remains dangling.
As issues tangentially arising it also:
- reduces the diversity of luminances in the VIC; and
- makes the Mac's new machine dialogue respond to enter, and makes sure that the user's selection as to inclusion of a C1540 is honoured.
=> Corrects NTSC VIC raster register timing.

Components/DiskII/DiskII.cpp, Components/DiskII/DiskII.hpp
Only if required. In order to support various potential forms of supplied ROM.
=> Shuffles the Disk II ROM at load time into B.A.P. form.

Machines/AppleII/AppleII.cpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Oric/Oric.cpp, Machines/Utility/StringSerialiser.cpp, Machines/Utility/StringSerialiser.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj
Resolves #435
Specifically:
* string serialisation with \r\n converion, not that there's much to it, is factored out of the Apple II; and
* the Oric emulation now feeds ASCII directly to the machine via the keyboard buffer byte whenever that address is read, rather than faking keypresses.
=> Corrects Oric text pasting.

Components/DiskII/DiskII.cpp, Components/DiskII/DiskII.hpp, Concurrency/BestEffortUpdater.cpp, Machines/AppleII/AppleII.cpp, Machines/AppleII/Card.hpp, Machines/AppleII/DiskIICard.cpp, Machines/AppleII/DiskIICard.hpp, Machines/Oric/Oric.cpp, Storage/Disk/DiskImage/Formats/AppleDSK.cpp, Storage/Disk/DiskImage/Formats/AppleDSK.hpp, Storage/Disk/Track/PCMPatchedTrack.cpp, Storage/Disk/Track/PCMPatchedTrack.hpp, Storage/Disk/Track/PCMTrack.cpp, Storage/Disk/Track/PCMTrack.hpp, Storage/Disk/Track/Track.hpp, Storage/Disk/Track/TrackSerialiser.cpp, Storage/Disk/Track/TrackSerialiser.hpp, Storage/Disk/Track/UnformattedTrack.cpp, Storage/Disk/Track/UnformattedTrack.hpp
In particular:
* lowers the level of bus communications to allow the Disk II to read the data bus at any time and not load the bus at all even on a read cycle;
* fleshes out and corrects the state machine re: unused commands, the single shift register, the proper computation of is-read-only;
* implements some of the more subtle effects of various soft switches; and
* ensures only one drive is powered at a time.
As a side effect, it also enhances the Apple II's internal slot system.
=> Substantially improves Disk II emulation, including write support

NumberTheory/CRC.hpp, OSBindings/Mac/Clock SignalTests/CRCTests.mm, Storage/Disk/Controller/MFMDiskController.cpp, Storage/Disk/Controller/MFMDiskController.hpp, Storage/Disk/DiskImage/Formats/AppleDSK.cpp, Storage/Disk/DiskImage/Formats/WOZ.cpp, Storage/Disk/DiskImage/Formats/WOZ.hpp, Storage/Disk/Encodings/MFM/Encoder.cpp, Storage/Disk/Encodings/MFM/Encoder.hpp, Storage/Disk/Encodings/MFM/Shifter.cpp, Storage/Disk/Encodings/MFM/Shifter.hpp, Storage/FileHolder.hpp, Storage/Tape/Parsers/Acorn.cpp, Storage/Tape/Parsers/Acorn.hpp
Since WOZ files include a CRC32 to verify file contents, this also generalises what was `CRC16` into a generic templated `CRC::Generator` from which both the 16-bit CCITT generator used by FM/MFM disks and Acorn tapes, and the CRC32 used for WOZ file verification can be instantiated.
=> Implements write support for WOZ files

Components/6560/6560.hpp, Components/AY38910/AY38910.hpp, Components/DiskII/DiskII.cpp, Machines/AppleII/Video.cpp, Machines/AppleII/Video.hpp, Machines/Atari2600/TIA.cpp, Machines/ZX8081/Video.cpp, Machines/ZX8081/Video.hpp, Machines/ZX8081/ZX8081.cpp, Outputs/CRT/CRT.cpp, Outputs/CRT/CRT.hpp, Outputs/CRT/Internals/Shaders/IntermediateShader.cpp
As per #399 the Apple II was originally selected as a candidate for addition because it produces a direct, fully-defined PCM video stream. In many other machines the exact manner of colour signal generation is either undefined or implicitly dependent upon analogue components. I therefore hoped it would confirm or deny my NTSC implementation.
Despite initially believing it confirmed my implementation based on low-resolution mode, it turns out I had still made coupled errors on both sides of the NTSC chasm. My low-resolution mode was shifting colour values in reverse.
High-resolution mode shifts correctly, but had acquired an odd effect: two out of four colours (not counting black and white) were the wrong way around. I should have noticed, but didn't.
Regardless, diagnosing that revealed …
=> Corrects NTSC Q phase

Analyser/Dynamic/MultiMachine/Implementation/MultiJoystickMachine.cpp, Inputs/Joystick.hpp, Machines/AppleII/AppleII.cpp, Machines/Atari2600/Atari2600.cpp, Machines/ColecoVision/ColecoVision.cpp, Machines/Commodore/Vic-20/Vic20.cpp, OSBindings/Mac/Clock Signal/Base.lproj/MainMenu.xib, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/SDL/main.cpp
Includes broadening the internal joystick interface to support analogue inputs, with an attempt automatically to map between digital and analogue axis inputs if the real input device doesn't match the emulated one.
Also adds a keyboard as [joystick/keyboard] selection switch for Mac users, to allow testing in advance of adding support for real joysticks.
=> Introduces Joystick support for the Apple II

Machines/AmstradCPC/AmstradCPC.cpp, Machines/AmstradCPC/AmstradCPC.hpp, Machines/Electron/Electron.cpp, Machines/Utility/MachineForTarget.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Base.lproj/CompositeOptions.xib, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm
Specifically:
* sync sent to the monitor is still triggered by but independent of the hsync signal from the CRTC;
* however neither pixels nor border are output while CRTC hsync is active;
* a colour burst is posted after the sync level, then the blank level is adopted until hsync falls.
Since there is now a colour burst, composite video is enabled for the CPC.
This addresses the oversized left border of #473.
=> Corrects left-border handling on the CPC

Storage/Tape/Formats/TZX.cpp
=> Corrects TZX custom info block parsing.

OSBindings/SDL/main.cpp
When saving screenshots.
Another step towards #501
=> Ensures SDL is properly informed of buffer byte order.

OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Info.plist, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm
Specifically to:
* ensure that 'Insert...' isn't offered for machines that don't accept new media while running;
* provide a hint that the inert dialogue need not be used;
* make sure 'keyboard as keyboard' isn't ticked for machines without keyboards; and
* to try again to make the file type icons work.
=> Tweaks the Mac UI

Machines/AppleII/AppleII.cpp, Machines/Atari2600/Cartridges/Cartridge.hpp, Machines/Commodore/1540/Implementation/C1540.cpp, Machines/Commodore/1540/Implementation/C1540Base.hpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Electron/Electron.cpp, Machines/Oric/Oric.cpp, OSBindings/Mac/Clock SignalTests/Bridges/TestMachine6502.mm, Processors/6502/6502.hpp, Processors/6502/AllRAM/6502AllRAM.cpp, Processors/6502/Implementation/6502Implementation.hpp, Processors/6502/Implementation/6502Storage.cpp, Processors/6502/Implementation/6502Storage.hpp
UNREADY!
Introduces profiles for the:
- 6502;
- NES 6502;
- Synertek 65C02 (seemingly a synonym of the 65SC02);
- WDC 65C02 (with added bit instructions, but no STP or WEI); and
- Rockwell 65C02 (like the WDC, but with added STP and WEI).
Corrects the following errors in the prior 65C02 implementation:
* ensures D is clear on NMI and RST;
* prevents NMI from usurping BRK.
* indexing across a page boundary on the 65C02 rereads the last instruction byte rather than an incorrect address;
* read-modify-write absolute indexed (i.e. abs,x and abs,y) ASL, LSR, ROL and ROR with no page boundary crossing complete in 6 cycles rather than 7; and
* branches that complete in three cycles (i.e. branch taken, no page crossing) can no longer segue directly into responding to an IRQ or NMI. Reacting is …
=> Further corrects 65C02 behaviour

ClockReceiver/ClockDeferrer.hpp, Machines/AppleII/AppleII.cpp, Machines/AppleII/Video.cpp, Machines/AppleII/Video.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj
Resolves #528 ; also contains a variety of rearrangements that help to separate logic a little more neatly, and introduces the `ClockDeferrer` to help almost anywhere that an action has a delayed effect.
=> Corrects Apple II video defects

OSBindings/Mac/Clock Signal/Info.plist
LSItemContentTypes should be unique identifiers, not generic types like `public.item` or `public.data`.
This can result in the app's icons showing up in the wrong places.
Also added a category type.
=> Remove LSItemContentTypes

Components/6560/6560.hpp, Components/9918/9918.cpp, Machines/AmstradCPC/AmstradCPC.cpp, Machines/AppleII/Video.cpp, Machines/Atari2600/TIA.cpp, Machines/Electron/Video.cpp, Machines/Electron/Video.hpp, Machines/Oric/Video.cpp, Machines/ZX8081/Video.cpp, Outputs/CRT/CRT.hpp, Outputs/CRT/Internals/CRTOpenGL.cpp, Outputs/CRT/Internals/CRTOpenGL.hpp, Outputs/CRT/Internals/Shaders/IntermediateShader.cpp, Outputs/CRT/Internals/Shaders/IntermediateShader.hpp, Outputs/CRT/Internals/TextureBuilder.cpp, Outputs/CRT/Internals/TextureBuilder.hpp
By eliminating the last vestige of storing multiple output samples in single texture samples. So the minimum size of an output sample is now 1 byte.
This is part of the opening salvo in removing the OpenGL assumption, in addition to being an actual observable issue.
=> Resolves potential Electron output errors

Machines/AppleII/Video.cpp
So that light blue is more like a blue.
=> Turns down the Apple II brightness a little.

Processors/6502/6502.hpp
Also shuffles the NES CPU type up into the top position, so this is a strict progression in terms of functionality.
=> Corrects Rockwell and WDC references.

Components/9918/9918.cpp, Components/9918/Implementation/9918Base.hpp, Outputs/CRT/Internals/TextureBuilder.hpp
Also seeks to ensure a more obviously-guaranteed crash should there be a regression in the future.
Issue was: telling the CRT to output data without having previously asked for somewhere to put it. Fix is: make sure that request occurs. For future consideration: make the CRT tolerant to that misuse?
Fixes #560
=> Corrects likely crash shortly after starting a TMS9918 or derivative

Components/9918/9918.cpp
i.e. respective to reading; sprite collision times now seem correct.
=> Slightly adjusts pixel output time.

Components/9918/Implementation/9918Base.hpp
This prevents a potential crash at startup.
=> Ensures offset and flags are initialised to 0.

Machines/AppleII/AppleII.cpp, Machines/AppleII/AppleII.hpp, Machines/AppleII/Video.cpp, Machines/AppleII/Video.hpp, Machines/Oric/Oric.cpp, Machines/Utility/MachineForTarget.cpp, OSBindings/Mac/Clock Signal/Base.lproj/AppleIIOptions.xib, OSBindings/Mac/Clock Signal/Documents/MachinePanel.swift, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, Outputs/OpenGL/Primitives/Shader.cpp, Outputs/OpenGL/Primitives/Shader.hpp, Outputs/OpenGL/ScanTarget.cpp, Outputs/OpenGL/ScanTarget.hpp, Outputs/OpenGL/ScanTargetGLSLFragments.cpp
This diversion back into OpenGL is taking far too long; essentially this switches the whole flow back to what it was for calculating chrominance — a point sample at four times the colour subcarrier, subject to a rolling average.
As it keeps luminance at full output resolution, this does not negate resolution of the aliasing issue.
=> Reintroduces a separate chrominance buffer

Machines/ColecoVision/ColecoVision.cpp
Resolves #586
That being said, I've lost confidence in my calculation of 3 cycles to access the SN. So I might need to revisit that.
=> Adds a single-cycle M1 delay to the ColecoVision.

Machines/MSX/MSX.cpp, Storage/Tape/Formats/CAS.cpp, Storage/Tape/Formats/CAS.hpp
Specifically:
* the fast tape hack could engage even when the BIOS isn't paged, causing it to intercede in software it knows nothing about; and
* CAS turns out to be a lot more nuanced than I naively believed. A much more complicated parser has been substituted for the original.
This is believed to fix #546 .
=> Fixes various MSX tape-handling bugs, and adds a status LED.

OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/Mac/Clock Signal/Views/CSOpenGLView.h, OSBindings/Mac/Clock Signal/Views/CSOpenGLView.m, OSBindings/SDL/main.cpp, Outputs/OpenGL/ScanTarget.cpp, Outputs/OpenGL/ScanTarget.hpp
On the Mac, draw is now called without an update for resizing events, and anything else requested by AppKit. In all other cases — including from the SDL version — both are called as if they were still a single function.
=> Splits OpenGL ScanTarget update and draw functions.

OSBindings/Mac/Clock Signal/Views/CSOpenGLView.m, Outputs/OpenGL/ScanTarget.cpp
Also makes sure that ScanTarget's `draw` is safe to call prior to `update`.
Resolves #599
=> Reintroduces proper locking of the Mac OpenGL context.

Processors/Z80/Z80.hpp
Just some small corrections to the comments that I came across while reading the code.
=> Correct typos in Z80.hpp

Outputs/OpenGL/ScanTarget.cpp, Outputs/OpenGL/ScanTarget.hpp, Outputs/OpenGL/ScanTargetGLSLFragments.cpp
=> Disallows smaller buffer use for 'sharp' displays and tightens sampling window.

Outputs/OpenGL/ScanTarget.cpp, Outputs/OpenGL/ScanTarget.hpp
Resolves a potential crash-at-startup with the Vic-20, at least. Also just plain makes sense.
=> Permits end_data only after a begin_data.

Components/8530/z8530.cpp, Components/8530/z8530.hpp, Machines/Apple/Macintosh/Macintosh.cpp, OSBindings/Mac/Clock SignalTests/68000Tests.mm, OSBindings/Mac/Clock SignalTests/EmuTOSTests.mm, OSBindings/Mac/Clock SignalTests/QLTests.mm, Processors/68000/68000.hpp, Processors/68000/Implementation/68000Implementation.hpp, Processors/68000/Implementation/68000Storage.cpp, Processors/68000/Implementation/68000Storage.hpp
On the 68000: reduced the size of instruction tables, by almost 80%. Specifically, from 5,342,080 bytes to 1,116,576 — from an amount that definitely wouldn't fit in L2 cache to one that might, even if still unfortunately hefty.
On the Macintosh: took interrupt level selection outside of the loop, experiments with tightening graphics update triggers.
=> Attempts to improve 68000 (and Macintosh) emulation speed

OSBindings/SDL/SConstruct
I was trying to build the program using scons as installed from Python 3, but ran into issues with the `reload` and `sys.setdefaultencoding` functions, both of which were removed in Python 3. Seeing as they're not needed, I added a check to only run those functions if the user is using Python 2 or below.
=> Allow for scons to run on Python 3

Machines/Apple/Macintosh/Macintosh.cpp, Processors/68000/Implementation/68000Implementation.hpp
Which slightly simplifies the Macintosh, as a side effect.
=> Corrects 68000 address lines during interrupt acknowledgement.

Processors/68000/Implementation/68000Implementation.hpp, Processors/68000/Implementation/68000Storage.hpp
As per comment, that is definitely the only place it can occur; I don't know whether it always occurs there.
=> Moves timing of interrupt sampling into prefetch queue advancement.

Machines/Apple/Macintosh/Macintosh.cpp, Machines/Apple/Macintosh/Video.cpp, Machines/Apple/Macintosh/Video.hpp
This is probably the proper scheme for the Macintoshes I actually implement.
=> Implements every-other-cycle-during-pixels RAM timing.

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock Signal/ROMRequester/ROMRequester.xib, Processors/Z80/Z80.hpp
The updated compiler also flagged a potential issue with CPU::Z80::Register not being a namespace re: 'Refresh' versus CPU::Z80::PartialMachineCycle. I don't entirely see it, but this fixes the problem.
I also finally figured out what the compiler was trying to tell me about ROMRequester.xib.
=> Updates to Xcode11 recommended project settings.

Inputs/Keyboard.cpp, Inputs/Keyboard.hpp, Machines/Apple/Macintosh/Keyboard.cpp, Machines/Apple/Macintosh/Keyboard.hpp, Machines/Apple/Macintosh/Macintosh.cpp, Machines/KeyboardMachine.cpp, Machines/KeyboardMachine.hpp, Machines/MasterSystem/MasterSystem.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock Signal/AppDelegate.swift, OSBindings/Mac/Clock Signal/CSApplication.h, OSBindings/Mac/Clock Signal/CSApplication.m, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Info.plist, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/Mac/Clock Signal/Views/CSOpenGLView.h, OSBindings/Mac/Clock Signal/Views/CSOpenGLView.m
In Cocoa world, a machine that declares 'command' as essential will usurp normal keyboard shortcuts, at least if it also allows mouse capture. I'm on the fence about the best approach for any non-capturing machines that may come. Arguably the Apple II is one already.
=> Allows machines to declare modifiers as 'essential'.

Machines/Apple/AppleII/AppleII.cpp, Machines/Apple/AppleII/Card.hpp, Machines/Apple/AppleII/DiskIICard.cpp, Storage/Disk/Drive.cpp
... and an issue with post-write head placement for machines with fixed-speed drives (i.e. everything other than the Macintosh).
This fixes #625
=> Corrects time propagation for Apple II cards

Outputs/OpenGL/ScanTarget.cpp
Risk was: allocation exactly joins end of buffer. In which case the next get_data won't wrap the texture y coordinate since it won't spot an x overage.
Believed to correct the crashing part of #663
=> Resolves a potential out-of-bounds array access.

Machines/Atari/ST/Video.cpp
Specific issue: the repeated (start_column != end_column) test, which can no longer be correct if start_column has been incremented in the (x_&7) test.
The visible effect was to omit pixels from the output wave, which also affected observed sync timing.
=> Corrects accidental dropping of pixel residue.

Components/68901/MFP68901.cpp, Machines/Atari/ST/Video.cpp, OSBindings/Mac/Clock SignalTests/AtariSTVideoTests.mm
Or, arguably, two off-by-one errors. Also adjusts vertical sync placement in horizontal terms.
=> Corrects off-by-one error in the ST's vertical state machine

Components/68901/MFP68901.cpp, Components/68901/MFP68901.hpp
Empirically, this seems to be correct.
=> Implements MFP timer reload when in event counting mode.

.github/workflows/ccpp.yml
Thereby fixing the can't-find-file failure of the SDL/Ubuntu build test.
=> Adds an apt-get update.

Components/1770/1770.cpp, Storage/Disk/Controller/MFMDiskController.cpp, Storage/Disk/Encodings/MFM/Shifter.cpp
Specifically when rolling to the next sector after a successful read in a multi-sector read or write.
=> Ensure the WD won't confuse sector contents for header content.

ClockReceiver/JustInTime.hpp, Machines/Atari/ST/AtariST.cpp, Machines/Atari/ST/Video.cpp, Machines/Atari/ST/Video.hpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock SignalTests/AtariSTVideoTests.mm
Specifically:
- eliminates potential pixel buffer overrun;
- ensures the Shifter is fully asynchronous;
- introduces delays on external VSYNC and HSYNC signalling;
- ensures the video address is reloaded for the entirety of VSYNC;
- introduces unit tests as to various 'sync line lengths'; and
- adds VSYNC/HSYNC interrupt latches, so each definitely fires only once.
Wider discussion: various demos still work incorrectly, but games are increasingly working.
=> Further improves the ST graphics subsystem

Machines/Atari/ST/AtariST.cpp, Machines/Atari/ST/Video.cpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock SignalTests/68000Tests.mm, OSBindings/Mac/Clock SignalTests/AtariSTVideoTests.mm, OSBindings/Mac/Clock SignalTests/TestRunner68000.hpp, Outputs/CRT/Internals/Flywheel.hpp, Processors/68000/Implementation/68000Implementation.hpp, Storage/Disk/Encodings/MFM/Encoder.cpp
This produces this emulator's first fully-stable full-screen overscan.
Though most such things still do not work.
=> Corrects vsync placement and BPP-change pipeline flushing.

Processors/68000/Implementation/68000Implementation.hpp, Processors/68000/Implementation/68000Storage.hpp
Specifically:
* ensures pushed PC is correct return address; and
* adds a one-instruction delay to the trace command coming into effect.
=> Improves 68000 trace support

Analyser/Dynamic/MultiMachine/Implementation/MultiSpeaker.cpp, Concurrency/BestEffortUpdater.cpp, Concurrency/BestEffortUpdater.hpp, Machines/CRTMachine.hpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/Mac/Clock Signal/Updater/CSBestEffortUpdater.h, OSBindings/Mac/Clock Signal/Updater/CSBestEffortUpdater.mm, OSBindings/SDL/main.cpp, Outputs/Speaker/Implementation/LowpassSpeaker.hpp, Outputs/Speaker/Speaker.hpp
i.e. run a target machine until a particular event occurs. Used right now by the Mac for ensuring audio is prepared in a timely fashion, intended also to allow a potential future vsync mode.
This also rethinks the BestEffortUpdater logic in an attempt to improve likely CPU affinity.
=> Implements a nascent `run_until`

Analyser/Static/Commodore/Disk.cpp, Machines/AmstradCPC/AmstradCPC.cpp, Machines/Atari/ST/AtariST.cpp, Machines/Atari/ST/DMAController.cpp, Machines/Atari/ST/DMAController.hpp, Machines/Commodore/1540/Implementation/C1540.cpp, Machines/Commodore/1540/Implementation/C1540Base.hpp, Machines/Electron/Plus3.cpp, Machines/Electron/Plus3.hpp, Machines/MSX/DiskROM.cpp, Machines/MSX/DiskROM.hpp, Machines/Oric/BD500.cpp, Machines/Oric/DiskController.hpp, Machines/Oric/Jasmin.cpp, Machines/Oric/Microdisc.cpp, Machines/Oric/Video.hpp, Storage/Disk/Controller/DiskController.cpp, Storage/Disk/Controller/DiskController.hpp, Storage/Disk/Drive.cpp
This is primarily intended to allow intelligent clocking.
I've also endeavoured to give myself room to allow multiple-drive selection. It's a bit nonsensical, but some machines support it, and it'd be nice to provide nonsensical results if performed.
While I'm here, this also:
* resolves #747 by implementing multiple Byte Drive 500 drives; and
* fixes potential arbitrary memory accesses by the Oric at startup if you're unlucky.
=> Moves ownership of drives inside Disk::Controller.

OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/SDL/main.cpp
Also attempts to improve new-world SDL shutdown reliability.
=> Avoids trying to paper over huge gaps in running time.

OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal Kiosk.xcscheme, OSBindings/SDL/main.cpp
This is at least until I'm more confident in the keypress/text input merging. Also, switches to a vector for intermediate keypresses, to ensure order is retained even if timestamps are absent.
This is aimed at #767
=> Return to old SDL behaviour if --logical-keyboard isn't specified.

OSBindings/Mac/Clock Signal/Views/CSOpenGLView.m
This also centralises the workaround, the better for replacing it when I discover a safer alternative.
Attempts to deal with the crash mentioned in #770
=> Ensure race condition workaround is applied for all CVDisplayLinkStops.

OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock Signal/Views/CSOpenGLView.m
and no never-ending setupDisplayLink loop on exit.
Takes another stab at the crash part of #770
=> Ensures proper NSScreen comparison... 

.github/workflows/ccpp.yml, Analyser/Dynamic/MultiMachine/Implementation/MultiConfigurable.cpp, Processors/6502/6502.hpp, Processors/6502/Implementation/6502Base.cpp, Processors/6502/Implementation/6502Implementation.hpp, Processors/6502/Implementation/6502Storage.cpp, Processors/6502/Implementation/6502Storage.hpp, Reflection/Struct.cpp, Reflection/Struct.hpp, Storage/Disk/Drive.cpp
Also further enhances reflection as I go along:
* registered properties that are themselves reflectable structs are now registered as reflectable structs, introducing something of an object graph;
* steps have been taken towards const correctness; and
* a textual description can now be generated of any reflectable struct. Which I guess is technically a first draft at serialisation, albeit to an informal layout.
=> Provisionally adds `State` and `get/set_state` to the 6502.

Storage/Disk/DiskImage/Formats/WOZ.cpp, Storage/Disk/DiskImage/Formats/WOZ.hpp, Storage/Disk/Drive.cpp, Storage/Disk/Encodings/AppleGCR/SegmentParser.cpp
Also liberalises the Disk II static analyser and improves gain-related disk drive noise (as recommended by the WOZ 2 spec).
On the other side, WOZ writing is now disabled as it isn't supported properly by the track cache.
=> Support WOZ 2 disk images

ClockReceiver/VSyncPredictor.hpp, OSBindings/Qt/mainwindow.cpp, OSBindings/Qt/mainwindow.h, OSBindings/Qt/scantargetwidget.cpp
Resolves #820 
Therefore it:
- ensures that status LED updates are properly thread confined; and
- avoids improper UI display if an invalid filename is passed on the command line.
Bonus features:
- a better attempt is made at frame-length prediction; and
- slightly more feedback is provided in the ROM installation loop.
=> Qt issue mega ticket

Analyser/Dynamic/MultiMachine/Implementation/MultiSpeaker.cpp, Analyser/Dynamic/MultiMachine/MultiMachine.cpp, Outputs/Speaker/Speaker.hpp
Corrects the crashing part of #826 but leaves multimachines still oddly mute.
Will look at the second issue separately — it's always worth getting a fix for a crash onto master ASAP.
=> Ensures proper handover of speaker state when picking in a multimachine.

Outputs/CRT/CRT.cpp
Which has the effect of removing the errant bottom-left to top-right raster scan on some systems; the vertical counter no longer overflows during the final line of the display.
=> Allows for permitted 1/32nd timing error in `time_multiplier_`.

OSBindings/Mac/Clock SignalTests/65816kromTests.swift
It cuts down on creating a URL struct.
=> Use url(forResource:... instead of path(forResource:… 

OSBindings/Qt/mainwindow.cpp
Resolves the remaining portion of #852
=> Qt: don't copy the result of get_keyboard().

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/ScanTarget/CSScanTarget.mm
Also enables the M1 again for release builds.
=> Corrects Metal buffer sizing on Retina displays.

OSBindings/Mac/Clock Signal/Joystick Manager/CSJoystickManager.m
This is a hacked-together implementation of the GameController framework for Clock Signal.
Current limitation: only four buttons are set up, a, b, x, and y. Any more buttons will need to be manually added.
The d-pad is interpreted as a hat switch.
The left analog stick and the x axis of the the right are used for `CSJoystickAxisTypeX`, `CSJoystickAxisTypeY`, and `CSJoystickAxisTypeZ`.
Note that you will need Mac OS 11 (Big Sur) or later, as the GameController frameworks were somewhat lacking in useful utilities until recently.
=> Initial GameController joystick support.

Analyser/Static/Acorn/Disk.cpp, Analyser/Static/Acorn/File.hpp, Analyser/Static/Acorn/StaticAnalyser.cpp, Analyser/Static/Acorn/Tape.cpp, Analyser/Static/Acorn/Target.hpp, Analyser/Static/StaticAnalyser.cpp, Machines/Electron/Electron.cpp, ROMImages/Electron/readme.txt, Storage/Disk/DiskImage/Formats/AcornADF.cpp, Storage/Disk/DiskImage/Formats/AcornADF.hpp
Resolves the first part of #864
=> Electron: adds support for the ADL file format, and logic for AP6 and sideways RAM selection

OSBindings/Mac/Clock Signal/MachinePicker/MachinePicker.swift
A quick bugfix for the post-IIgs-option macOS version only.
=> Ensures machine selection carries over sessions.

Machines/Apple/Macintosh/Macintosh.cpp
Albeit that it should be harmless; it's just seeding RAM.
=> Makes absolutely sure not to try to use quickboot workaround for Mac 128kb/512kb.

OSBindings/Mac/Clock SignalTests/68000ComparativeTests.mm, OSBindings/Mac/Clock SignalTests/EmuTOSTests.mm
Use `-fileSystermRepresentation` instead of `-UTF8String` when dealing with file manipulation.
=> Minor pokes to the test files code.

ClockReceiver/JustInTime.hpp, Machines/Apple/AppleIIgs/AppleIIgs.cpp, Machines/Atari/ST/AtariST.cpp, Machines/ColecoVision/ColecoVision.cpp, Machines/Electron/Electron.cpp, Machines/Electron/Video.cpp, Machines/Electron/Video.hpp, Machines/Sinclair/ZXSpectrum/ZXSpectrum.cpp, Storage/Tape/Formats/TapeUEF.cpp
Also reorders template parameters; I think that specifying a different time base is likely to be more common than using a divider.
=> Moves the Electron to JustInTimeActor video.

Machines/Sinclair/ZXSpectrum/Video.hpp, Machines/Sinclair/ZXSpectrum/ZXSpectrum.cpp
Primary target was proper intersection with the floating bus; using the 48/128 timings as a portal into otherwise-undocumented Z80 behaviour* will have to wait.
\* specifically:
* what's on the address bus during non-access cycles; and
* how MREQ is signalled during long accessing machine cycles (such as those in LDIR).
=> Further tweaks Spectrum timing.

Machines/Sinclair/ZXSpectrum/Video.hpp
Thereby causing the pixel region to be centred.
=> Moves horizontal sync on the 48kb.

Storage/Tape/Formats/OricTAP.cpp
This is in reaction to there being at least one tape in the wild with more than three synchronisation bytes recorded.
=> Relaxes Oric .tap signature check.

OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal Kiosk.xcscheme, OSBindings/SDL/main.cpp
Specifically to include all paths tried, and not use the plural for 'crc32' when only one is present.
Possibly to help with #943
=> Improve SDL failed-ROM reporting.

Machines/Enterprise/Enterprise.cpp
The result of this was that opcode reads from non-video memory would have video access timing applied if wait modes were set to none.
i.e. complete nonsense.
SIDBasic now correctly recognises a 4Mhz CPU. So that's progress.
=> Correct Enterprise timing error.

Machines/Enterprise/Enterprise.cpp
As per the branch name, this corrects all timing issues with Chase HQ.
=> Flip meaning of INT1 input read.

Activity/Observer.hpp, Analyser/Static/Enterprise/StaticAnalyser.cpp, Machines/AmstradCPC/AmstradCPC.cpp, Machines/AmstradCPC/Keyboard.hpp, Machines/Electron/Electron.cpp, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/Qt/mainwindow.cpp, OSBindings/Qt/mainwindow.h, OSBindings/SDL/main.cpp
i.e. they indicate a persistent state rather than transient activity.
This is used by the macOS UI as a display hint.
=> Classify some LEDs as 'persistent'

OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Views/CSScanTargetView.h, OSBindings/Mac/Clock Signal/Views/CSScanTargetView.m
This allows the Macintosh and ST to fade out volume and settings even without having captured the mouse.
=> Slightly adjusts macOS mouse hiding semantics.

Machines/Amiga/Copper.cpp, Machines/Amiga/Disk.cpp
Previously I had been led empirically to believe that WAITs which don't wait terminate in just 8 cycles, but I no longer believe that to be true.
Primary improvement: PAL titles which use the standard $FFDF, $FFFE and then immediately another WAIT no longer trigger upon the end of line 255. Which has resolved an issue with the bottom of the display being cropped in a decent amount of software.
=> Switches all Copper WAITs to 12 cycles

OSBindings/SDL/main.cpp, Storage/MassStorage/Encodings/MacintoshVolume.hpp
This is a portability concern; I think I've been just a touch too lazy here.
=> Eliminate usages of unistd.h.

InstructionSets/M68k/Decoder.cpp, InstructionSets/x86/Decoder.cpp
In particular around what was clearly a bug in the x86 decoder. GCC saves the day!
=> Resolve GCC compilation warnings.

InstructionSets/M68k/Instruction.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock SignalTests/68000OldVsNew.mm, OSBindings/Mac/Clock SignalTests/68000Tests.mm, Processors/68000/68000.hpp, Processors/68000/Implementation/68000Implementation.hpp, Processors/68000Mk2/68000Mk2.hpp, Processors/68000Mk2/Implementation/68000Mk2Implementation.hpp
Expected steps:
1. use this to uncover all meaningful differences between my old and new implementations;
2. find out which implementation is correct, where known, and fix the new implementation if necessary;
3. solidify all intermediate results into JSON so that they can outlive the old implementation.
Corrections to the new 68000 are already included and will likely continue to turn up.
=> Introduce randomised old vs new 68000 tests.

Processors/6502/Implementation/6502Implementation.hpp
This resolves a regression that broke the Vic-20 and Acorn Electron (i.e. both 6502 devices that utilise interrupts).
=> Correct 6502 for switched BRK presumption.

OSBindings/Mac/Clock Signal/Audio/CSAudioQueue.h, OSBindings/Mac/Clock Signal/Audio/CSAudioQueue.m, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm
The more interesting part of this is that it reduces potential runtime failure points; although it reduces the scope of the critical section, it had no empirical effect on performance.
=> macOS: perform audio buffer allocations ahead of time.

Machines/Amiga/Blitter.cpp, Machines/Amiga/Blitter.hpp, Machines/Amiga/BlitterSequencer.hpp, Machines/Amiga/Chipset.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock SignalTests/AmigaBlitterTests.mm
As of this pull request it's still deliberately skipping blits that are of the same size as those carried out during MFM decoding. This is temporarily to avoid an issue with loading (Spindizzy Worlds being a triggering example) which I have yet further to investigate but is likely due to some sort of broken interlock and may be a latent issue in disk decoding. I don't know. Research to do.
=> Partially enable serialised blitter.

Outputs/OpenGL/ScanTargetGLSLFragments.cpp, Outputs/ScanTarget.hpp
Some GPUs (e.g. r600) require the stride of vertex attributes to be a multiple of four bytes, add two bytes of padding to the Scan struct to meet this alignment requirement and reduce driver CPU overhead.
=> Align Scan to be a multiple of four bytes

InstructionSets/M68k/Instruction.cpp, InstructionSets/M68k/Instruction.hpp, OSBindings/Mac/Clock SignalTests/68000OldVsNew.mm, Processors/68000Mk2/68000Mk2.hpp, Processors/68000Mk2/Implementation/68000Mk2Implementation.hpp
This is a further step towards eliminating the classic 68000 implementation from the codebase, though it also eliminates an error in the new 68000's bus signalling of new versus same address.
=> Add 68000 regression test generator.

Processors/65816/Implementation/65816Implementation.hpp, Processors/65816/Implementation/65816Storage.hpp
Locking the generated address to the page indicated by `DH` previously occurred whenever `E=1`. It should occur only when `E=1` **and** `DL=0`.
See http://www.6502.org/tutorials/65c816opcodes.html#5.8 and https://github.com/TomHarte/ProcessorTests/issues/16
=> Fix 65816 direct, [x/y] addressing when E=1, DL != 0.

Machines/Apple/AppleIIgs/AppleIIgs.cpp, Machines/Apple/AppleIIgs/MemoryMap.hpp, OSBindings/Mac/Clock SignalTests/IIgsMemoryMapTests.mm
This removes the manual `for` loops, which is nice, but it also gives much better hooks to hang debugging on in the form of those various `const bool`s.
=> Apple IIgs: better spell out shadowing logic.

InstructionSets/M68k/Implementation/PerformImplementation.hpp, InstructionSets/M68k/Status.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock SignalTests/68000ComparativeTests.mm
Also adjusts shifts and rolls:
* adding safeguards against undefined behaviour (which was in practice affecting carry and extend, amongst others); and
* correcting logic for the overflow flag.
=> Tidy up 68000, primarily switching from macros to templates.

Components/9918/Implementation/9918Base.hpp, Components/9918/Implementation/PersonalityTraits.hpp
Clearly I'll have to do something else to support 128k+, probably move the ram pointer?
=> TMS9918 &c: Eliminate hard-coded assumption of 16kb.

Components/9918/Implementation/9918.cpp, Components/9918/Implementation/ClockConverter.hpp, Components/9918/Implementation/Fetch.hpp, Components/9918/Implementation/Storage.hpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme
Promised as a separate pull request; I'm actually doing this relative to the MSX 2 branch.
Sadly this change is necessary to support the V99x8 horizontal offset. Or, at least, it's the neatest way to get there.
=> Definitively switch 9918 to counting cycle 0 as start-of-sync.

Components/9918/Implementation/9918.cpp, Components/9918/Implementation/ClockConverter.hpp, Components/9918/Implementation/Fetch.hpp, Components/9918/Implementation/LineLayout.hpp, Components/9918/Implementation/Storage.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj
Also glue in a potential change of origin between the way that fetch positions are expressed (i.e. relative to start of horizontal sync) and the internal counting. So it's no effort from here on to chop and change, hopefully.
This is preparatory to another potential shift of internal zero, per the observation that the Yamaha latches mode partway through left blank, and therefore probably so do the TMS and Master System (albeit that there's really no call ever to mix modes on the Master System, and it's not really done on the TMS).
=> Clean up further internal magic constants.

Activity/Observer.hpp, Analyser/Static/Commodore/File.hpp, Machines/Utility/ROMCatalogue.hpp, Machines/Utility/StringSerialiser.hpp, Reflection/Struct.hpp, Storage/Data/Commodore.hpp
Sprinkle includes of the `<cstdint>` header as needed to make the build succeed with GCC 13, this fixes both with SDL and Qt builds.
=> Add missing <cstdint> includes for GCC 13

Processors/65816/Implementation/65816Base.cpp, Processors/65816/Implementation/65816Implementation.hpp, Processors/65816/Implementation/65816Storage.cpp, Processors/65816/Implementation/65816Storage.hpp
While admitting that the stack pointer is 16-bit even in emulation mode.
=> Use full 16-bit stack pointer for all 'new' instructions.

Machines/Apple/ADB/Mouse.cpp, Machines/Apple/AppleIIgs/ADB.cpp, Machines/Apple/AppleIIgs/AppleIIgs.cpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme
Along with sanity-based quality-of-life improvements, primarily clamping mouse speed.
For some reason cursor position update seems to be languid, the cause for which I currently suspect to be interrupt or JIT-actor related. More investigation to come.
=> Without rhythm or rhyme, fix IIgs GSOS mouse movement.

OSBindings/Mac/Clock SignalTests/65816ComparativeTests.mm, Processors/6502/Implementation/6502Storage.cpp
TODO: should this affect the 65C02 safety NOPs? My expectation is that it should, but I've conservatively omitted them for now.
=> 6502: add final read cycle to illegal NOPs.

Numeric/Carry.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock SignalTests/BCDTest.swift, Processors/6502/6502.hpp, Processors/6502/Implementation/6502Implementation.hpp
While also fixing invalid-BCD `SBC`s on the 65C02.
=> Extend BCD testing to the 65C02; clean up implementation

InstructionSets/x86/Decoder.cpp, InstructionSets/x86/Implementation/PerformImplementation.hpp, InstructionSets/x86/Instruction.cpp, InstructionSets/x86/Instruction.hpp, OSBindings/Mac/Clock SignalTests/8088Tests.mm, OSBindings/Mac/Clock SignalTests/x86DecoderTests.mm
Specifically:
* give up trying to store length; it hasn't turned out to be as useful as originally imagined;
* pack REP/REPE/REPNE into the operation field;
* fully boil down segment into the instruction;
* pack lock and the segment override into the space freed up by no longer storing length; and
* thereby, eliminate the length extension.
Bonus: puts `operation` behind a getter, in case I want to expand it to nine or more bits in the future.
In net: normalised instructions are now always 32-bits + operand and/or displacement.
=> Compact normalised x86 instructions.

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj
This fixes failure of Clock Signal to launch on macOS High Sierra as reported in #1191.
-----
Users wishing to use the binary of release 23.09.10 without recompiling it can copy it to the Desktop and then run these commands in the Terminal:
```
install_name_tool -delete_rpath /System/Library/PrivateFrameworks/Swift/libswiftCore.dylib -add_rpath @loader_path/../Frameworks "$HOME/Desktop/Clock Signal.app/Contents/MacOS/Clock Signal"
codesign -fs - "$HOME/Desktop/Clock Signal.app/Contents/MacOS/Clock Signal"
```
The `install_name_tool` command replaces the invalid runtime path with the correct one. This is of course a modification of the program, and any modification to a program breaks its code signature and makes the OS refuse to run it. The `codesign` command creates a new ad-hoc code …
=> Fix LD_RUNPATH_SEARCH_PATHS for High Sierra

InstructionSets/x86/Decoder.cpp, InstructionSets/x86/Implementation/PerformImplementation.hpp, InstructionSets/x86/Instruction.hpp, InstructionSets/x86/Perform.hpp, OSBindings/Mac/Clock SignalTests/8088Tests.mm
The memory controller for a given machine now receives a type with each call to `access` which may be:
* read, which effectively means to throw if the described address isn't readable;
* write, which effectively means to throw if the described address isn't writeable;
* read-modify-write, which effectively means to throw if the described address isn't readable or writeable; and
* preauthorised read or write, which means not to validate because the access was validated earlier.
RAM accesses can be preauthorised based on segment, absolute or stack-relative position. All accesses are validated before `perform` modifies state.
I've also cleaned up the arguments provided to and beyond `perform` by bundling them into a single context object, and minimised what the flow controller does.
Kicked …
=> Work towards x86 access violations.

InstructionSets/x86/Decoder.cpp, InstructionSets/x86/Implementation/Arithmetic.hpp, InstructionSets/x86/Implementation/PerformImplementation.hpp, InstructionSets/x86/Instruction.cpp, InstructionSets/x86/Instruction.hpp, OSBindings/Mac/Clock SignalTests/8088Tests.mm
Failures accepted, related to undocumented or undefined behaviour of the 8086:
* my `AAM 00h` doesn't modify status before throwing a divide error but the 8086's does;
* my `LEA reg` loads the value of the register whereas the 8086's loads whatever address was last calculated; and
* the test set's `rep idiv` sometimes doesn't advance the instruction pointer.
Additionally:
* my `IDIV byte` doesn't throw as often as the 8086's, it seems. I can't find an example where it should have thrown per the spec and have observed other 16-bit x86 emulations doing the same as mine. So I provisionally think this is an 8086 quirk.
In net though: since I'm now testing for and permitting only these failures, if any other failures are introduced then they should show up more clearly and hence be easier to …
=> Improve IDIV marginally; require acceptable failures to have a reason.

InstructionSets/x86/Implementation/BCD.hpp, InstructionSets/x86/Implementation/PerformImplementation.hpp, InstructionSets/x86/Instruction.hpp, OSBindings/Mac/Clock SignalTests/8088Tests.mm
While also fixing AAA/AAS's effect on the carry flag.
Segment register changes are observed by the test runner for no reason more sophisticated than eliminating a small shift, primarily for the sake of testing that the changes are caught at all. But they're essential to supporting protected modes, where changes actually trigger a selector reload.
=> Add means for tracking segment register changes.

OSBindings/Mac/Clock Signal/AppDelegate.swift, OSBindings/Mac/Clock Signal/Base.lproj/MainMenu.xib
A few minor changes to the Mac UI wording:
* Add a period at the end of the sentence "This application requires a Metal-capable GPU"
* Change the "Exit" button that closes that dialog to "Quit" to conform to standard macOS terminology
* Add ellipsis at end of "New" menu item since that menu item causes a dialog box to appear
=> Minor Mac UI wording changes

Machines/Apple/AppleII/Video.hpp
=> Fix Apple II/II+/IIe floating bus first eight non-hbl vbl bytes

InstructionSets/x86/Implementation/FlowControl.hpp, InstructionSets/x86/Implementation/PerformImplementation.hpp, InstructionSets/x86/Implementation/Stack.hpp, InstructionSets/x86/Instruction.hpp, InstructionSets/x86/Interrupts.hpp, OSBindings/Mac/Clock SignalTests/8088Tests.mm
Primarily:
1. fully document 80286 `Operation` semantics;
2. implement the 80186 instructions; and
3. create a separate object for handling segment mappings, rather than overloading the meaning of the register store.
The segment handler will receive descriptor pointers, handle VERR/VERW, etc.
=> Clear a path towards implementing the 80286

Machines/PCCompatible/PCCompatible.cpp, Machines/PCCompatible/PIC.hpp
Also marginally beefs up the MDA to respect attributes other than blink (it also still ignores the hardware cursor), and switches it to green output — albeit it very fictionally in terms of internal wiring.
There are now no key-related failures reported during boot.
Doesn't actually wire up keyboard input. I'll fill that in if and when there's something that can receive it. There's too much guesswork here for me at present; satisfying the one BIOS I happen to be testing doesn't actually establish all that much.
=> Attempt to implement the XT keyboard controller.

Storage/Disk/DiskImage/Formats/WOZ.cpp
I think this may have been what you meant to write?
=> Fix typo in comment in WOZ.cpp

Components/DiskII/DiskII.cpp
This shouldn't matter since these operations are not requested by the state machine but this is what those operations should do according to Understanding the Apple II, Table 9.3, page 9-15.
=> Handle C, E, F operations in Disk II state machine

Components/8272/CommandDecoder.hpp, Components/8272/Results.hpp, Components/8272/Status.hpp, Components/8272/i8272.cpp, Components/8272/i8272.hpp, Machines/PCCompatible/KeyboardMapper.hpp, Machines/PCCompatible/PCCompatible.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme
This:
* factors out command and status logic from the existing low-level implementation; and
* implements high-level versions of the decode, execute and result phases along with the few instructions necessary to get past POST and into attempting to read the boot sector.
Additionally bundled:
* some expansion of the keyboard controller, to allow a little further machine interaction; and
* disk activity indicators.
The next step involves being able to accept and recognise disk images and direct them to the proper machine, which feels disjoint enough to be a separate work item.
=> Sketch the outline of a high-level emulation of the PC FDC

Machines/Enterprise/Nick.cpp, Machines/Enterprise/Nick.hpp
This could be triggered when rendering the very first line of output if happening to start mid-line.
=> Avoid illegal reads in Enterprise Nick

Components/DiskII/DiskII.cpp
Ensure we're actually in the sense-write-protect loop before deciding that we don't need to process anymore.
Closes #1218
=> Fix Disk II sense-write-protect clocking preference

.github/workflows/build.yml, .github/workflows/ccpp.yml
Here are some proposed improvements to the continuous integration, primarily adding a job to build the Mac UI. My intention is that the existing job to build the SDL UI could be expanded later to also run on macOS (and Windows, if it builds there) and a third job can be added later to build the Qt UI on whichever operating systems it supports.
=> CI improvements

Machines/PCCompatible/PIC.hpp
This thrillingly causes DOS Plus fully to boot, though it then seems to use only a quarter of the display for most output, and not entirely correctly. So more to pursue there.
=> Support 8259 PIC specific EOIs.

.github/workflows/build.yml, Machines/Apple/AppleII/Video.hpp, OSBindings/SDL/SConstruct, OSBindings/SDL/main.cpp
Here are several improvements to the scons/SDL/OpenGL build, especially for macOS.
Fixes
```
/bin/sh: sdl2-config: command not found
```
when sdl2-config is not in a standard system bin directory (e.g. MacPorts).
Fixes
```
main.cpp:22:10: fatal error: 'SDL2/SDL.h' file not found
```
when SDL2 is not in a standard system include directory (e.g. MacPorts).
Fixes
```
Undefined symbols for architecture x86_64:
"_vDSP_dotpr_s1_15", referenced from:
Outputs::Speaker::LowpassBase<Outputs::Speaker::PushLowpass<true>, true>::resample_input_buffer(int) in Audio.o
Outputs::Speaker::LowpassBase<Outputs::Speaker::PullLowpass<GI::AY38910::AY38910<true> >, true>::resample_input_buffer(int) in AmstradCPC.o
Outputs::Speaker::LowpassBase<Outputs::Speaker::PullLowpass<Audio::Toggle>, …
```
=> SDL build improvements

Outputs/OpenGL/OpenGL.hpp
Building the scons/SDL version of Clock Signal on macOS with llvm.org clang 17.0.6 fails:
```
Outputs/OpenGL/OpenGL.hpp:17:6: error: 'TARGET_OS_IPHONE' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
17 |         #if TARGET_OS_IPHONE
|             ^
```
This PR fixes it by including the header that defines `TARGET_OS_IPHONE`.
=> Include TargetConditionals.h where needed

Machines/Amiga/Amiga.cpp, Machines/Amiga/Chipset.cpp, Machines/Amiga/Chipset.hpp, Machines/Amiga/Disk.cpp, Machines/Amiga/MemoryMap.hpp, Machines/Apple/Macintosh/Macintosh.cpp, Machines/Atari/ST/AtariST.cpp, OSBindings/Mac/Clock SignalTests/68000ComparativeTests.mm, OSBindings/Mac/Clock SignalTests/EmuTOSTests.mm, OSBindings/Mac/Clock SignalTests/QLTests.mm, OSBindings/Mac/Clock SignalTests/TestRunner68000.hpp, Processors/68000/68000.hpp, Processors/68000/Implementation/68000Implementation.hpp, Processors/68000/Implementation/68000Storage.hpp
A better take on what I'd attempted with the operation template:
* the supplied Microcycle always has an `operation`, it's just sometimes `static constexpr` rather than dynamic;
* that means that the resulting `perform_bus_operation`s can be written in a more straightforward manner, and also that any compile-time fixed `operation`s can also be optimised into the various getters and setters provided by `Microcycle` — `data_select_active()`, `lower_data_select()`, etc.
---
As with the previous efforts here, the intent is to install a means for the `operation` to be fixed at compile-time if it can be. Not yet exhaustively to do so.
=> Move fact of fixed operations into type.

Concurrency/AsyncTaskQueue.hpp
=> Remove pointless — and damaging — `std::move`.

Machines/PCCompatible/RTC.hpp
This now correctly indicates hour; I may be way off here, but it seems that GlaTick expects a 24-hour clock value even before it has set register B.
=> Default to 24-hour mode.

Storage/Disk/Encodings/MFM/Parser.cpp
This fixes static analysis for a range of platforms.
=> Avoid erroneous early Parser exit.

Machines/Apple/AppleII/VideoSwitches.hpp
=> Fix Apple II inverse text errors.

Components/DiskII/DiskII.cpp, Storage/Disk/DiskImage/Formats/NIB.cpp
I'm pretty sure that four is the actual minimum number of sync bytes; in the worst case the controller will be repeatedly catching bit 0 so:
* after one sync byte it'll have climbed to bit 2;
* then 4;
* then 6;
* then on the fourth it'll attempt to start reading at bit 8, and slip down to 7.
=> Mildly clean up around NIBs.

Machines/Apple/AppleIIgs/AppleIIgs.cpp, Machines/Apple/AppleIIgs/MemoryMap.hpp, OSBindings/Mac/Clock SignalTests/IIgsMemoryMapTests.mm
Indecision had led to a mild contradiction here:
* shadowing was enabled by logical address;
* ... but applied by physical address.
Some titles seem to: (i) enable auxiliary memory; (ii) enable super-high-resolution shadowing; and (iii) write all graphics via bank 0. I am therefore doubling down on physical addresses being the things that are shadowed — i.e. the process is:
1. map from logical to physical address;
2. shadow from physical address to second physical address if enabled.
This seems to resolve the issue where many pieces of super-high-resolution software were missing the bottom half of their display.
E.g.
=> Be consistent in shadowing IIgs *physical* addresses.

Components/6845/CRTC6845.hpp, OSBindings/Mac/Clock SignalTests/IIgsMemoryMapTests.mm
The EGA and VGA change the meaning of some registers, therefore register number isn't a good way to identify programmer-set values while executing.
=> Use named fields during CRTC execution.

OSBindings/Mac/Clock Signal/Views/CSScanTargetView.m
Closes #1178
I don't know why this fixes it but it does.
Thanks to @RRyanClark for suggesting I look in the area of code that calls `MTLCreateSystemDefaultDevice`.
=> Fix color video performance on macOS 10.15+

Components/9918/Implementation/9918.cpp
Old code was:
if(this is first row) { if(this is latch time) { latch vertical; } latch horizontal; }
This is corrected to:
if(this is latch time) { if(this is first row) { latch vertical; } latch horizontal; }
So:
* horizontal scrolling is now latched _every line_; and
* vertical scrolling is now latched _once per frame_.
Which I think is correct.
=> Ensure Master System horizontal scroll is latched every line.

Analyser/Static/StaticAnalyser.cpp, Storage/Disk/DiskImage/Formats/2MG.hpp
Fixes `error: use of undeclared identifier 'nullptr_t'; did you mean 'nullptr'?` when compiling with Xcode 12.4.
=> Include <cstddef> and use std::nullptr_t not nullptr_t

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Qt/audiobuffer.h, OSBindings/Qt/functionthread.h, OSBindings/Qt/keyboard.h, OSBindings/Qt/mainwindow.h, OSBindings/Qt/scantargetwidget.h, OSBindings/Qt/settings.h, OSBindings/Qt/timer.h, Reflection/TypeInfo.hpp
Also adds TypeInfo.hpp to the Xcode project, which had previously omitted it.
=> Switch trailing files to #pragma once.

Processors/AllRAMProcessor.cpp
In the new CMake build system I'm putting together for Clock Signal, I pretty much included all the source files. This built fine on macOS 12 using Apple clang 14.0.0 but on Linux Mint 21.2 with g++ 11.4.0 it failed:
```
/home/rschmidt/repos/CLK/Processors/AllRAMProcessor.cpp: In member function ‘void CPU::AllRAMProcessor::set_data_at_address(size_t, std::size_t, const uint8_t*)’:
/home/rschmidt/repos/CLK/Processors/AllRAMProcessor.cpp:20:9: error: ‘memcpy’ was not declared in this scope
20 |         memcpy(&memory_[start_address], data, end_address - start_address);
|         ^~~~~~
/home/rschmidt/repos/CLK/Processors/AllRAMProcessor.cpp:10:1: note: ‘memcpy’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
9 | #include "AllRAMProcessor.hpp"
+++ |+#include …
```
=> Add missing include of cstring for memcpy.

InstructionSets/README.md, OSBindings/Mac/Clock SignalTests/68000 Comparative Tests/readme.md, OSBindings/Mac/Clock SignalTests/AllSuiteA/readme.md, OSBindings/Mac/Clock SignalTests/Amiga Blitter Tests/README.md, OSBindings/Mac/Clock SignalTests/BCDTest/readme.md, OSBindings/Mac/Clock SignalTests/Wolfgang Lorenz 6502 test suite/readme.md, Packaging/README.md, README.md
Improve compatibility with some Markdown readers like [MacDown](https://macdown.uranusjr.com) by adding blank lines before lists. Blank lines around headers were added for consistency. One header level was fixed. One code block was fixed.
=> Compatibility fixes in Markdown files.

.github/workflows/build.yml
GitHub Actions now offers macOS 14 runners:
https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/
macos-latest will remain on macOS 12 until it switches to macOS 14 in the second quarter of 2024. So that you don't have to wait that long to get automated checks running on something newer than macOS 12, this PR switches from macos-latest to explicitly listing macos-11, macos-12, macos-13, and macos-14.
macos-11 is deprecated and will be removed by June 2024 but could be helpful until then.
macos-14 is arm64; macos-13 and earlier are x86_64.
=> Update CI to build on macOS 11, 12, 13, and 14.

Components/AY38910/AY38910.cpp, Components/AY38910/AY38910.hpp, Components/AudioToggle/AudioToggle.hpp, Components/OPx/OPLL.hpp, Machines/Apple/AppleIIgs/Sound.hpp, Outputs/Speaker/Implementation/BufferSource.hpp
Also overtly to do with getting to the Mockingboard shortly:
* break the AY down from a BufferSource into a SampleSource;
* thereby allow for easy irregular clocking;
* while simultaneously being able to flush out issues with the entirely-untested new SampleSource pathway.
For now there's possibly a processing cost* but I can likely alleviate that later; since this audio processing is always done on its own thread it shouldn't affect user perception — the main emulation thread will still be substantially slower than the audio thread.
\* the explicit instantiation of AY38910 _hopefully_ provides the compiler with enough visibility of AY38910SampleSource to appropriately inline advance() and level() but this hasn't been verified.
=> Convert AY to a SampleSource.

Machines/Apple/AppleII/AppleII.cpp, Machines/Apple/AppleII/Card.hpp, Machines/Apple/AppleII/DiskIICard.cpp, Machines/Apple/AppleII/Mockingboard.hpp, Machines/Apple/AppleII/SCSICard.cpp
So `IO` and `Device` signals are no longer labelled the wrong way around.
=> Fix IOSEL and DEVSEL assignments.

README.md
I was going to ask how difficult it would be to add support for the Macintosh 128K and 512K but it seems you already support them! This PR mentions this in the README. (Unless these emulations are unfinished and you don't want to mention them yet…)
=> Mention Macintosh 128K and 512K in README.

Components/AY38910/AY38910.cpp
Précis/reminder-to-self:
* the AY does its envelopes with 16 levels of volume precision;
* the YM doubles that to 32 levels;
* my implementation use a half-a-real-AY internal clock divider so that it can generate the YM-style envelopes if asked;
* it doubles the programmer-supplied tone and noise periods to make up the difference.
... but, here's the bug: it wasn't doubling the envelope period.
Fixed.
Affects #1339 and possibly resolves it. More testing to do.
=> Correct envelope period for internal double-resolution.

Machines/Apple/AppleII/VideoSwitches.hpp
Clearly I'd failed to account for the count being from 0 to 2*flash_length.
Resolves #1344
=> Double Apple II flash rate.

InstructionSets/ARM/Executor.hpp, InstructionSets/ARM/OperationMapper.hpp, InstructionSets/ARM/Registers.hpp, Machines/Utility/ROMCatalogue.cpp, Machines/Utility/ROMCatalogue.hpp, OSBindings/Mac/Clock SignalTests/ARMDecoderTests.mm, ROMImages/Archimedes/readme.txt
Also forces an instruction set version to be specified more widely, and clarifies/simplifies PC handling via the interpreter-style executor.
Bugs immediately uncovered and fixed:
* returning the wrong operation for data operations;
* making the wrong choice as to whether offsets are immediate for single data transfers.
=> Add RISC OS catalogue entry; do some basic ARM debugging.

InstructionSets/ARM/Executor.hpp, InstructionSets/ARM/OperationMapper.hpp, InstructionSets/ARM/Registers.hpp, OSBindings/Mac/Clock SignalTests/ARMDecoderTests.mm
Also tie down some of the undefined parts of the still-vague ARM execution test.
Off the record: a lot of the output of that test now looks like appropriate IOC/VIDC activity.
=> Express offset test as positive logic.

Analyser/Machines.hpp, Analyser/Static/Acorn/Disk.cpp, Analyser/Static/Acorn/StaticAnalyser.cpp, Machines/Utility/MachineForTarget.cpp, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm
Noting that https://mdfs.net/Docs/Comp/Disk/Format/ADFS severely conflates disk images and on-disk formats, making it hard to be especially confident. But this serves its current purpose; if there were an Archimedes machine then it would start upon an Archimedes disk being inserted — whether that disk would then appear properly formatted or not.
=> Add a through path for Archimedes disk images.

Machines/Acorn/Archimedes/FloppyDisc.hpp, Storage/Disk/Drive.cpp
1. reduces the Archimedes to a single disk drive, to avoid paying any update costs on the invisible three; and
2. removes a single conditional in drive emulation which showed up as expensive in profiling.
=> Slightly reduce processing heft of floppy accesses.

.github/workflows/build.yml
As per GitHub's announcement that "The macOS 11 runner image will be removed by 6/28/24"
=> Eliminate macos11 runner.

Machines/Acorn/Archimedes/Archimedes.cpp
This also implies I could probably remove both `wait` and `set_phase` actions, but I'll defer for now.
=> Don't move cursor near disk to folder if not about to load something.

Analyser/Dynamic/MultiMachine/Implementation/MultiSpeaker.cpp, Machines/Amiga/Audio.cpp, Machines/Apple/ADB/Mouse.cpp, Machines/Apple/AppleIIgs/Sound.cpp, Machines/Apple/Macintosh/Audio.cpp, OSBindings/SDL/main.cpp, Outputs/ScanTargets/BufferingScanTarget.cpp, Outputs/Speaker/Implementation/LowpassSpeaker.hpp, Outputs/Speaker/Speaker.hpp, Processors/65816/Implementation/65816Storage.cpp, Reflection/Enum.hpp, Reflection/Struct.hpp, Storage/Disk/DiskImage/DiskImageImplementation.hpp, Storage/Disk/Encodings/AppleGCR/SegmentParser.cpp, Storage/Disk/Encodings/MFM/SegmentParser.cpp
... as this form is compatible with both C++17 and C++20 onwards.
=> Avoid `std::memory_order::memory_order_X` in favour of `std::memory_order_X`.

Components/6560/6560.hpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal Kiosk.xcscheme, Outputs/ScanTargets/BufferingScanTarget.cpp
The actual bug here was:
* because the CRT doesn't display data received during periods of retrace, it would refuse to allocate space for any;
* but, machines might still be trying to begin provision of data in that period, even if it's not actually populated or output until later;
* ... in particular, the internal convention for outputting a single level — e.g. a border — means providing the value once and then allowing the GPU to paint it n times, so this could cause left borders in particular not to be painted, or to be painted with the wrong colour.
The particular surfacing that led me to this discovery was #1383
Resolves #1383
=> CRT: accept data during retrace.

Processors/6502/Implementation/6502Implementation.hpp, Processors/6502/Implementation/6502Storage.cpp, Processors/6502/Implementation/6502Storage.hpp
These should now last 5 cycles if the branch is untaken, 6 if it is taken within a page, 7 if it is taken crossing a page — and omit the erroneous mid-instruction write.
=> Correct 65c02 BBS/BBR bus activity.

Machines/Acorn/Electron/Electron.cpp, Machines/Acorn/Electron/Video.cpp, Machines/Acorn/Electron/Video.hpp, Outputs/CRT/CRT.cpp
This pull request attempts to transcribe the video generation portion of @hoglet67 's https://github.com/hoglet67/ElectronFpga (as filtered through @moogway82 's https://github.com/moogway82/JamSoftElectronULA which removes from that support for VGA, etc, making it easier to parse to my non-VHDL-aware mind) into C++, in order to benefit from all current knowledge about video generation within the Electron FPGA.
It's a very basic translation at present, with little in the way of software-style optimisation.
=> Replace Electron graphics generation with FPGA transcription.

Components/6845/CRTC6845.hpp, Machines/AmstradCPC/AmstradCPC.cpp, Machines/PCCompatible/CGA.hpp, Machines/PCCompatible/MDA.hpp, Machines/Utility/Typer.cpp
Similar to the recent Electron ULA changes, but casting a wider net on implementations, this attempts to reframe my CRTC implementation in hardware-style logic.
It still doesn't satisfy #1019; believed owing to the way the 6845 is integrated into the CPC emulation. More work to do here. But it's definitely an accuracy improvement in other areas.
=> Redraft CRTC closer to raw logic.

InstructionSets/M50740/Executor.cpp
Apropos of very little, since Apple IIgs emulation is still faulty.
=> Eliminate majority of M50740 macros

Machines/Apple/Macintosh/Macintosh.cpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/MSX/MSX.cpp, Machines/Oric/Oric.cpp, OSBindings/SDL/main.cpp
Primarily exposing the identities of objects prior to their initialisation, but also to tighten the type used for a `popen`/`FILE *` `unique_ptr`.
=> Resolve GCC/Ubuntu CI warnings.

OSBindings/Mac/Clock SignalTests/CPCShakerTests.mm
Even though it was safe, being used as part of a half-open range, it still trips up the sanitiser.
=> Avoid taking an out-of-range pointer.

Analyser/Static/Commodore/StaticAnalyser.cpp, Machines/Atari/ST/Video.cpp, Machines/Commodore/1540/C1540.hpp, Machines/Commodore/1540/Implementation/C1540.cpp, Machines/Commodore/1540/Implementation/C1540Base.hpp, Machines/Commodore/Plus4/Audio.hpp, Machines/Commodore/Plus4/Interrupts.hpp, Machines/Commodore/Plus4/Keyboard.cpp, Machines/Commodore/Plus4/Keyboard.hpp, Machines/Commodore/Plus4/Plus4.cpp, Machines/Commodore/Plus4/Video.hpp, Machines/Commodore/SerialBus.cpp, Machines/Commodore/SerialBus.hpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Enterprise/Enterprise.cpp, Machines/PCCompatible/PCCompatible.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal Kiosk.xcscheme, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock SignalTests.xcscheme, OSBindings/Mac/Clock Signal/MachinePicker/Base.lproj/MachinePicker.xib, Outputs/CRT/CRT.cpp, Storage/Tape/Tape.cpp, Storage/Tape/Tape.hpp, cmake/CLK_SOURCES.cmake
Outstanding issues to be solved in the future:
* audio is missing noise generation and is probably wrong in its counting;
* there's no character mapper and, correspondingly, no pasting or automatic media starting;
* tape loading doesn't work (possibly an issue with the timers?);
* there's no GUI route to starting a machine with no media;
* not all TED registers are yet implemented — primarily around video counters; and
* the static analyser still routinely makes bad choices, especially with disk images.
Nevertheless I'm optimistic that this is reasonable as far as it goes, implementing a TED machine with decent timing and proper modelling of internal state, and I'm able to load from floppy disk.
=> Add a simulacrum of C16+4 emulation.

OSBindings/Mac/Clock Signal/Audio/CSAudioQueue.m
This primarily avoids errant assertion failures in debug builds; it doesn't affect release builds.
=> Treat kAudioQueueErr_CannotStart as ephemeral.

Machines/Acorn/Electron/Electron.cpp, Machines/Apple/AppleII/AppleII.cpp, Machines/Apple/AppleIIgs/AppleIIgs.cpp, Machines/Atari/2600/Cartridges/ActivisionStack.hpp, Machines/Atari/2600/Cartridges/Atari16k.hpp, Machines/Atari/2600/Cartridges/Atari32k.hpp, Machines/Atari/2600/Cartridges/Atari8k.hpp, Machines/Atari/2600/Cartridges/CBSRAMPlus.hpp, Machines/Atari/2600/Cartridges/Cartridge.hpp, Machines/Atari/2600/Cartridges/CommaVid.hpp, Machines/Atari/2600/Cartridges/MNetwork.hpp, Machines/Atari/2600/Cartridges/MegaBoy.hpp, Machines/Atari/2600/Cartridges/ParkerBros.hpp, Machines/Atari/2600/Cartridges/Pitfall2.hpp, Machines/Atari/2600/Cartridges/Tigervision.hpp, Machines/Atari/2600/Cartridges/Unpaged.hpp, Machines/Commodore/1540/Implementation/C1540.cpp, Machines/Commodore/Plus4/Plus4.cpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Oric/Oric.cpp, Processors/6502/AllRAM/6502AllRAM.cpp, Processors/6502/Implementation/6502Implementation.hpp, Processors/6502Esque/6502Esque.hpp, Processors/65816/Implementation/65816Implementation.hpp
This is possibly preparatory to supplying the bus operation as a template argument. We'll see.
=> Eliminate macros from 6502 bus operation actions.

Machines/Commodore/Plus4/Interrupts.hpp, Machines/Commodore/Plus4/Plus4.cpp
This fixes tape input. Or, at least, restores it to its previous high watermark.
=> Correct status unset-bit masks.

Machines/Commodore/Plus4/Video.hpp
I'm primarily testing this against Alpharay; there's still an off-by-one error somewhere. I'm guessing it's something in my failure to model hcounter_next.
=> Correct shift on hcount write.

Components/6522/6522.hpp, Components/6522/Implementation/6522Implementation.hpp, Machines/Apple/AppleII/Mockingboard.hpp, Machines/Apple/Macintosh/Macintosh.cpp, Machines/Commodore/1540/Implementation/C1540.cpp, Machines/Commodore/1540/Implementation/C1540Base.hpp, Machines/Commodore/SerialBus.hpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Oric/Oric.cpp
Just excising another demon; I don't imagine it makes a substantial difference — or necessarily any difference — at runtime as the constant nature of the port/line parameters should have been easy for the compiler to detect.
=> Reduce repetitive dynamic work in 6522 usages.

.github/workflows/build.yml, Analyser/Static/Commodore/StaticAnalyser.cpp, Analyser/Static/Commodore/Tape.cpp, Analyser/Static/Commodore/Tape.hpp, Machines/Commodore/Plus4/Plus4.cpp, Machines/Commodore/Vic-20/Vic20.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, Outputs/ScanTargets/BufferingScanTarget.cpp, Processors/6502Esque/Implementation/LazyFlags.hpp, Storage/Tape/Formats/CommodoreTAP.cpp, Storage/Tape/Parsers/Commodore.cpp, Storage/Tape/Parsers/Commodore.hpp, Storage/TimedEventLoop.cpp, Storage/TimedEventLoop.hpp
Also temporarily disables Xcode continuous integration, owing to some sort of version mismatch between Apple's released version of Xcode and those available in the GitHub runners.
=> Edge towards fast loading in the Plus 4.

Analyser/Dynamic/MultiMachine/Implementation/MultiProducer.cpp, Outputs/ScanTargets/BufferingScanTarget.cpp
With C++20 I'd be empowered to use concepts, which I think could better document a lot of the otherwise mildly-opaque template requirements.
But I'm just dipping my toe in for now.
=> Resolve two immediate warnings in a C++20 test build.

Analyser/Static/PCCompatible/Target.hpp, InstructionSets/x86/Decoder.cpp, InstructionSets/x86/Decoder.hpp, Machines/PCCompatible/PCCompatible.cpp, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, OSBindings/Qt/mainwindow.cpp
Minor clean-up steps only:
- eliminate the `Decoder8086` workaround, for more natural templating;
- rename `Model::Speed` to capture that it'll be approximately PC models;
- build PC model type into `PCCompatible` template.
I will subsequently need:
1. 286 stuff: protected mode, mainly. Which is a few extra instructions, a little more state and privilege validation;
2. ATA stuff: probably including support for relevant types of hard disk image (VHDs?); and
3. the other AT additions: second interrupt controller, A20 line, etc.
Support for EGA and VGA would be a huge boon beyond there, but that's already a long way off.
=> Tee up for an AT-class PC.

Analyser/Static/PCCompatible/Target.hpp, InstructionSets/x86/Implementation/FlowControl.hpp, InstructionSets/x86/Implementation/PerformImplementation.hpp, InstructionSets/x86/Implementation/Stack.hpp, InstructionSets/x86/Instruction.hpp, Machines/PCCompatible/DMA.hpp, Machines/PCCompatible/Memory.hpp, Machines/PCCompatible/PCCompatible.cpp, Machines/PCCompatible/PIC.hpp, Machines/PCCompatible/ProcessorByModel.hpp, Machines/PCCompatible/Registers.hpp, Machines/PCCompatible/Segments.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, OSBindings/Qt/mainwindow.cpp
At least as far as building; various syntax issues were being hidden by the fact that perform<286> just wasn't in use anywhere in the build.
This also heavily templates the PC compatible's parts on the PC or processor they're meant to represent, to allow for further development there.
=> Repair 286 decoding and `perform`.

Machines/PCCompatible/KeyboardController.hpp, Machines/PCCompatible/PCCompatible.cpp
Thereby clearing a further hurdle and reaching the point of needing 80286 functionality.
Open question: should I continue to try to support the Phoenix BIOS?
=> AT: adjust reported RAM refresh timing.

InstructionSets/x86/Implementation/LoadStore.hpp, InstructionSets/x86/Implementation/PerformImplementation.hpp, InstructionSets/x86/Instruction.hpp, Machines/PCCompatible/Memory.hpp, Machines/PCCompatible/Registers.hpp, Machines/PCCompatible/Segments.hpp
The PC AT BIOS now seems to get as far as trying to switch into protected mode — to [here](https://github.com/gawlas/IBM-PC-BIOS/blob/e6cae33370fa7cd0568d72b785f682971edcc70c/IBM%20PC%20AT/AT%20BIOS%20V3/TEST5.ASM#L241) I think. So now it's time to read some more documentation.
=> Add extra 80286 registers.

InstructionSets/x86/Implementation/Arithmetic.hpp, InstructionSets/x86/Implementation/Logical.hpp
=> x86: clear auxiliary carry on AND, OR, XOR and TEST.

Analyser/Static/Acorn/File.hpp, Storage/Cartridge/Cartridge.hpp
When building the 2025-03-20 release with GCC 15, these two files were missing the `<cstdint>` include.
However, the current Git master builds happily with GCC 15 with no changes, so you may want to reject this. I'm not sure whether you're trying to ensure that includes are always present in the files that use their definitions (in this case, both files do use cstdint types), or just have been included somewhere already...
=> Add some missing <cstdint> includes

InstructionSets/x86/Descriptors.hpp, InstructionSets/x86/Implementation/FlowControl.hpp, InstructionSets/x86/Implementation/LoadStore.hpp, InstructionSets/x86/Implementation/PerformImplementation.hpp, InstructionSets/x86/Registers.hpp, Machines/PCCompatible/PCCompatible.cpp, Machines/PCCompatible/RTC.hpp, Machines/PCCompatible/Segments.hpp
Adding:
* LTR, STR, VERR, VERW, LSL, LAR
Correcting:
* ARPL
... and stepping further toward proper support for protected mode flow control.
The IBM PC AT BIOS now seems to hit further confusion with the keyboard controller, so probably best to look there a bit more.
=> Further implement the 80286

Machines/PCCompatible/LinearMemory.hpp, Machines/PCCompatible/PCCompatible.cpp
This substantially speeds up the boot process, clearing the way for other experimentation.
=> Reduce AT to 640kb RAM.

Components/6845/CRTC6845.hpp, Components/SAA5050/SAA5050.cpp, Components/SAA5050/SAA5050.hpp, Machines/Acorn/BBCMicro/BBCMicro.cpp, Machines/AmstradCPC/AmstradCPC.cpp
In particular:
- reduce redundancy of cursor visibility testing;
- correct blink rates;
- avoid applying SAA5050 smoothing logic when Mode 7 isn't visible; 
- accept that range checks are probably necessary for now on the cursor; and
- mildly improve documentation.
Also adds a one-column delay in CPC output, which affects when palette effects take hold.
=> Variously tweak and improve BBC graphics infrastructure.

Machines/Atari/2600/Atari2600.cpp, Machines/Oric/Video.hpp, Numeric/CubicCurve.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, Outputs/CRT/CRT.cpp, Outputs/CRT/CRT.hpp, Outputs/CRT/Internals/Flywheel.hpp, Outputs/CRT/MismatchWarner.hpp
This might end up being a hefty one; currently machines nominate a crop window for their output ahead of time and the virtual screen is fixed at that crop window. For many machines the window is expressed in terms of magic constants. So the relevant issues are:
1. machines such as the BBC, CPC, Vic-20 and Atari 2600 are explicitly fully programmable in terms of which parts of the display they paint, making a fixed crop always something of a trade-off;
2. even machines such as the ZX Spectrum can sometimes be a target for demo-scene border trickery, in which rapid changing of the border colours appear to put graphics within the borders, giving a similar problem;
3. as it is, I actually have to invest thought into the crop when it's already almost implied by the semantics of the video …
=> Begin move towards automatic cropping.
