Outputs/CRT/Internals/CRTOpenGL.cpp
Display should now be completely fixed.
=> Found and fixed off-by-one error.

Outputs/CRT/CRT.cpp, Outputs/CRT/Internals/CRTConstants.hpp, Outputs/CRT/Internals/CRTOpenGL.cpp, Outputs/CRT/Internals/CRTOpenGL.hpp, Outputs/CRT/Internals/Shaders/IntermediateShader.cpp, Outputs/CRT/Internals/Shaders/Shader.cpp, Outputs/CRT/Internals/Shaders/Shader.hpp
... along with slight refactoring around array attributes.
=> Following the output run switch, switched also to instanced rendering for intermediate scans.

Machines/Atari2600/Atari2600.cpp, Outputs/CRT/CRT.cpp, Outputs/CRT/Internals/CRTOpenGL.cpp, Outputs/CRT/Internals/CRTOpenGL.hpp, Outputs/CRT/Internals/Flywheel.hpp
... thereby fixing PAL colours.
=> Adds an implementation of the PAL-region colour phase shift formula

Machines/Atari2600/Atari2600.cpp, Machines/Atari2600/Atari2600.hpp, Machines/CRTMachine.hpp, Machines/Electron/Electron.cpp, Machines/Electron/Electron.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Documents/Atari2600Document.swift, OSBindings/Mac/Clock Signal/Documents/ElectronDocument.swift, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Views/CSOpenGLView.m, OSBindings/Mac/Clock Signal/Wrappers/AudioQueue.h, OSBindings/Mac/Clock Signal/Wrappers/AudioQueue.m, OSBindings/Mac/Clock Signal/Wrappers/CSAtari2600.h, OSBindings/Mac/Clock Signal/Wrappers/CSAtari2600.mm, OSBindings/Mac/Clock Signal/Wrappers/CSElectron.h, OSBindings/Mac/Clock Signal/Wrappers/CSElectron.mm, OSBindings/Mac/Clock Signal/Wrappers/CSMachine+Subclassing.h, OSBindings/Mac/Clock Signal/Wrappers/CSMachine.h, OSBindings/Mac/Clock Signal/Wrappers/CSMachine.mm, Outputs/CRT/Internals/CRTOpenGL.cpp, Outputs/CRT/Internals/CRTOpenGL.hpp, Outputs/CRT/Internals/Shaders/IntermediateShader.cpp, Outputs/CRT/Internals/Shaders/OutputShader.cpp, Outputs/Speaker.hpp, Processors/6502/CPU6502.hpp
... albeit that it's still not flawless.
This also adds audio and increases CPU/GPU parallelism.
=> Made an attempt substantially to improve Atari 2600 emulation accuracy

Machines/Typer.cpp, Machines/Typer.hpp, Machines/Vic-20/Vic20.cpp, Machines/Vic-20/Vic20.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, Processors/6502/CPU6502.hpp
... this therefore also starts infrastructure for automatic string typing within machines. Which I've utilised to implement paste support, for the Vic only at present.
=> Adds a check for whether PRGs should be loaded to RAM and, if so, installs them post-boot and performs a 'RUN'

Machines/Electron/Electron.cpp, Machines/Electron/Electron.hpp
Thereby enabling paste support.
=> Implements `Utility::TypeRecipient` for the Electron

Components/6532/6532.hpp, Machines/Atari2600/Atari2600.hpp, OSBindings/Mac/Clock SignalTests/6532Tests.swift, OSBindings/Mac/Clock SignalTests/MOS6532Bridge.mm, Processors/6502/CPU6502.hpp
Simultaneously seeking to implement all documented features.
=> Increases unit testing of the 6532

Components/6560/6560.cpp, Components/6560/6560.hpp, Machines/Vic-20/Vic20.cpp
... still imperfect, but I've stopped short of turning it into a template over temporary indecision on whether to split the sound out as a separate part.
=> Improved 6560 emulation and the Vic-20's bus

Machines/Electron/Electron.cpp, Machines/Typer.hpp, Machines/Vic-20/Vic20.cpp, OSBindings/Mac/Clock Signal/Documents/Atari2600Document.swift, OSBindings/Mac/Clock Signal/Documents/ElectronDocument.swift, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Documents/Vic20Document.swift, Outputs/CRT/CRT.cpp, Outputs/CRT/Internals/CRTOpenGL.cpp, Outputs/CRT/Internals/Shaders/IntermediateShader.cpp, Outputs/CRT/Internals/Shaders/OutputShader.cpp, Outputs/CRT/Internals/TextureTarget.cpp, Outputs/Speaker.hpp
Primarily around resetting `unique_ptr`s, but with a minor Swift-side variable improvement.
=> Adds minor reference and pointer style improvements

Components/6522/6522.hpp, Machines/Electron/Electron.cpp, Machines/Electron/Electron.hpp, Machines/Vic-20/Vic20.cpp, Machines/Vic-20/Vic20.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Documents/ElectronDocument.swift, OSBindings/Mac/Clock Signal/Documents/Vic20Document.swift, OSBindings/Mac/Clock Signal/Info.plist, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSElectron.mm, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSVic20.h, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSVic20.mm, OSBindings/Mac/Clock SignalTests/MOS6522Bridge.mm, Storage/Tape/Formats/CommodoreTAP.cpp, Storage/Tape/Formats/CommodoreTAP.hpp, Storage/Tape/Tape.cpp, Storage/Tape/Tape.hpp
Which includes very minor 6522 advancements, as concerns interrupt generation from control lines.
=> Adds basic TAP support for the Vic-20

Machines/Vic-20/Vic20.cpp, Machines/Vic-20/Vic20.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Base.lproj/Vic20Document.xib, OSBindings/Mac/Clock Signal/ClockSignal-Bridging-Header.h, OSBindings/Mac/Clock Signal/Documents/Atari2600Document.swift, OSBindings/Mac/Clock Signal/Documents/ElectronDocument.swift, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Documents/Vic20Document.swift, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSElectron.h, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSVic20.h, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSVic20.mm
For a very relative meaning of 'fast'.
=> Adds 'fast' tape loading for the Vic-20

Processors/6502/CPU6502.hpp
Some work to do on the B flag though, I think.
=> Made an attempt to implement NMI

Components/6522/6522.hpp, Components/6560/6560.cpp, Components/6560/6560.hpp, Machines/Atari2600/Atari2600.cpp, Machines/Atari2600/Atari2600.hpp, Machines/CRTMachine.hpp, Machines/Electron/Electron.cpp, Machines/Electron/Electron.hpp, Machines/Vic-20/Vic20.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/ClockSignal-Bridging-Header.h, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Machine/CSFastLoading.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSElectron.h, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSVic20.h
... and also fixes an omission in the Objective-C repository inclusion.
=> Eliminates plain pointer passes for object types

Machines/Commodore/1540/C1540.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Documents/Vic20Document.swift, OSBindings/Mac/Clock Signal/Info.plist, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSElectron.mm, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSVic20.h, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSVic20.mm, Storage/Disk/Encodings/CommodoreGCR.cpp, Storage/Disk/Encodings/CommodoreGCR.hpp, Storage/Disk/Formats/D64.cpp, Storage/Disk/Formats/D64.hpp, Storage/Disk/PCMTrack.cpp, Storage/Disk/PCMTrack.hpp
... probably the final of the required Vic formats for which I currently have no support whatsoever?
=> Adds support for the .d64 file format

NumberTheory/Factors.cpp, Storage/Disk/Disk.hpp, Storage/Disk/DiskDrive.cpp, Storage/Disk/DiskDrive.hpp, Storage/Disk/PCMTrack.cpp, Storage/Disk/PCMTrack.hpp, Storage/Storage.hpp, Storage/TimedEventLoop.cpp, Storage/TimedEventLoop.hpp
Severely expanding the concept of `Time` as I go.
=> Sought to prevent a reset of angular position when changing tracks

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/AppDelegate.swift, OSBindings/Mac/Clock Signal/Document Controller/DocumentController.swift, OSBindings/Mac/Clock Signal/Documents/Atari2600Document.swift, OSBindings/Mac/Clock Signal/Documents/ElectronDocument.swift, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Documents/Vic20Document.swift, OSBindings/Mac/Clock SignalTests/6502InterruptTests.swift, OSBindings/Mac/Clock SignalTests/6502TimingTests.swift, OSBindings/Mac/Clock SignalTests/6522Tests.swift, OSBindings/Mac/Clock SignalTests/6532Tests.swift, OSBindings/Mac/Clock SignalTests/AllSuiteATests.swift, OSBindings/Mac/Clock SignalTests/C1540Tests.swift, OSBindings/Mac/Clock SignalTests/DPLLTests.swift, OSBindings/Mac/Clock SignalTests/KlausDormannTests.swift, OSBindings/Mac/Clock SignalTests/WolfgangLorenzTests.swift
And allowed Xcode to update to the latest recommended settings.
=> Migrated to Swift 3.

OSBindings/Mac/Clock Signal/Base.lproj/Atari2600Options.xib, OSBindings/Mac/Clock Signal/Base.lproj/ElectronOptions.xib, OSBindings/Mac/Clock Signal/Base.lproj/Vic20Options.xib, OSBindings/Mac/Clock SignalTests/DPLLTests.swift, OSBindings/Mac/Clock SignalTests/WolfgangLorenzTests.swift, Processors/6502/CPU6502.hpp
(and completes correction of the formal unit tests for Swift 3)
=> Resolves failure of the jsbeeb BCDTest.ssd

Components/6560/6560.cpp, Concurrency/AsyncTaskQueue.cpp, Concurrency/AsyncTaskQueue.hpp, Machines/Atari2600/Atari2600.cpp, Machines/Electron/Electron.cpp, Machines/Electron/Electron.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, Outputs/Speaker.hpp
... and by that mechanism makes all audio processing separately threadable. Primarily as a test run.
=> Introduces an asynchronous task queue

Machines/Commodore/1540/C1540.cpp, Machines/Commodore/1540/C1540.hpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Commodore/Vic-20/Vic20.hpp, Machines/Oric/Oric.cpp, Machines/Oric/Oric.hpp, Storage/Tape/Tape.cpp, Storage/Tape/Tape.hpp
Mostly to do with evicting code from headers that needn't be there.
=> Minor code improvements

OSBindings/Mac/Clock Signal/Audio/CSAudioQueue.m
Based on the observation that the audio queue seems to start quick rejecting them.
=> Introduces a reuse list for Mac audio buffers

Machines/Oric/Video.cpp, OSBindings/Mac/Clock Signal/Base.lproj/Atari2600Options.xib, OSBindings/Mac/Clock Signal/Base.lproj/ElectronOptions.xib, OSBindings/Mac/Clock Signal/Base.lproj/MachineDocument.xib, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, Storage/Tape/Formats/OricTAP.cpp, Storage/Tape/Formats/OricTAP.hpp
While also tweaking the Mac UI and fixing the Oric blink attribute's meaning.
=> Makes an attempt to improve the handling of Oric TAPs

OSBindings/Mac/Clock SignalTests/6502TimingTests.swift, Processors/6502/CPU6502.hpp
Particularly re: avoiding conditionals.
=> Simplifies the 6502's main processing loop

Machines/Oric/Video.cpp, Machines/Oric/Video.hpp
For a worthwhile performance decrease, albeit that it's not so clean as it was.
=> Rearranges Oric painting logic to reduce code path complexity

Components/AY38910/AY38910.cpp, Machines/Oric/Oric.cpp, Machines/Oric/Oric.hpp
As well as pulling a few more snippets out of headers.
=> Fixes Oric audio

Components/6522/6522.hpp, Machines/Oric/Oric.cpp, OSBindings/Mac/Clock SignalTests/6522Tests.swift, Outputs/Speaker.hpp
i.e. if the processor sets the timer value this cycle then it isn't a decrementing cycle.
=> Introduces a one-cycle cost to setting 6522 timers

Storage/Tape/Parsers/Oric.cpp, Storage/Tape/Parsers/Oric.hpp
Since that is what I am informed is correct.
=> Switches to Oric tape parsing by full-cycle length only

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Info.plist, StaticAnalyser/StaticAnalyser.cpp, Storage/Disk/Formats/AcornADF.cpp, Storage/Disk/Formats/AcornADF.hpp, Storage/Disk/Formats/D64.cpp, Storage/Disk/Formats/D64.hpp, Storage/Disk/Formats/G64.cpp, Storage/Disk/Formats/G64.hpp, Storage/Disk/Formats/OricMFMDSK.cpp, Storage/Disk/Formats/OricMFMDSK.hpp, Storage/Disk/Formats/SSD.cpp, Storage/Disk/Formats/SSD.hpp, Storage/FileHolder.cpp, Storage/FileHolder.hpp, Storage/Tape/Formats/CommodoreTAP.cpp, Storage/Tape/Formats/CommodoreTAP.hpp, Storage/Tape/Formats/OricTAP.cpp, Storage/Tape/Formats/OricTAP.hpp, Storage/Tape/Formats/TapePRG.cpp, Storage/Tape/Formats/TapePRG.hpp, Storage/Tape/Formats/TapeUEF.cpp, Storage/Tape/Formats/TapeUEF.hpp
... while additionally adding an attempt at support of the Oric MFM .DSK file format.
=> Creates a base class for file format implementations which seeks to collect boilerplate stuff

Machines/Electron/Electron.cpp, Machines/Electron/Electron.hpp, Machines/Electron/Video.cpp, Machines/Electron/Video.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj
Primarily by factoring out video and heavily simplifying the counting that contributes towards interrupts. So this now looks a lot more like the Oric and Vic implementations.
=> Applies a healthy cleaning to the Electron implementation

Components/1770/1770.cpp, Components/1770/1770.hpp, Storage/Disk/Encodings/MFM.hpp
i.e. read/write track and read address.
=> Implements the Type 3 WD177x commands

Machines/Atari2600/Atari2600.cpp, Machines/Atari2600/Atari2600.hpp, Machines/Atari2600/TIA.cpp, Machines/Atari2600/TIA.hpp, Machines/Electron/Video.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Audio/CSAudioQueue.m, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSAtari2600.mm, OSBindings/Mac/Clock Signal/Views/CSOpenGLView.h, OSBindings/Mac/Clock SignalTests/TIATests.mm, Outputs/CRT/CRT.hpp, Outputs/CRT/Internals/ArrayBuilder.cpp, Outputs/CRT/Internals/CRTOpenGL.cpp, Outputs/CRT/Internals/CRTOpenGL.hpp, Outputs/CRT/Internals/Shaders/IntermediateShader.cpp, Outputs/CRT/Internals/Shaders/IntermediateShader.hpp, Outputs/CRT/Internals/Shaders/Shader.cpp, Outputs/CRT/Internals/Shaders/Shader.hpp, StaticAnalyser/Atari/StaticAnalyser.cpp, StaticAnalyser/Disassembler/Disassembler6502.cpp, StaticAnalyser/Disassembler/Disassembler6502.hpp, StaticAnalyser/StaticAnalyser.cpp, StaticAnalyser/StaticAnalyser.hpp
Also bringing speed improvements and some accuracy benefits, though the latter needs a lot more work.
A couple of machine startup and shutdown race conditions are also fixed here, as they happened to crop up.
=> Reimplements the Atari TIA, as a discrete component

Components/6532/6532.hpp, Machines/Atari2600/Atari2600.cpp, Machines/Atari2600/Atari2600.hpp, OSBindings/Mac/Clock SignalTests/6532Tests.swift
... and turns it into a deferred work component.
=> Improves 6532 counting accuracy

Machines/Atari2600/Atari2600.cpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock Signal/Audio/CSAudioQueue.m, StaticAnalyser/Atari/StaticAnalyser.cpp
... and fixes an audio queue race condition.
=> Adds detection and emulation of the Tigervision paging scheme

.gitignore, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock SignalTests/Atari ROMs/readme.txt, OSBindings/Mac/Clock SignalTests/AtariStaticAnalyserTests.mm, StaticAnalyser/Atari/StaticAnalyser.cpp
... and thereby 'perfects' it (i.e. across the given sample set).
=> Introduces unit tests for the Atari static analyser

OSBindings/Mac/Clock Signal/Audio/CSAudioQueue.m
Specifically that even when requesting a synchronous (i.e. blocking) shutdown of a queue, audio callbacks can still be received after the queue is ostensibly shut down.
=> Works around what appears to be a bug in Apple's AudioQueue.

Machines/Commodore/Vic-20/Vic20.cpp, Storage/Cartridge/Formats/PRG.cpp
... and makes some minor tidying moves.
=> Permits ROM-area located PRGs that are not a power-of-two in size

Machines/Commodore/Vic-20/Vic20.cpp, Machines/Commodore/Vic-20/Vic20.hpp, OSBindings/Mac/Clock Signal/Base.lproj/Vic20Options.xib, OSBindings/Mac/Clock Signal/Documents/Vic20OptionsPanel.swift, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSVic20.h, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSVic20.mm
Given that it isn't being offered elsewhere; intention is to offer that sort of access via File -> New... .
=> Formally withdraws the 'load automatically' option for the Vic

OSBindings/Mac/Clock SignalTests/FUSETests.swift, OSBindings/Mac/Clock SignalTests/ZexallTests.swift, Processors/Z80/Z80.hpp
I've added some basic memptr emulation steps, but chickened out in the absence of easier tests. I'm going to take a step back and think about that, I think.
=> Corrects bit 3 & 5 emulation for everything except BIT n, (HL)

Machines/ZX8081/ZX8081.cpp, Processors/Z80/Z80.hpp
... and also seeks to ensure that the ZX81 hence triggers them when exiting a HALT during an NMI.
=> Ensures wait states are observed during interrupt response

Machines/ZX8081/ZX8081.cpp, Machines/ZX8081/ZX8081.hpp, Storage/Tape/Formats/ZX80O81P.cpp, Storage/Tape/Parsers/ZX8081.cpp, Storage/Tape/Tape.cpp
Albeit in a way that starts to emphasise the limits of just-in-time substitution of a parser.
=> Corrects ZX81 fast loading

Machines/ZX8081/ZX8081.cpp, Machines/ZX8081/ZX8081.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Base.lproj/ZX8081Options.xib, OSBindings/Mac/Clock Signal/ClockSignal-Bridging-Header.h, OSBindings/Mac/Clock Signal/Documents/ZX8081OptionsPanel.swift, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSZX8081.h, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSZX8081.mm, Storage/Tape/Formats/ZX80O81P.cpp
=> Introduces both manual and automatic tape control for the ZX80 and 81

Machines/Electron/Electron.cpp, Machines/ZX8081/Typer.cpp, Machines/ZX8081/ZX8081.cpp, Machines/ZX8081/ZX8081.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, StaticAnalyser/ZX8081/StaticAnalyser.cpp
Simultaneously becoming smart enough to know what to type to begin tape loading. But not usually smart enough to get a program to run.
=> Introduces preliminary `Typer` support for the ZX80 and ZX81

Machines/Commodore/1540/C1540.cpp, Machines/Commodore/1540/C1540.hpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Commodore/Vic-20/Vic20.hpp, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, Outputs/Speaker.hpp, Storage/Disk/DigitalPhaseLockedLoop.cpp, Storage/Disk/DigitalPhaseLockedLoop.hpp
Dating back to my first steps back into C++; just replaced them all with vectors.
=> Corrects some long-standing unnecessarily convoluted ways to handle semi-dynamic arrays

OSBindings/Mac/Clock Signal/Info.plist, StaticAnalyser/StaticAnalyser.cpp, Storage/FileHolder.cpp, Storage/FileHolder.hpp, Storage/Tape/Formats/ZX80O81P.cpp
Which is exactly the same as O, P, 80 and 81, except that it's ZX81 targeted and includes the file name.
=> Adds support for the P81 file format

ClockReceiver/ClockReceiver.hpp, Components/6522/6522.hpp, Components/6532/6532.hpp, Components/6560/6560.hpp, Machines/Atari2600/TIA.hpp, Machines/Electron/Electron.hpp, Machines/Electron/Video.hpp, Machines/Oric/Video.hpp, Machines/ZX8081/Video.hpp, Machines/ZX8081/ZX8081.cpp, Machines/ZX8081/ZX8081.hpp, Outputs/Speaker.hpp, Processors/6502/6502.hpp, Processors/Z80/Z80.hpp, Storage/Disk/DigitalPhaseLockedLoop.hpp, Storage/Tape/Tape.hpp, Storage/TimedEventLoop.hpp
Full disclosure: owing to the previous pull request having been prematurely merged in error.
=> Completes revocation of ClockReceiver

Storage/Tape/Formats/TZX.cpp, Storage/Tape/Formats/TZX.hpp
Continuing empirically for now; a complete sweep can't be far off though.
=> Further expands the implemented subset of the TZX file format

Machines/AmstradCPC/AmstradCPC.cpp
There is no longer an assumption that the border colour will be consistent across however much time the CRTC happens to imply it should be plotted between display and sync. So no more false perfect horizontals.
Also corrects a minor error in my colour table.
=> Removes quick-hack solution for border drawing

Machines/AmstradCPC/AmstradCPC.cpp
This, as it turns out, is why I had a big black bar on the left of the screen: the gate array doesn't blindly pass the CRTC's horizontal sync along — after a short delay to act at all, it caps it.
=> Introduces filtering of the CRTC's hsync signal into the gate array.

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, StaticAnalyser/StaticAnalyser.cpp, Storage/Disk/Formats/CPCDSK.cpp, Storage/Disk/Formats/CPCDSK.hpp, Storage/Disk/Formats/SSD.cpp
Still very incomplete, but gives a foothold from which to begin an 8272/FDC765 emulation.
=> Introduces parsing of the file format support for the simplest of CPC disks

Machines/AmstradCPC/AmstradCPC.cpp, StaticAnalyser/AmstradCPC/StaticAnalyser.cpp
... and defaults to requesting a 6128 when loading a disk.
=> Introduces support for 128kb CPCs.

Components/8272/i8272.cpp, Storage/Disk/Drive.cpp, Storage/Disk/Drive.hpp
* implements sense drive status;
* implements multi-sector reads (confined to a single head for now).
=> Continues building up the 8272

Components/6845/CRTC6845.hpp, Machines/AmstradCPC/AmstradCPC.cpp
As well as making minor fixes for register sizes and quantity, and correcting the Amstrad CPC's general bus behaviour.
=> Corrects 6845 address loading

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, StaticAnalyser/Acorn/Disk.cpp, StaticAnalyser/AmstradCPC/StaticAnalyser.cpp, Storage/Disk/Encodings/MFM.cpp, Storage/Disk/Encodings/MFM.hpp, Storage/Disk/Formats/AcornADF.cpp, Storage/Disk/Formats/SSD.cpp, Storage/Disk/Parsers/CPM.cpp, Storage/Disk/Parsers/CPM.hpp
Also improves and expands on the MFM parser, making it aware that drives may have multiple heads and giving it some caching logic that seeks to cut down on processing costs.
=> Introduces a CP/M catalogue parser, as a basic for the CPC's static analyser

Machines/AmstradCPC/AmstradCPC.cpp, Machines/AmstradCPC/AmstradCPC.hpp, Machines/AmstradCPC/CharacterMapper.cpp, Machines/AmstradCPC/CharacterMapper.hpp, Machines/Typer.cpp, Machines/ZX8081/CharacterMapper.hpp, Machines/ZX8081/ZX8081.cpp, Machines/ZX8081/ZX8081.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, StaticAnalyser/AmstradCPC/StaticAnalyser.cpp
Simultaneously corrects a destruction bug of the CPC and ZX80/81, and adds an additional fallback approach to CPC static analysis.
=> Introduces typer support for the Amstrad CPC.

Components/8272/i8272.cpp, Components/8272/i8272.hpp, Storage/Disk/Formats/CPCDSK.cpp
To include:
* the read deleted data command;
* head loading/unloading times; and
* various potential read [deleted] error conditions.
=> Expands 8272 emulation further

Components/8272/i8272.cpp
In particular, eliminating magical bits.
=> Improves 8272 implementation style

Components/6845/CRTC6845.hpp, Components/8272/i8272.cpp, Components/8272/i8272.hpp, Concurrency/AsyncTaskQueue.cpp, Machines/AmstradCPC/AmstradCPC.cpp, StaticAnalyser/AmstradCPC/StaticAnalyser.cpp, Storage/Disk/DiskController.cpp, Storage/Disk/Drive.cpp, Storage/Disk/Drive.hpp, Storage/Disk/Encodings/MFM.cpp, Storage/Disk/Formats/CPCDSK.cpp, Storage/Disk/MFMDiskController.cpp, Storage/Disk/MFMDiskController.hpp
As well as:
* accuracy improvements to the seek infrastructure; and
* a fix to step timing.
=> Introduces initial implementations of the 8272's write data, write deleted data, read track and format track

Components/1770/1770.cpp, Components/1770/1770.hpp, Components/8272/i8272.cpp, Components/8272/i8272.hpp, Storage/Disk/MFMDiskController.cpp, Storage/Disk/MFMDiskController.hpp
Also pulls a few additional things out of the 8272 into the parent class, as utilities and because of likely reuse.
=> Brings the 1770 into usage of those parts factored out of it for the 8272

Machines/Oric/Oric.cpp, Machines/Oric/Oric.hpp, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSOric.mm
Also: corrects a minor threading issue with the Mac integration thereof.
=> Hides the Oric implementation innards

Machines/AmstradCPC/AmstradCPC.hpp, Machines/Atari2600/Atari2600.cpp, Machines/Atari2600/Atari2600.hpp, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSAtari2600.mm
While slightly improving the commenting around the Amstrad CPC, as I was looking at that as a reference while working on this.
=> Catches the Atari 2600 up with the no-internals-published trend.

Machines/AmstradCPC/AmstradCPC.hpp, Machines/Electron/Electron.cpp, Machines/Electron/Electron.hpp, Machines/Oric/Oric.hpp, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSElectron.mm
While improving some of the verbiage used elsewhere for informally-similar comments.
=> Adds the Electron to the pantheon of machines that reveal very little in their public interface

Machines/Commodore/Vic-20/Vic20.cpp, Machines/Commodore/Vic-20/Vic20.hpp, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSVic20.mm
Specifically so as to hide the overwhelming majority of implementation details, which in this case are substantial.
=> Brings the Vic-20 into line with the new idiom on machine declaration

StaticAnalyser/AmstradCPC/StaticAnalyser.cpp
i.e. even if no CP/M catalogue is found anywhere.
Implied TODO: be more rigorous about what's an acceptable boot sector. Will probably need a Z80 disassembler.
=> Generalises: an acceptable boot sector is always acceptable

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Info.plist, StaticAnalyser/StaticAnalyser.cpp, Storage/Disk/Formats/HFE.cpp, Storage/Disk/Formats/HFE.hpp
Thereby revealing problems with the static analyser's MFM decoder. But the 8272 soldiers on like a champion.
=> Introduces support for the HFE file format.

ClockReceiver/ForceInline.hpp, ClockReceiver/Sleeper.h, ClockReceiver/Sleeper.hpp, Components/8272/i8272.cpp, Components/8272/i8272.hpp, Machines/AmstradCPC/AmstradCPC.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, Storage/Disk/DiskController.cpp, Storage/Disk/DiskController.hpp, Storage/Disk/Drive.cpp, Storage/Disk/Drive.hpp, Storage/Tape/Tape.cpp, Storage/Tape/Tape.hpp
Ensures that both the tape player and the 8272 are sleepers, and wires action down into the CPC.
=> Experimentally introduces the concept of a 'sleeper' — a component that will volunteer to be unclocked for a period

Components/6845/CRTC6845.hpp, Outputs/Speaker.hpp
Mildly increases accuracy in so doing.
=> Refactors the 6845 to make end-of-line and end-of-frame conditions more explicit and to reduce repetition

Processors/Z80/Z80.hpp
... with the exception of the target of *value, since that's intended to be writeable by recipients.
=> Makes all of PartialMachineCycle const

Outputs/CRT/Internals/CRTOpenGL.cpp, StaticAnalyser/Disassembler/Disassembler6502.cpp, StaticAnalyser/StaticAnalyser.cpp, Storage/Disk/Encodings/MFM.cpp, Storage/Disk/Formats/OricMFMDSK.cpp
Including a memory leak in the static analyser resulting from an incomplete factoring out of file opening.
=> Resolves all current analyser warnings.

Components/6845/CRTC6845.hpp
Thereby gets one step closer to satisfying Arnold's cpctest.
=> Moves test for 6845 horizontal sync timing into the time after phase 1 and before phase 2

Machines/AmstradCPC/AmstradCPC.cpp, Machines/ZX8081/ZX8081.cpp, Processors/Z80/Z80.hpp
With runtime costs decreasing slightly if a Z80 user opts out.
=> Makes the Z80's support for WAIT input optional

OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm
Given that the option is not honoured.
=> Removes the CPC options panel.

OSBindings/Mac/Clock Signal/Machine/CSMachine.mm
Explicit cause: dealloc calls close_output(). That may decide to flush work, indiscriminately. Some of the flushed work might be audio generation. Audio generation might cause the audio queue to react with an out-of-data announcement. Which would cause a fresh attempt to update the CSMachine.
=> Eliminates potential cyclic entry into CSMachine during its `-dealloc`.

Components/6522/6522.hpp, Components/6522/Implementation/6522Base.cpp, Components/6522/Implementation/6522Implementation.hpp, Components/6522/Implementation/6522Storage.hpp, Components/6522/Implementation/IRQDelegatePortHandler.cpp, Machines/Commodore/1540/C1540.cpp, Machines/Commodore/1540/C1540.hpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Oric/Oric.cpp, Machines/Oric/Video.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj
Eliminating the recurring template pattern, and adjusting all affected systems. Also cleans up the Oric generally, being the easiest of the three 6522 users to address.
=> Significantly cleans up the 6522.

Storage/Disk/Parsers/CPM.cpp
Resulting from failure to treat a number o…f records of 0x80 as a special case.
=> Corrects CPM reader buffer overwrites

OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/SDL/main.cpp, Outputs/CRT/CRT.hpp, Outputs/CRT/Internals/CRTOpenGL.cpp, Outputs/CRT/Internals/CRTOpenGL.hpp
Breaking the assumption that it'll be zero.
=> Allows a CRT machine owner to set the target frame buffer for OpenGL output.

OSBindings/SDL/main.cpp
This gives an additional hook from which machine updates can be hooked, so separates that buffer size from any implicit frame rate assumptions.
=> Switches to using the supply-on-demand audio route through SDL.

Machines/Electron/Video.cpp
As per https://github.com/TomHarte/CLK/issues/300.
=> Corrects Electron Mode 3 timing.

Machines/Oric/Oric.cpp
Re: https://github.com/TomHarte/CLK/issues/299
=>  Ensures Oric video output starts up and changes validly.

Machines/AmstradCPC/AmstradCPC.cpp, Machines/AmstradCPC/AmstradCPC.hpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Commodore/Vic-20/Vic20.hpp, Machines/Electron/Electron.cpp, Machines/Electron/Electron.hpp, Machines/Oric/Oric.cpp, Machines/Oric/Oric.hpp, Machines/ZX8081/ZX8081.cpp, Machines/ZX8081/ZX8081.hpp, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSElectron.mm, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSOric.mm, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSVic20.mm, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSZX8081.mm
... and adapts the Mac port to cope.
=> Withdraws genericised selection and ROM provision interfaces.

Outputs/CRT/Internals/CRTOpenGL.cpp, Outputs/CRT/Internals/Shaders/IntermediateShader.cpp, Outputs/CRT/Internals/Shaders/IntermediateShader.hpp, Outputs/CRT/Internals/Shaders/OutputShader.cpp, Outputs/CRT/Internals/Shaders/OutputShader.hpp, Outputs/CRT/Internals/Shaders/Shader.cpp, Outputs/CRT/Internals/Shaders/Shader.hpp, Outputs/CRT/Internals/TextureTarget.cpp
Addresses https://github.com/TomHarte/CLK/issues/285
=> Formalises naming of shader inputs and related guarantees.

Machines/Utility/MachineForTarget.cpp, Machines/Utility/TypedDynamicMachine.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Documents/ElectronOptionsPanel.swift, OSBindings/Mac/Clock Signal/Machine/CSMachine+Subclassing.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSAmstradCPC.mm, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSAtari2600.mm, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSElectron.h, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSElectron.mm, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSOric.h, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSOric.mm, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSVic20.h, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSVic20.mm, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSZX8081.h, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSZX8081.mm
Thereby eliminating plenty of duplication.
=> Adapts the Mac port to use a Machine::DynamicMachine.

Components/9918/9918.cpp, Components/9918/9918.hpp, Machines/MSX/MSX.cpp
Also corrects a half-speed output bug in the TMS hence uncovered.
=> Attempts real VRAM access timings for the TMS9918a

Machines/MSX/Keyboard.hpp, Machines/MSX/MSX.cpp, OSBindings/Mac/Clock Signal/Info.plist, StaticAnalyser/MSX/StaticAnalyser.cpp, StaticAnalyser/StaticAnalyser.cpp, Storage/Tape/Formats/TZX.cpp, Storage/Tape/Formats/TZX.hpp, Storage/TimedEventLoop.cpp
And fixes a minor keyboard mapping error.
=> Introduces TSX support for the MSX.

Machines/AmstradCPC/AmstradCPC.cpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Electron/Electron.cpp, Machines/KeyboardMachine.cpp, Machines/KeyboardMachine.hpp, Machines/MSX/MSX.cpp, Machines/MSX/MSX.hpp, Machines/Oric/Oric.cpp, Machines/Utility/MachineForTarget.cpp, Machines/Utility/Typer.cpp, Machines/Utility/Typer.hpp, Machines/ZX8081/ZX8081.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/SDL/main.cpp, StaticAnalyser/Acorn/StaticAnalyser.cpp, StaticAnalyser/AmstradCPC/StaticAnalyser.cpp, StaticAnalyser/Commodore/StaticAnalyser.cpp, StaticAnalyser/MSX/StaticAnalyser.cpp, StaticAnalyser/MSX/Tape.cpp, StaticAnalyser/MSX/Tape.hpp, StaticAnalyser/Oric/StaticAnalyser.cpp, StaticAnalyser/StaticAnalyser.hpp, StaticAnalyser/ZX8081/StaticAnalyser.cpp, Storage/Tape/Formats/CAS.cpp, Storage/Tape/Formats/CAS.hpp, Storage/Tape/Parsers/MSX.cpp, Storage/Tape/Parsers/MSX.hpp, Storage/Tape/Tape.cpp, Storage/Tape/Tape.hpp
With corresponding automatic launches. And that meant it was easy to provide fast tape loading.
=> Introduces basic tape analysis for the MSX

OSBindings/Mac/Clock Signal/Info.plist
Will need to survey all the other Mac emulators to get a complete list, I guess.
=> Adds document type UTIs.

.gitignore, Machines/MSX/Cartridges/ASCII16kb.hpp, Machines/MSX/Cartridges/ASCII8kb.hpp, Machines/MSX/Cartridges/Konami.hpp, Machines/MSX/Cartridges/KonamiWithSCC.hpp, Machines/MSX/MSX.cpp, Machines/MSX/ROMSlotHandler.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/Mac/Clock Signal/Machine/CSROMFetcher.hpp, OSBindings/Mac/Clock Signal/Machine/CSROMFetcher.mm, OSBindings/Mac/Clock Signal/Machine/NSBundle+DataResource.m, OSBindings/Mac/Clock SignalTests/Bridges/C1540Bridge.h, OSBindings/Mac/Clock SignalTests/Bridges/C1540Bridge.mm, OSBindings/Mac/Clock SignalTests/C1540Tests.swift, OSBindings/Mac/Clock SignalTests/MSX ROMs/readme.txt, OSBindings/Mac/Clock SignalTests/MSXStaticAnalyserTests.mm, StaticAnalyser/MSX/StaticAnalyser.cpp, StaticAnalyser/StaticAnalyser.hpp
Replete with a failing test proving that the type auto-detection works poorly at present.
=> Introduces a basic attempt at MSX MegaROM support

Components/1770/1770.cpp, Components/1770/1770.hpp, Machines/MSX/DiskROM.cpp, Machines/MSX/DiskROM.hpp, Machines/MSX/MSX.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, ROMImages/MSX/readme.txt, StaticAnalyser/MSX/StaticAnalyser.cpp, StaticAnalyser/StaticAnalyser.cpp, Storage/Disk/DiskImage/Formats/AcornADF.cpp, Storage/Disk/DiskImage/Formats/MFMSectorDump.cpp, Storage/Disk/DiskImage/Formats/MFMSectorDump.hpp, Storage/Disk/DiskImage/Formats/MSXDSK.cpp, Storage/Disk/DiskImage/Formats/MSXDSK.hpp, Storage/Disk/DiskImage/Formats/OricMFMDSK.hpp, Storage/Disk/DiskImage/Formats/SSD.cpp, Storage/Disk/DiskImage/Formats/Utility/ImplicitSectors.cpp
Supporting .DSK only, for now.
=> Adds floppy emulation for the MSX

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Info.plist, StaticAnalyser/StaticAnalyser.cpp, Storage/Disk/DiskImage/Formats/AcornADF.hpp, Storage/Disk/DiskImage/Formats/CPCDSK.hpp, Storage/Disk/DiskImage/Formats/D64.hpp, Storage/Disk/DiskImage/Formats/DMK.cpp, Storage/Disk/DiskImage/Formats/DMK.hpp, Storage/Disk/DiskImage/Formats/G64.hpp, Storage/Disk/DiskImage/Formats/HFE.hpp, Storage/Disk/DiskImage/Formats/MFMSectorDump.hpp, Storage/Disk/DiskImage/Formats/OricMFMDSK.cpp, Storage/Disk/DiskImage/Formats/SSD.hpp, Storage/Disk/Track/PCMSegment.hpp
Along with some small adjacent acts of cleaning.
=> Adds support for the DMK file format

OSBindings/Mac/Clock Signal/Info.plist, Storage/Tape/Parsers/MSX.cpp
Also reintroduces proper file type association for TSX on the Mac.
=> Makes MSX tape parsing more tolerant to phase.

Components/9918/9918.cpp
So that the MSX no longer looks burnt out.
=> Sets TMS input gamma.

Machines/Commodore/Vic-20/Vic20.cpp, Machines/Electron/Electron.cpp, Machines/MSX/MSX.cpp, Machines/ZX8081/ZX8081.cpp, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/Mac/Clock Signal/Updater/CSBestEffortUpdater.mm
In the:
* MSX;
* Electron;
* Vic-20; and
* ZX80/81.
=> Reduces cost of checking for fast-tape usage

Machines/MSX/MSX.cpp, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Updater/CSBestEffortUpdater.mm
Specifically totalling a 5–10% cut in processing.
=> Introduces modest MSX optimisations

Machines/ColecoVision/ColecoVision.cpp, Machines/ZX8081/ZX8081.cpp
Thereby addresses https://github.com/TomHarte/CLK/issues/362
=> Introduces ZonX emulation and corrects a minor ColecoVision AY timing issue.

Analyser/Dynamic/MultiMachine/Implementation/MultiConfigurationTarget.cpp, Analyser/Dynamic/MultiMachine/Implementation/MultiConfigurationTarget.hpp, Analyser/Static/Acorn/StaticAnalyser.cpp, Analyser/Static/Acorn/Target.hpp, Analyser/Static/AmstradCPC/StaticAnalyser.cpp, Analyser/Static/AmstradCPC/Target.hpp, Analyser/Static/Atari/StaticAnalyser.cpp, Analyser/Static/Atari/Target.hpp, Analyser/Static/Commodore/StaticAnalyser.cpp, Analyser/Static/Commodore/Target.hpp, Analyser/Static/Oric/StaticAnalyser.cpp, Analyser/Static/Oric/Target.hpp, Analyser/Static/StaticAnalyser.hpp, Analyser/Static/ZX8081/StaticAnalyser.cpp, Analyser/Static/ZX8081/Target.hpp, Machines/AmstradCPC/AmstradCPC.cpp, Machines/Atari2600/Atari2600.cpp, Machines/ColecoVision/ColecoVision.cpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/ConfigurationTarget.hpp, Machines/Electron/Electron.cpp, Machines/MSX/MSX.cpp, Machines/Oric/Oric.cpp, Machines/Utility/MachineForTarget.cpp, Machines/ZX8081/ZX8081.cpp, Machines/ZX8081/ZX8081.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj
Resolves https://github.com/TomHarte/CLK/issues/311.
=> Encapsulates per-platform analyser result fields.

Analyser/Static/Acorn/Target.hpp, Analyser/Static/AmstradCPC/Target.hpp, Analyser/Static/Atari/Target.hpp, Analyser/Static/Commodore/Target.hpp, Analyser/Static/Oric/Target.hpp, Analyser/Static/ZX8081/Target.hpp, Components/6560/6560.hpp, Concurrency/AsyncTaskQueue.cpp, Machines/AmstradCPC/AmstradCPC.cpp, Machines/Atari2600/Bus.hpp, Machines/ColecoVision/ColecoVision.cpp, Machines/Electron/Electron.cpp, Machines/MSX/MSX.cpp, Machines/Oric/Oric.cpp, Machines/ZX8081/ZX8081.cpp, Processors/Z80/Implementation/Z80Storage.hpp, Storage/Disk/Encodings/MFM/SegmentParser.cpp
Including a machine shutdown race condition.
=> Resolves various pieces of undefined behaviour.

Analyser/Dynamic/MultiMachine/Implementation/MultiJoystickMachine.cpp, Analyser/Static/Oric/StaticAnalyser.cpp, Concurrency/BestEffortUpdater.hpp
=> Introduces missing #includes.

Analyser/Static/AmstradCPC/StaticAnalyser.cpp
=> Corrects nullptr references in the CPC static analyser.

Analyser/Static/Commodore/StaticAnalyser.cpp, Machines/Commodore/Vic-20/Vic20.cpp
Also corrects an unsafe assumption in fast loading.
=> Strips back Vic-20 static analysis to the bare minimum.

Analyser/Static/Commodore/Target.hpp, Components/6560/6560.hpp, Machines/Commodore/1540/Implementation/C1540.cpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Commodore/Vic-20/Vic20.hpp
Also formalises region and memory model as startup parameters of a Vic-20.
=> Tweaks VIC palette, especially PAL.

Components/6560/6560.hpp, Machines/Commodore/Vic-20/Vic20.cpp
Different chips, but partially the same palette according to direct inspection.
=> Introduces Vic luminances sourced from the TED manual.

Components/6560/6560.cpp, Components/6560/6560.hpp
Thereby resolves a clipping issue.
=> Causes the 6560 to obey `set_sample_volume_range`.

OSBindings/Mac/Clock Signal/New Group/Base.lproj/MachinePicker.xib
... and to try to tell users that they're doing it wrong.
=> Tweaks the 'new machine' dialogue for ZX memory size

Machines/ZX8081/ZX8081.cpp
=> Simplifies the test for resetting the ZX80/81 line counter.

Analyser/Static/AppleII/StaticAnalyser.cpp, Analyser/Static/AppleII/Target.hpp, Machines/AppleII/AppleII.cpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.h, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, OSBindings/Mac/Clock Signal/New Group/Base.lproj/MachinePicker.xib, OSBindings/Mac/Clock Signal/New Group/MachinePicker.swift
Specifically: II or II+? Disk II 13- or 16-sector? Or not at all?
=> Introduces configuration options for the Apple II.

Analyser/Static/DiskII/StaticAnalyser.cpp, Machines/AppleII/AppleII.cpp, Storage/Disk/Encodings/AppleGCR/SegmentParser.cpp
Also corrects adjacent errors in the Disk II analyser and an Apple II shutdown race condition.
=> Implements the Apple II language card

Analyser/Static/DiskII/StaticAnalyser.cpp, Analyser/Static/Oric/StaticAnalyser.cpp, Analyser/Static/Oric/Target.hpp, Components/DiskII/DiskII.cpp, Components/DiskII/DiskII.hpp, Machines/AppleII/DiskIICard.cpp, Machines/Oric/Oric.cpp, Machines/Oric/Oric.hpp, Machines/Utility/MachineForTarget.cpp, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.h, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, OSBindings/Mac/Clock Signal/New Group/Base.lproj/MachinePicker.xib, OSBindings/Mac/Clock Signal/New Group/MachinePicker.swift, ROMImages/Oric/readme.txt
i.e. the Disk II wired up to the Oric, with some ROM swaps.
=> Makes attempt to implement support for the Pravetz 8D + 8DOS.

Machines/Oric/Oric.cpp, Storage/Disk/DiskImage/Formats/AppleDSK.cpp
Primarily by fixing DSK file handling, but also by clarifying the Oric code.
=> Corrects Pravetz 8DOS startup.

Storage/Disk/Encodings/AppleGCR/SegmentParser.cpp
It's now a length test that at present accepts 6-and-2 sectors only.
=> Removes requirement for correct sector epilogues.

OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Views/CSOpenGLView.h, OSBindings/Mac/Clock Signal/Views/CSOpenGLView.m
Also updates documentation around CSOpenGLView.
=> Corrects Mac paste pathway.

Machines/AppleII/AppleII.cpp, Machines/AppleII/Video.hpp
I'm going to call this the resolution of both #425 and #399 as it was the last substantial unimplemented piece of an Apple II.
=> Attempts to implement vapour lock bus behaviour.

Machines/AppleII/AppleII.cpp, Machines/AppleII/DiskIICard.cpp, Storage/Disk/DiskImage/Formats/AppleDSK.cpp, Storage/Disk/Track/PCMSegment.cpp
It's now the case that the majority of things work rather than fail; I think that fixing segment conjugation is the big one here.
=> Corrects various Apple DSK handling errors.

Machines/AppleII/AppleII.cpp, OSBindings/Mac/Clock Signal/Audio/CSAudioQueue.m
Also seeks to prevent excessive build-up of buffered audio.
=> Introduces a low-pass filter for the Apple II

Machines/ColecoVision/ColecoVision.cpp
This is my reading of (i) the SN76489 data sheet; plus (ii) the ColecoVision schematic.
=> Imposes a three-cycle penalty for SN76489 access.

Machines/Oric/Microdisc.cpp, Machines/Oric/Microdisc.hpp, Machines/Oric/Oric.cpp
=> Corrects meaning of the Microdisc's paging control.

Storage/Disk/DiskImage/Formats/AppleDSK.hpp, Storage/Disk/DiskImage/Formats/NIB.cpp, Storage/Disk/DiskImage/Formats/NIB.hpp, Storage/Disk/DiskImage/Formats/WOZ.hpp
Also introduces an additional validation test for NIBs beyond size: all top bits set.
=> Adds write support for NIBs 

Storage/Data/ZX8081.cpp
Thereby allowing Humpty Dumpty to load, resolving #453
=> Relaxes .p validation even further

OSBindings/SDL/main.cpp
=> Changes SDL full screen/window toggle and allows ROM path to be specified

Outputs/CRT/CRT.cpp, Outputs/CRT/Internals/CRTOpenGL.cpp, Outputs/CRT/Internals/Shaders/IntermediateShader.cpp, Outputs/CRT/Internals/Shaders/OutputShader.cpp
...  and corrects PAL colour generation from an RGB source. It was previously far too bright, with colour loss as a result.
=> Tweaks blending back to appease interlaced video

Outputs/CRT/Internals/CRTOpenGL.cpp, Outputs/CRT/Internals/TextureTarget.cpp, Outputs/CRT/Internals/TextureTarget.hpp
=> Hides persistent low-part colour channel errors.

Components/1770/1770.cpp, Components/8272/i8272.cpp, Machines/Electron/Electron.cpp, Machines/Electron/Plus3.cpp, Machines/Electron/Plus3.hpp, Machines/MSX/DiskROM.cpp, Machines/MSX/DiskROM.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Base.lproj/Activity.xib, OSBindings/Mac/Clock Signal/Base.lproj/MainMenu.xib, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, Outputs/Log.hpp, Storage/Disk/Drive.cpp
I.e. disk activity, and any other LEDs. And in celebration of which, introduces proper logging macros so that the two disk controllers that talk a lot do not do so in release builds.
=> Shows activity indicators on the Mac

Processors/Z80/Implementation/Z80Storage.cpp
Specifically, puts the enforced wait either before or after checking the wait line. More research may be required; it feels more likely to me that a forced post wait should complete the read then wait, but would that still count as a single machine cycle?
Either way, resolves #477
=> Differentiates reasons for a read to be four cycles.

Machines/AmstradCPC/AmstradCPC.cpp, Machines/AppleII/Video.cpp, Machines/Electron/Video.cpp, Machines/Oric/Video.cpp, Outputs/CRT/CRT.cpp
In the hope of moving the CPC closer to the real CTM visible area.
=> [Re-]recalibrates CRT retrace period and affected view windows.

Components/9918/9918.cpp
Also adds a little extra documentation.
Resolves #496.
=> Ensures only the first 8px of sprites is output in 8x8 mode.

Activity/Observer.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/SDL/main.cpp, Outputs/CRT/Internals/CRTOpenGL.cpp, Outputs/CRT/Internals/CRTOpenGL.hpp, Outputs/CRT/Internals/Rectangle.cpp, Outputs/CRT/Internals/Rectangle.hpp, Outputs/CRT/Internals/Shaders/OutputShader.cpp, Outputs/CRT/Internals/Shaders/OutputShader.hpp, Outputs/CRT/Internals/TextureTarget.hpp
As well as introducing drive status lights in SDL mode, given that a usable primitive has become available.
Thereby resolves #473 and completes #426.
=> Resolves border issues in fullscreen mode

Inputs/Joystick.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Clock Signal.entitlements, OSBindings/Mac/Clock Signal/ClockSignal-Bridging-Header.h, OSBindings/Mac/Clock Signal/Document Controller/DocumentController.swift, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Joystick Manager/CSJoystickManager.h, OSBindings/Mac/Clock Signal/Joystick Manager/CSJoystickManager.m, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm
As in: your real joystick controlling the emulated machine.
=> Implements initial joystick support for the Mac

OSBindings/SDL/main.cpp
This pull request covers the SDL build only. So it helps with #501 but doesn't complete it, if this functionality is desired for the Mac as well.
Screenshots are saved to your home holder, with the format `clk-screenshot-X.bmp` where X is the lowest positive or zero number that can be used so as not to overwrite anything that already exists.
=> Adds screenshot saving upon ctrl+shift+d.

OSBindings/Mac/Clock Signal/Base.lproj/MainMenu.xib, OSBindings/Mac/Clock Signal/Clock Signal.entitlements, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm
Via command+shift+D (it's in the File menu). They'll turn up in your Pictures folder.
To complete #501, subject to testing.
=> Attempts to introduce screenshot capture for macOS.

OSBindings/SDL/main.cpp
Where available.
Resolves #501.
=> Use `xdg-user-dir PICTURES` instead of $HOME for screenshots

Analyser/Static/AppleII/Target.hpp, Components/DiskII/DiskII.cpp, Components/DiskII/DiskII.hpp, Machines/AppleII/AppleII.cpp, Machines/AppleII/AppleII.hpp, Machines/AppleII/Video.cpp, Machines/AppleII/Video.hpp, Machines/Utility/MachineForTarget.cpp, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.h, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, OSBindings/Mac/Clock Signal/MachinePicker/Base.lproj/MachinePicker.xib, OSBindings/Mac/Clock Signal/MachinePicker/MachinePicker.swift, ROMImages/AppleII/readme.txt, Storage/Disk/Drive.cpp
Also adjusts Disk II spin-down logic, resolving #509
=> Extends Apple II emulation to include the IIe

Analyser/Static/Coleco/StaticAnalyser.cpp, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm
=> Relaxes ColecoVision cartridge image size check

Inputs/Joystick.hpp, Machines/AppleII/AppleII.cpp
Of my go-to testing set, fixes Prince of Persia, Airheart and Donkey Kong. Zaxxon continues to work much as it ever did.
=> Significant improves Apple II joystick compatibility

Machines/AppleII/AppleII.cpp
Specifically:
* the double-high resolution switches should be read/write; and
* the other IIe-specific switches should cause a video update for real-time effect.
=> Fixes various IIe video deficiencies.

Storage/Disk/DiskImage/Formats/AppleDSK.cpp, Storage/Disk/Track/PCMSegment.cpp, Storage/Disk/Track/PCMSegment.hpp
=> Corrects Apple DSK track length, inter-track skew, and Pro-DOS volume number.

Machines/AppleII/AppleII.cpp
=> Adds mirrors for keyboard input and the audio toggle.

Machines/AppleII/Video.cpp, Machines/AppleII/Video.hpp
=> Corrects 40-column alternative text mode corruption

Machines/AppleII/AppleII.cpp, Machines/AppleII/Video.cpp, Machines/AppleII/Video.hpp
=> Implements the two undocumented annunciator 3 graphics modes

OSBindings/Mac/Clock Signal/Info.plist
=> Removes `LSItemContentTypes` so as not to reject files.

Machines/AppleII/Video.cpp, OSBindings/Mac/Clock SignalTests/6502InterruptTests.swift, OSBindings/SDL/main.cpp, Outputs/CRT/Internals/Shaders/IntermediateShader.cpp, Outputs/CRT/Internals/Shaders/OutputShader.cpp, Outputs/CRT/Internals/Shaders/Shader.cpp, Storage/Disk/DiskImage/Formats/NIB.cpp, Storage/FileHolder.cpp
Thereby resolves the colouration issue of #526 
Also makes a few code style fixes.
=> Corrects composition-time over-saturation.

Outputs/CRT/Internals/CRTOpenGL.cpp, Outputs/CRT/Internals/CRTOpenGL.hpp, Outputs/CRT/Internals/Shaders/OutputShader.cpp, Outputs/CRT/Internals/Shaders/OutputShader.hpp
=> Adds a left gutter to complement the right.

Machines/MSX/MSX.cpp
Now including mapping \n -> \r.
=> Simplifies and corrects MSX pasting behaviour.

Analyser/Static/Sega/StaticAnalyser.cpp, Analyser/Static/Sega/Target.hpp, Components/9918/9918.cpp, Components/9918/9918.hpp, Machines/MasterSystem/MasterSystem.cpp
Resolving #556 
Given that it's now detecting region and paging scheme, also implements PAL output and Japanese (i.e. BIOS-less) running modes.
=> Implements the Codemasters paging scheme

Components/9918/9918.cpp, OSBindings/Mac/Clock SignalTests/MasterSystemVDPTests.mm
=> Corrects residual Master System interrupt timing issues.

Analyser/Static/Sega/StaticAnalyser.cpp, Analyser/Static/Sega/Target.hpp, Components/9918/9918.cpp, Components/9918/Implementation/9918Base.hpp, Machines/MasterSystem/MasterSystem.cpp
Thereby fixes various minor segments of Codemasters games.
=> Separates request for an SMS2 VDP from current graphics mode.

Components/9918/9918.cpp
=> (Mostly) randomises the 9918 start position.

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/SDL/main.cpp, Outputs/OpenGL/Screenshot.hpp
=> Unifies the OpenGL screenshot code and corrects it for arbitrary alignment.

Analyser/Static/MSX/StaticAnalyser.cpp, Analyser/Static/MSX/Target.hpp, Machines/MSX/MSX.cpp, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.h, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, OSBindings/Mac/Clock Signal/MachinePicker/Base.lproj/MachinePicker.xib, OSBindings/Mac/Clock Signal/MachinePicker/MachinePicker.swift, ROMImages/MSX/readme.txt
With a caveat: the static analyser is very dumb.
=> Introduces region support to the MSX.

Components/AY38910/AY38910.cpp, Components/AY38910/AY38910.hpp
=> Implements proper AY IO output behaviour.

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, Outputs/DisplayMetrics.cpp, Outputs/DisplayMetrics.hpp, Outputs/OpenGL/Primitives/TextureTarget.cpp, Outputs/OpenGL/ScanTarget.cpp, Outputs/OpenGL/ScanTarget.hpp
So, specifically: if graphics output is too slow, scale down the quality of the output. In practice this is more or less restricted to composite processing, since that's the slow one.
Also produces an estimate of frame length and frame position, hopefully towards #341 (and, possibly, future beam racing?)
=> UNREADY! Introduces dynamic output quality selection.

Outputs/OpenGL/ScanTarget.cpp, Outputs/OpenGL/ScanTarget.hpp
This won't yet have any effect on either port owing to the way they handle contexts, but here it is.
=> Reduces draw/update contention.

OSBindings/Mac/Clock Signal/High Precision Timer/CSHighPrecisionTimer.h, OSBindings/Mac/Clock Signal/High Precision Timer/CSHighPrecisionTimer.m
For intended improvements to frame/emulator synchronisation.
=> Sketches a high-precision timer class.

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock Signal/Views/CSOpenGLView.m
No conversion to Swift 5 yet though; Xcode seems unhappy with the project.
=> Performs basic migration to Xcode 10.2.

Machines/MSX/MSX.cpp
=> Removes hard-coded assumption about disk ROM list placement.

OSBindings/SDL/SConstruct
Resolves #432
Fix suggested by MJBG in post https://github.com/TomHarte/CLK/issues/432#issuecomment-495964273
=> Adds recommended fix for 0xc3 in position 12 error.

ClockReceiver/ClockReceiver.hpp, Components/DiskII/IWM.hpp, Machines/Apple/Macintosh/Macintosh.cpp, Processors/68000/Implementation/68000Storage.cpp, Storage/Disk/Drive.cpp, Storage/Disk/Drive.hpp, Storage/Disk/Encodings/AppleGCR/Encoder.hpp, Storage/Storage.hpp
Primarily:
- to ensure proper positional continuity across speed rate changes; and
- to correct a few more generalised edge cases and precision issues.
=> Makes various fixes to `Drive` and `Track`.

Machines/Apple/Macintosh/Macintosh.cpp, Machines/Apple/Macintosh/Video.cpp
It now seems to me that these take effect immediately.
=> Removes the video and audio base address latches.

ClockReceiver/ClockReceiver.hpp, ClockReceiver/DeferredQueue.hpp, ClockReceiver/JustInTime.hpp, Components/6522/Implementation/6522Implementation.hpp, Machines/Apple/AppleII/AppleII.cpp, Machines/Apple/AppleII/Video.hpp, Machines/Apple/Macintosh/DeferredAudio.hpp, Machines/Apple/Macintosh/Macintosh.cpp, Machines/Atari2600/Bus.hpp, Machines/ColecoVision/ColecoVision.cpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/Electron/Electron.cpp, Machines/MSX/MSX.cpp, Machines/MasterSystem/MasterSystem.cpp, Machines/Oric/Oric.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme
... possibly slowly to discover the current limits of formalisation.
=> Starts to formalise just-in-time handling

Components/DiskII/MacintoshDoubleDensityDrive.cpp, Components/DiskII/MacintoshDoubleDensityDrive.hpp, Machines/Apple/Macintosh/DriveSpeedAccumulator.cpp, Machines/Apple/Macintosh/DriveSpeedAccumulator.hpp, Machines/Apple/Macintosh/Macintosh.cpp, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift
... while also adding more of the background wiring necessary to get emulated Macintosh 400kb drives working. One or two disks even work.
=> Resolves a potential crash at launch on the Mac

Components/DiskII/IWM.cpp, Components/DiskII/IWM.hpp, Components/DiskII/MacintoshDoubleDensityDrive.cpp, Inputs/Keyboard.hpp, Machines/AmstradCPC/Keyboard.cpp, Machines/Apple/AppleII/AppleII.cpp, Machines/Apple/Macintosh/Keyboard.cpp, Machines/Apple/Macintosh/Keyboard.hpp, Machines/Apple/Macintosh/Macintosh.cpp, Machines/Commodore/Vic-20/Keyboard.cpp, Machines/Electron/Keyboard.cpp, Machines/MSX/Keyboard.cpp, Machines/Oric/Keyboard.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/Mac/Clock Signal/Views/CSOpenGLView.h, OSBindings/Mac/Clock Signal/Views/CSOpenGLView.m, OSBindings/SDL/main.cpp
Specifically:
- adds indicator lights for drive activity; and
- adds instructions on how to release a captured mouse.
Also now maps in keypad keys to the Macintosh.
=> Improves Macintosh user communications

Machines/Apple/Macintosh/Macintosh.cpp
While introducing video-motivated RAM access delays.
=> Simplifies code around Mac bus decoding.

Machines/Apple/Macintosh/Macintosh.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.xcworkspace/contents.xcworkspacedata, OSBindings/Mac/Clock SignalTests/68000ArithmeticTests.mm, Processors/68000/Implementation/68000Implementation.hpp
It's not only 'long overflow' that I don't fully understand the timing of, I think. Whatever the cause is, it's outside the bounds of the process described in yacht.txt so more research is required.
=> Substantially improves DIVS timing.

ClockReceiver/JustInTime.hpp, Machines/Apple/Macintosh/DriveSpeedAccumulator.cpp, Machines/Apple/Macintosh/DriveSpeedAccumulator.hpp, Machines/Apple/Macintosh/Macintosh.cpp
Still preparatory to getting the Mac 128k and 512k working, hopefully.
=> Simplifies just-in-time usage of the IWM, and the disk-speed accumulator

Components/9918/Implementation/9918Base.hpp
Notable fixed titles: After Burner for the Master System.
=> Minor TMS timing correction.

Machines/Utility/MachineForTarget.cpp
=> Adds missing Master System option enumerations.

Machines/AmstradCPC/AmstradCPC.cpp, Outputs/OpenGL/ScanTarget.hpp
... by mapping a black border to the blank level.
=> Slightly improves CPC performance

Machines/AmstradCPC/AmstradCPC.cpp, OSBindings/Mac/Clock SignalTests/MacintoshVideoTests.mm, Outputs/OpenGL/ScanTarget.cpp
Also decreases risk of future error within the CPC.
=> Fixes unit test target

Analyser/Dynamic/MultiMachine/Implementation/MultiJoystickMachine.cpp, Analyser/Dynamic/MultiMachine/Implementation/MultiJoystickMachine.hpp, Components/6850/6850.cpp, Machines/AmstradCPC/AmstradCPC.cpp, Machines/Apple/AppleII/AppleII.cpp, Machines/Atari/2600/Atari2600.cpp, Machines/Atari/ST/AtariST.cpp, Machines/Atari/ST/IntelligentKeyboard.cpp, Machines/Atari/ST/IntelligentKeyboard.hpp, Machines/ColecoVision/ColecoVision.cpp, Machines/Commodore/Vic-20/Vic20.cpp, Machines/JoystickMachine.hpp, Machines/MSX/MSX.cpp, Machines/MasterSystem/MasterSystem.cpp, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/SDL/main.cpp
While introducing joysticks to the Atari ST and correcting one of the issues that is causing input sometimes not to be honoured.
=> Makes joysticks a little more const correct

.github/workflows/ccpp.yml
Specifically, for the Linux/SDL kiosk mode target. I think Xcode is also possible; will investigate later.
=> Adds continuous integration via GitHub actions.

ClockReceiver/ClockReceiver.hpp, Components/68901/MFP68901.cpp, Machines/Atari/ST/AtariST.cpp, Machines/Atari/ST/IntelligentKeyboard.cpp, Machines/Atari/ST/Video.cpp, Machines/Atari/ST/Video.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock SignalTests/AtariStaticAnalyserTests.mm, Processors/68000/Implementation/68000Storage.cpp
As well as adjusting joystick input better to map real joysticks to the ST.
=> Introduces a 28-cycle delay on DE propagation

Components/6850/6850.cpp, Components/6850/6850.hpp, Machines/Atari/ST/AtariST.cpp, Machines/Atari/ST/Video.cpp, Machines/Atari/ST/Video.hpp, Machines/Utility/MemoryPacker.cpp, Machines/Utility/MemoryPacker.hpp, OSBindings/Mac/Clock SignalTests/MasterSystemVDPTests.mm, Processors/68000/68000.hpp, Processors/68000/Implementation/68000Implementation.hpp, Storage/Disk/DiskImage/Formats/MSA.hpp
Specifically on optimisations:
* reduced unnecessary video flushing; and
* sought to reduce `.b` memory access cost.
Also corrects a 6850 reset bug that arose while testing.
=> ST: Adds some initial bus error logic, plus some optimisations.

Machines/Atari/ST/AtariST.cpp, Machines/Atari/ST/Video.cpp, Machines/Atari/ST/Video.hpp
Plus a delay between setting the output frequency and it taking effect, and various other timing improvements.
Resolves #684
=> Adds a delay on load following DE

Components/AY38910/AY38910.cpp, Components/AY38910/AY38910.hpp, Machines/AmstradCPC/AmstradCPC.cpp, Machines/Atari/ST/AtariST.cpp, Machines/ColecoVision/ColecoVision.cpp, Machines/MSX/MSX.cpp, Machines/Oric/Oric.cpp, Machines/ZX8081/ZX8081.cpp
i.e. like an AY, except with double-precision envelopes.
=> Adds explicit emulation of the YM2149F.

Components/68901/MFP68901.cpp, Machines/Atari/ST/AtariST.cpp, Machines/Atari/ST/DMAController.cpp, Machines/Atari/ST/Video.cpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, Storage/Disk/DiskImage/Formats/MSA.cpp, Storage/Disk/Encodings/MFM/Encoder.cpp
Resolves #681 , at least at the specific level rather than necessarily the generic.
=> Compacts gaps when necessary to fit more sectors.

OSBindings/Mac/Clock SignalTests/Bridges/DigitalPhaseLockedLoopBridge.mm, OSBindings/Mac/Clock SignalTests/Bridges/MOS6522Bridge.mm
Not part of the automated build yet, alas, owing to the limits on free build server time.
=> Corrects syntax errors in test suite.

Components/1770/1770.cpp, Components/1770/1770.hpp, Machines/Atari/ST/DMAController.cpp, Storage/Disk/Drive.cpp, Storage/Disk/Drive.hpp, Storage/Disk/Track/Track.hpp, Storage/TimedEventLoop.cpp, Storage/TimedEventLoop.hpp
Specifically based on the documentation of Jean Louis-Guérin and debugging New Zealand Story.
=> Corrects WD track-zero and write-protect flags.

Analyser/Static/Commodore/StaticAnalyser.cpp, Analyser/Static/Commodore/Target.hpp, Machines/Commodore/Vic-20/Vic20.cpp, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm
... and adds recognition of TheC64-style file tags to specify them.
Resolves #705
=> Permits Vic-20 memory to be specified in banks; 

Machines/Atari/ST/IntelligentKeyboard.cpp, Machines/Atari/ST/IntelligentKeyboard.hpp
This should fix Turrican due to the latter change; I'm not aware of software that uses the former.
=> Adds Joystick key code mode, ensures events aren't posted in interrogation mode.

OSBindings/Mac/Clock SignalTests/68000 Comparative Tests/readme.md
Also renames a file. But no code changes are currently suggested, at least until I can learn more about DIVU/DIVS.
=> After rerunning all tests, adds some notes on questionable results.

OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock SignalTests/68000 Comparative Tests/readme.md, OSBindings/Mac/Clock SignalTests/68000ComparativeTests.mm, Processors/68000/Implementation/68000Storage.cpp
I completely withdraw my earlier statement re: the test cases.
=> Fixes A7-relative JSRs.

Analyser/Static/Oric/StaticAnalyser.cpp, Analyser/Static/Oric/Target.hpp, Machines/Oric/Jasmin.cpp, Machines/Oric/Jasmin.hpp, Machines/Oric/Keyboard.cpp, Machines/Oric/Keyboard.hpp, Machines/Oric/Microdisc.cpp, Machines/Oric/Microdisc.hpp, Machines/Oric/Oric.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.h, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, OSBindings/Mac/Clock Signal/MachinePicker/Base.lproj/MachinePicker.xib, OSBindings/Mac/Clock Signal/MachinePicker/MachinePicker.swift
Albeit with a bit of guesswork. So it might or might not be accurate.
=> Adds emulation of the Oric's Jasmin disk interface.

Analyser/Static/Oric/StaticAnalyser.cpp, Analyser/Static/Oric/Target.hpp, Components/1770/1770.cpp, Components/1770/1770.hpp, Machines/Oric/BD500.cpp, Machines/Oric/BD500.hpp, Machines/Oric/DiskController.hpp, Machines/Oric/Jasmin.cpp, Machines/Oric/Jasmin.hpp, Machines/Oric/Microdisc.cpp, Machines/Oric/Microdisc.hpp, Machines/Oric/Oric.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.h, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, OSBindings/Mac/Clock Signal/MachinePicker/Base.lproj/MachinePicker.xib, OSBindings/Mac/Clock Signal/MachinePicker/MachinePicker.swift, ROMImages/Oric/readme.txt, Storage/Disk/DiskImage/Formats/OricMFMDSK.cpp, Storage/Disk/Drive.cpp, Storage/Disk/Drive.hpp
While also cleaning up such interface duplication as existed between the Microdisc and Jasmin.
=> Implements highly-provisional Byte Drive 500 support for the Oric.

Machines/Oric/BD500.cpp, Machines/Oric/DiskController.hpp, Machines/Oric/Jasmin.cpp, Machines/Oric/Microdisc.cpp, Storage/Disk/Drive.cpp, Storage/Disk/Drive.hpp
Also opts the BD-500 in for modified Shugart output. At a guess.
=> Adds emulation of non-default types of floppy drive RDY output

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme
Seemingly with no ill effects.
=> Opts in for the hardened macOS runtime.

Components/1770/1770.hpp, NumberTheory/LFSR.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, Storage/Disk/DiskImage/Formats/CPCDSK.cpp, Storage/Disk/DiskImage/Formats/STX.cpp, Storage/Disk/Encodings/MFM/Encoder.cpp, Storage/Disk/Encodings/MFM/Encoder.hpp, Storage/Disk/Track/PCMSegment.cpp, Storage/Disk/Track/PCMSegment.hpp
... in the sense of random.
Also adds population of fuzzy bits to the STX file format, and ensures it runs in from CPC-style DSKs.
=> Adds PCMSegementEventSource support for 'fuzzy' bits

Analyser/Dynamic/MultiMachine/Implementation/MultiSpeaker.cpp, Analyser/Dynamic/MultiMachine/Implementation/MultiSpeaker.hpp, Machines/CRTMachine.hpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/SDL/main.cpp, Outputs/Speaker/Implementation/LowpassSpeaker.hpp, Outputs/Speaker/Speaker.hpp
Exposed to SDL users only, for now.
=> Adds the option to run machines at a multiple of their real speeds.

ClockReceiver/DeferredQueue.hpp, ClockReceiver/JustInTime.hpp, Machines/Apple/AppleII/Video.hpp, Machines/Apple/Macintosh/Video.cpp, Machines/Atari/ST/AtariST.cpp, Machines/Atari/ST/Video.cpp, Machines/Atari/ST/Video.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal Kiosk.xcscheme, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock SignalTests.xcscheme, OSBindings/Mac/Clock Signal/High Precision Timer/CSHighPrecisionTimer.h, OSBindings/Mac/Clock SignalTests/AtariSTVideoTests.mm, Outputs/CRT/CRT.cpp, Outputs/CRT/CRT.hpp, Storage/Disk/DPLL/DigitalPhaseLockedLoop.hpp
This support is not currently exposed. I'm starting to consider whether there might not be a better way to implement this thing.
=> Adds some amount of 1bpp/72Hz output support for the Atari ST.

ClockReceiver/ScanSynchroniser.hpp, ClockReceiver/TimeTypes.hpp, Machines/Commodore/Vic-20/Vic20.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal Kiosk.xcscheme, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/SDL/main.cpp
Attempts simultaneously to reduce latency, but there's only so much that can be done here. SDL just doesn't provide the tools.
=> Introduces sync matching to the SDL version.

Analyser/Dynamic/MultiMachine/Implementation/MultiCRTMachine.cpp, Components/6560/6560.cpp, Components/AY38910/AY38910.cpp, Components/AudioToggle/AudioToggle.cpp, Components/KonamiSCC/KonamiSCC.cpp, Machines/Apple/AppleII/Video.cpp, Machines/Apple/AppleII/Video.hpp, Machines/Apple/Macintosh/Audio.cpp, Machines/Atari/2600/TIASound.cpp, Machines/Atari/ST/Video.cpp, Machines/Electron/SoundGenerator.cpp, OSBindings/Mac/Clock SignalTests/68000ComparativeTests.mm
=> Tries to be less lazy with lambda captures.

Machines/AmstradCPC/AmstradCPC.cpp, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, Outputs/OpenGL/ScanTarget.cpp, Outputs/OpenGL/ScanTarget.hpp, Outputs/Speaker/Implementation/LowpassSpeaker.hpp, Outputs/Speaker/Speaker.hpp, Storage/Disk/Drive.hpp
On the hunt for whatever is causing trouble for the CPC, but of non-generic form otherwise.
=> Resolves a variety of potential startup data races.

Machines/AmstradCPC/AmstradCPC.cpp, Outputs/OpenGL/ScanTarget.cpp
So far without uncovering anything.
=> Throws in additional asserts.

Analyser/Dynamic/MultiMachine/Implementation/MultiKeyboardMachine.cpp, Analyser/Dynamic/MultiMachine/Implementation/MultiKeyboardMachine.hpp, Inputs/Keyboard.cpp, Inputs/Keyboard.hpp, Machines/AmstradCPC/Keyboard.cpp, Machines/Apple/AppleII/AppleII.cpp, Machines/Electron/Electron.cpp, Machines/Electron/Keyboard.cpp, Machines/KeyboardMachine.cpp, Machines/KeyboardMachine.hpp, Machines/MasterSystem/MasterSystem.cpp, Machines/ZX8081/Keyboard.cpp, Machines/ZX8081/Keyboard.hpp, Machines/ZX8081/ZX8081.cpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm
Also, virtual ZX80 keys for cursors and edit.
=> Adds better guesses for unmapped physical keys.

Analyser/Dynamic/MultiMachine/Implementation/MultiSpeaker.cpp, Analyser/Dynamic/MultiMachine/Implementation/MultiSpeaker.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal Kiosk.xcscheme, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock Signal/Base.lproj/MachineDocument.xib, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/Mac/Clock Signal/Views/CSOpenGLView.h, OSBindings/Mac/Clock Signal/Views/CSOpenGLView.m, OSBindings/SDL/main.cpp, Outputs/Speaker/Implementation/LowpassSpeaker.hpp, Outputs/Speaker/Speaker.hpp
Because I've chosen to use image assets provided for touchbars in macOS, this bumps the minimum supported version to v10.12.2.
=> Adds output volume control.

Machines/MasterSystem/MasterSystem.cpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal Kiosk.xcscheme, OSBindings/SDL/main.cpp
=> Show CRC32s of missing ROMs.

Analyser/Static/DiskII/StaticAnalyser.cpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, Storage/Disk/DiskImage/Formats/NIB.cpp, Storage/Disk/Encodings/AppleGCR/Encoder.hpp, Storage/Disk/Encodings/AppleGCR/SegmentParser.cpp
While also making a first attempt at 5 & 3 decoding.
=> Resolves a potential crash with NIB files

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/SDL/SConstruct, Processors/6502/6502.hpp, Processors/6502/Implementation/6502Base.cpp, Processors/6502/Implementation/6502Implementation.hpp, Processors/6502/Implementation/6502Storage.hpp, Processors/6502/State/State.cpp, Processors/6502/State/State.hpp
I'm still experimenting with style here; I think something like this is probably the way to proceed with other components?
=> Makes `State`, and therefore the 'Reflection' dependency, an optional adjunct to the 6502.

Packaging/README.md, Packaging/main.yml, Packaging/templates/clksignal.1.j2, Packaging/templates/package.spec.j2
- add Ansible build playbook to create RPM package (tested on Fedora 32)
- create basic man page
=> Create RPM package and man page

Analyser/Dynamic/MultiMachine/Implementation/MultiJoystickMachine.cpp, Components/9918/Implementation/9918Base.hpp, Inputs/Joystick.hpp, Inputs/Keyboard.hpp, Machines/Atari/2600/Atari2600.cpp, Machines/KeyboardMachine.hpp, Machines/MasterSystem/MasterSystem.cpp, Outputs/CRT/CRT.hpp, Processors/68000/68000.hpp, Processors/68000/Implementation/68000Storage.hpp
While continuing to apply a little more const care.
=> Ensures the Master System makes a genuine attempt to boot sans BIOS

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal.xcodeproj/project.xcworkspace/contents.xcworkspacedata, OSBindings/SDL/SConstruct, Processors/6502/Implementation/6502Storage.hpp, Processors/6502/State/State.cpp, Processors/Z80/Implementation/Z80Storage.hpp, Processors/Z80/State/State.cpp, Processors/Z80/State/State.hpp, Reflection/Struct.cpp
As with the 6502, this is a very early part of the ongoing effort towards state snapshots and subsequently possibly a debugger.
=> Adds reflective state for the Z80.

Analyser/Dynamic/MultiMachine/Implementation/MultiConfigurable.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/SDL/SConstruct, Processors/6502/State/State.hpp, Processors/68000/Implementation/68000Implementation.hpp, Processors/68000/Implementation/68000Storage.cpp, Processors/68000/Implementation/68000Storage.hpp, Processors/68000/State/State.cpp, Processors/68000/State/State.hpp, Reflection/Struct.cpp, Reflection/Struct.hpp
in pursuit of which it also adds knowledge of C-style arrays to my little version of declarative reflection. Vectors should just work, though `Struct::description()` isn't smart enough to parse them yet. I think I'll have to decline to support `std::array` since what amounts to guess-and-check on types would be somewhat arduous.
=> Adds a `State` for the 68000.

Analyser/Dynamic/MultiMachine/Implementation/MultiConfigurable.cpp, Reflection/Struct.cpp, Reflection/Struct.hpp
It's not ideal, but I think it's probably better than coming up with my own format.
Further serialisation rules may be required, I'll figure it out if and when.
=> Adds BSON serialisation and deserialisation for all reflectable structs.

OSBindings/Qt/ClockSignal.pro, OSBindings/Qt/mainwindow.cpp, OSBindings/Qt/mainwindow.h
Also introduces to Qt the ability to use a keyboard as a joystick.
=> Works around Qt's keyboard limitations, under X11 at least

OSBindings/Qt/mainwindow.cpp, OSBindings/Qt/mainwindow.h
As a status bar, which is a bit of a quick fix, but it's better than not displaying this information.
=> Exposes activity lights in Qt.

Machines/ZX8081/ZX8081.cpp
=> Ensures the ZX80 and ZX81 automatically RUN software that doesn't do that itself

Components/DiskII/DiskII.cpp, Machines/Apple/AppleII/DiskIICard.cpp, Storage/Disk/Disk.hpp, Storage/Disk/DiskImage/DiskImage.hpp, Storage/Disk/DiskImage/DiskImageImplementation.hpp, Storage/Disk/DiskImage/Formats/WOZ.cpp, Storage/Disk/DiskImage/Formats/WOZ.hpp, Storage/Disk/Drive.cpp, Storage/Disk/Encodings/AppleGCR/Sector.hpp, Storage/Disk/Encodings/AppleGCR/SegmentParser.cpp, Storage/Disk/Track/PCMSegment.cpp, Storage/Disk/Track/PCMSegment.hpp, Storage/Disk/Track/PCMTrack.cpp, Storage/Disk/Track/PCMTrack.hpp, Storage/Disk/Track/Track.hpp, Storage/Disk/Track/TrackSerialiser.cpp, Storage/Disk/Track/UnformattedTrack.cpp, Storage/Disk/Track/UnformattedTrack.hpp, Storage/TimedEventLoop.cpp, Storage/TimedEventLoop.hpp
Also definitively switches seek logic for drives to floating point and marks WOZs as read-only.
=> Corrects a regression in disk image handling; liberalises Disk II analyser

Machines/Apple/Macintosh/Audio.cpp, Machines/Apple/Macintosh/Audio.hpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, Outputs/OpenGL/ScanTarget.cpp, Outputs/OpenGL/ScanTarget.hpp, Outputs/OpenGL/ScanTargetGLSLFragments.cpp, Outputs/ScanTargets/BufferingScanTarget.cpp, Outputs/ScanTargets/BufferingScanTarget.hpp
... with parts erroneously left out of #817
=> Completes LockFreeQueue branch.

Analyser/Dynamic/MultiMachine/Implementation/MultiSpeaker.cpp, Analyser/Dynamic/MultiMachine/Implementation/MultiSpeaker.hpp, Outputs/Speaker/Implementation/LowpassSpeaker.hpp, Outputs/Speaker/Speaker.hpp
=> Restores audio to multimachines

Outputs/Speaker/Implementation/LowpassSpeaker.hpp
Specifically due to the lingering use of integer logic despite relevant values now being floating point.
I suspect that this fully resolves #786 (albeit that the issue was already mostly resolved).
=> Resolves lowpass-speaker position aliasing

Components/6522/Implementation/6522Implementation.hpp
This is the first, fledgling result of investigating #805
=> Corrects a couple of minor VIA timer issues

Components/6522/6522.hpp, Components/6522/Implementation/6522Implementation.hpp, Components/6522/Implementation/6522Storage.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock SignalTests/6522Tests.swift, OSBindings/Mac/Clock SignalTests/PCMSegmentEventSourceTests.mm, OSBindings/Mac/Clock SignalTests/PCMTrackTests.mm
=> Further improves 6522 emulation.

OSBindings/Qt/mainwindow.cpp, OSBindings/Qt/scantargetwidget.cpp, OSBindings/Qt/scantargetwidget.h
=> Adds F8+F12 as an alternative mouse-release combo for Qt.

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/MachinePicker/Base.lproj/MachinePicker.xib, OSBindings/Mac/Clock Signal/ROMRequester/ROMRequester.xib
This plus a rebuild appears to resolve #848 
And let's hope that building for M1 will be just as problem-free.
=> Slightly tweaks machine picker for macOS Big Sur.

Outputs/OpenGL/ScanTargetGLSLFragments.cpp
This fixes the video part of #852
=> Avoids all risk of infinities when there is no colour burst

Components/DiskII/DiskII.cpp
=> Ensure proper in-memory ordering of the b72a2c70 ROM.

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Base.lproj/MachineDocument.xib, OSBindings/Mac/Clock Signal/CSApplication.h, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser+TargetVector.h, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.h, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, OSBindings/Mac/Clock Signal/MachinePicker/MachinePicker.swift, OSBindings/Mac/Clock Signal/ROMRequester/CSROMReceiverView.h
Use synthesized properties for CSMissingROM.
Remove openGLView from the xib: that will quiet a warning.
Add nullability metadata to CSStaticAnalyser.
=> Madd's improvements

OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.h, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, OSBindings/Mac/Clock Signal/MachinePicker/Base.lproj/MachinePicker.xib, OSBindings/Mac/Clock Signal/MachinePicker/MachinePicker.swift, OSBindings/Qt/mainwindow.cpp, OSBindings/Qt/mainwindow.ui
Both the Qt and Cocoa UIs are suitably modified.
=> Adds UI for the new Electron configuration options.

InstructionSets/Sizes.hpp
This PR fixes compilation on GCC 10.
=> Fix compilation on GCC 10

Analyser/Static/AmstradCPC/StaticAnalyser.cpp, Machines/AmstradCPC/AmstradCPC.cpp, Machines/AmstradCPC/AmstradCPC.hpp, Numeric/CRC.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, Storage/Tape/Parsers/Acorn.cpp, Storage/Tape/Parsers/Acorn.hpp, Storage/Tape/Parsers/Commodore.cpp, Storage/Tape/Parsers/Commodore.hpp, Storage/Tape/Parsers/Oric.cpp, Storage/Tape/Parsers/Oric.hpp, Storage/Tape/Parsers/Spectrum.cpp, Storage/Tape/Parsers/Spectrum.hpp, Storage/Tape/Parsers/TapeParser.hpp, Storage/Tape/Parsers/ZX8081.cpp, Storage/Tape/Parsers/ZX8081.hpp, Storage/Tape/Tape.cpp, Storage/Tape/Tape.hpp
Since they share something of a physical encoding with the ZX Spectrum, the parser is named that way and I've attempted to keep it open enough to parse either.
I have the feeling that possibly the Enterprise uses the same encoding again, it being a minor temporary de facto standard, but would have to do more research on that.
=> Slightly Improves CPC tape loading times

Components/9918/Implementation/9918Base.hpp
=> Tweak Master System blue scale.

Analyser/Static/StaticAnalyser.cpp, Machines/Apple/AppleIIgs/Video.cpp, Machines/Sinclair/Keyboard/Keyboard.cpp, Machines/Sinclair/ZXSpectrum/Video.hpp, Machines/Sinclair/ZXSpectrum/ZXSpectrum.cpp, Machines/Utility/Typer.cpp, Machines/Utility/Typer.hpp
Resolves #889 to my current comprehension; strikes one from #808
=> Adds Spectrum polish

Machines/Sinclair/ZXSpectrum/Video.hpp, Machines/Sinclair/ZXSpectrum/ZXSpectrum.cpp
As per http://sky.relative-path.com/zx/floating_bus.html
Resolves #891
=> Attempts to implement proper floating bus behaviour.

README.md
This was evidently unclear, as per #899
=> Clarifies the object in the 'Single-click Loading' readme section

ClockReceiver/JustInTime.hpp, Machines/Apple/Macintosh/Macintosh.cpp, Machines/Sinclair/ZXSpectrum/ZXSpectrum.cpp
Also gives it the ability to determine `TargetTimeScale` automatically.
=> Works `ClockingHint` logic into `JustInTimeActor`.

Machines/Sinclair/ZX8081/ZX8081.hpp, Machines/Sinclair/ZXSpectrum/ZXSpectrum.cpp, Machines/Sinclair/ZXSpectrum/ZXSpectrum.hpp, Machines/Utility/MachineForTarget.cpp
Also ties down interrupt response, fixing some software.
=> Adds display of Spectrum command-line options.

Components/6850/6850.cpp, Components/68901/MFP68901.cpp, Machines/Atari/ST/DMAController.cpp
=> Resolves failure of ST to startup

Machines/Sinclair/ZXSpectrum/Video.hpp, Machines/Sinclair/ZXSpectrum/ZXSpectrum.cpp
The better for verification and testing.
=> Attempts more cleanly to express ZX Spectrum timing.

Analyser/Static/StaticAnalyser.cpp, Components/AY38910/AY38910.hpp, Machines/Sinclair/ZXSpectrum/State.hpp, Machines/Sinclair/ZXSpectrum/Video.hpp, Machines/Sinclair/ZXSpectrum/ZXSpectrum.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Info.plist, Storage/State/SZX.cpp, Storage/State/SZX.hpp, Storage/State/Z80.cpp
Tweaking exposed Spectrum state object as relevant.
=> Adds SZX support.

Machines/Oric/Oric.cpp
Thereby hits the number one interface mentioned in #822
=> Adds Altai-style joystick support for the Oric.

Machines/Apple/ADB/Keyboard.cpp, Machines/Sinclair/Keyboard/Keyboard.cpp, Machines/Sinclair/ZXSpectrum/ZXSpectrum.cpp, Reflection/Struct.hpp
Primarily lack of annotations.
=> Correct minor style errors.

Machines/Apple/AppleII/AppleII.cpp, Machines/Apple/AppleII/AppleII.hpp, Machines/Apple/AppleII/Video.cpp, Machines/Apple/AppleII/Video.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal Kiosk.xcscheme, OSBindings/Mac/Clock Signal/Base.lproj/AppleIIOptions.xib, OSBindings/Mac/Clock Signal/Base.lproj/Atari2600Options.xib, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSAppleII.h, OSBindings/Mac/Clock Signal/Machine/Wrappers/CSAppleII.mm, OSBindings/Qt/mainwindow.cpp, OSBindings/Qt/mainwindow.h
Pending: exposure within Qt.
Resolves #945
=> Adds optional square pixel output for the Apple II

Inputs/Joystick.hpp, Inputs/Keyboard.cpp, Machines/Utility/MemoryPacker.cpp, Processors/65816/65816.hpp, SignalProcessing/FIRFilter.cpp
As reported by @iss000 in #943
=> Add missing stddef header where size_t is used.

Analyser/Static/Enterprise/StaticAnalyser.cpp, Machines/Enterprise/Enterprise.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, Storage/Disk/Parsers/FAT.cpp, Storage/Disk/Parsers/FAT.hpp
Uses it to make a decision as to how to handle Enterprise disk startup.
=> Adds a FAT12 parser.

Machines/Enterprise/Enterprise.cpp, Machines/Enterprise/Enterprise.hpp, Machines/Enterprise/Nick.cpp, Machines/Enterprise/Nick.hpp, Machines/Utility/MachineForTarget.cpp, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, OSBindings/Qt/mainwindow.cpp
While enabling more pixels on the left for RGB mode.
=> Adds Enterprise composite video option.

Machines/Enterprise/Dave.cpp, Machines/Enterprise/Dave.hpp, Machines/Enterprise/Nick.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock SignalTests/EnterpriseDaveTests.mm
Though I suspect issues are still lurking.
=> Correct various Enterprise timing discrepancies.

Machines/Enterprise/Dave.hpp, Machines/Enterprise/EXDos.cpp, Machines/Enterprise/Enterprise.cpp, Machines/Enterprise/Nick.cpp, Machines/Enterprise/Nick.hpp
While also cleaning up in general.
=> Makes a guess re: the Enterprise floating bus

Machines/Enterprise/Enterprise.cpp, Machines/Enterprise/Nick.hpp, OSBindings/Qt/mainwindow.cpp
(Along with other minor tweaks to address issues identified by the version of Clang currently shipping with Qt)
=> Ensure LEDs are cleared between machines in Qt.

Analyser/Static/Enterprise/Target.hpp, Machines/Enterprise/Enterprise.cpp, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.h, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, OSBindings/Mac/Clock Signal/MachinePicker/Base.lproj/MachinePicker.xib, OSBindings/Mac/Clock Signal/MachinePicker/MachinePicker.swift, OSBindings/Qt/mainwindow.cpp, OSBindings/Qt/mainwindow.ui
Primarily to provide more data collection on the speed issues affecting some software.
=> Adds the option of running an Enterprise at 6MHz.

Activity/Observer.hpp, OSBindings/Mac/Clock Signal/Base.lproj/Activity.xib, OSBindings/Mac/Clock Signal/Base.lproj/MacintoshOptions.xib, OSBindings/Mac/Clock Signal/Base.lproj/MainMenu.xib, OSBindings/Mac/Clock Signal/Base.lproj/QuickLoadOptions.xib, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift
Some recidivism may be on the cards, but for now this resolves #964
=> Converts activity indicators to transient in-window presentation.

Machines/Apple/AppleII/AppleII.cpp
Hi -
This morning I decided I wanted to try doing some BASIC and assembly coding with CLK's Apple ][ emulator but was frustrated to find that I couldn't even get from the monitor into BASIC. You're supposed to do this by pressing Ctrl+B followed by Return, but the SDL "logical keyboard" seemed to behave strangely with the ctrl key - it basically didn't work, as far as I could tell. With a bit of hacking I managed to get it working by disabling the logical keyboard and making some straightforward changes to the AppleII machine's `set_key_pressed`, but without the logical keyboard neither Shift nor Space worked. Moreover, `set_key_pressed` was clearly written with the Apple ][e in mind - it doesn't hesitate to put $c000 (the keyboard register) into states that simply couldn't exist on the …
=> Improve raw keyboard handling for original Apple ][

OSBindings/Mac/Clock Signal/ScanTarget/ScanTarget.metal
=> Increase precision of phase interpolation.

OSBindings/Mac/Clock Signal/MachinePicker/Base.lproj/MachinePicker.xib
=> macOS: cleans up layout of machine picker.

Machines/Amiga/Amiga.cpp, Machines/Amiga/Chipset.cpp, Machines/Amiga/Chipset.hpp, Machines/Amiga/Copper.cpp, OSBindings/Mac/Clock Signal/Base.lproj/MainMenu.xib
Still doesn't appear to pass the relevant parts of vAmigaTS however.
=> Amiga: regularises timing; improves Copper sleep/wait costs

Machines/Amiga/Chipset.cpp, Machines/Amiga/Chipset.hpp, Machines/Amiga/Copper.cpp
It adds an extra conditional, alas, but as a side effect it makes code slightly cleaner easier for the Copper.
=> Ensures Chipset reads can map to writes and vice versa.

Analyser/Static/Amiga/Target.hpp, Machines/Amiga/Amiga.cpp, Machines/Amiga/MemoryMap.hpp, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.h, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, OSBindings/Mac/Clock Signal/MachinePicker/Base.lproj/MachinePicker.xib, OSBindings/Mac/Clock Signal/MachinePicker/MachinePicker.swift, OSBindings/Qt/mainwindow.cpp, OSBindings/Qt/mainwindow.ui
=> Adds fast RAM to the Amiga, along with size selection for both fast & chip.

Processors/68000/Implementation/68000Implementation.hpp, Processors/68000/Implementation/68000Storage.cpp, Processors/68000/Implementation/68000Storage.hpp
Along with increased name-and-shame on table sizes.
=> Minor 68000 style improvements.

Machines/Amiga/Chipset.cpp, Machines/Amiga/Chipset.hpp
i.e. the values which define the Amiga's horizontal graphics data fetch window.
=> Improve application of DDFSTRT and DDFSTOP.

Machines/AmstradCPC/AmstradCPC.cpp
=> CPC: ensure 64/128k RAM is properly selected.

Machines/Apple/AppleII/AuxiliaryMemorySwitches.hpp
=> Undo bad guess at initial switch state.

Machines/Apple/AppleII/AppleII.cpp, Storage/Disk/DiskImage/Formats/AcornADF.cpp, Storage/Disk/DiskImage/Formats/FAT12.cpp, Storage/Disk/DiskImage/Formats/MacintoshIMG.cpp, Storage/Disk/DiskImage/Formats/MacintoshIMG.hpp, Storage/Disk/DiskImage/Formats/NIB.cpp, Storage/Disk/DiskImage/Formats/Utility/ImplicitSectors.cpp, Storage/Disk/Track/PCMSegment.cpp, Storage/Disk/Track/PCMTrack.cpp
=> Eliminate `off_t`.

Processors/68000Mk2/68000Mk2.hpp
To emphasise: the overwhelming point here is cleanliness. There's no difference in generated code.
=> Clean up Microcycle helpers.

Processors/6502/AllRAM/6502AllRAM.cpp, Processors/6502Esque/6502Selector.hpp
=> Add an automatic bus size selector.

Machines/Amiga/Amiga.cpp, Machines/Amiga/Chipset.cpp, Machines/Amiga/Chipset.hpp, Machines/Amiga/MemoryMap.hpp, Processors/68000Mk2/Implementation/68000Mk2Implementation.hpp
Much like the ST branch, this doesn't function as it did before, so will provide more fodder for testing the new 68000.
=> Switch the Amiga to the newer 68000.

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj
=> Ensure macOS releases contain an updated version number.

Concurrency/AsyncTaskQueue.hpp, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm
=> Resolve crash of machines that require the ROM requester under macOS.

OSBindings/Mac/Clock Signal/ScanTarget/ScanTarget.metal
So that the Metal backend tracks #1088
=> Incorporate new additional padding.

Storage/Disk/DiskImage/Formats/AppleDSK.cpp, Storage/Disk/Encodings/AppleGCR/Encoder.cpp, Storage/Disk/Encodings/AppleGCR/SegmentParser.cpp
=> Resolve off-by-one error in Apple II sector decoding.

InstructionSets/M68k/Executor.hpp, InstructionSets/M68k/Implementation/ExecutorImplementation.hpp
Noting that I don't have test material at this time, so this may end up needing to be revisited.
=> Support 68020+ long extensions.

OSBindings/Mac/Clock Signal/Machine/CSMachine.mm
This restores culling of abandoned parallel machines during dynamic analysis.
=> Restore repeated lookup of timed machine under macOS.

Components/RP5C01/RP5C01.cpp, Components/RP5C01/RP5C01.hpp, Numeric/NumericCoder.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj
I think this will leave 'only' the V9938 as a missing MSX 2 component.
This pull request omits the alarm functionality but attempts to provide meaningful getters and setters for the real-time clock, which is seeded according to your computer's clock.
=> More fully implement the RP-5C01.

InstructionSets/6809/OperationMapper.hpp, OSBindings/Mac/Clock SignalTests/6809OperationMapperTests.mm, Reflection/Dispatcher.hpp
Just a pleasant distraction, for now.
=> Add experimental 6809 opcode decoder.

Processors/65816/Implementation/65816Implementation.hpp
As per https://github.com/TomHarte/ProcessorTests/issues/25
=> 65816: Fix perceived S in emulated stack-relative mode.

Processors/65816/Implementation/65816Implementation.hpp, Processors/65816/Implementation/65816Storage.cpp
Cf. https://github.com/TomHarte/ProcessorTests/issues/24
=> 65816: Fix test (and commentary) for shortened emulated branches.

Components/9918/Implementation/9918.cpp
This pull request fixes Space Manbow, amongst others.
=> Restrict disabled MSX line interrupt signalling.

Processors/65816/Implementation/65816Implementation.hpp, Processors/65816/Implementation/65816Storage.cpp
Cf. https://github.com/TomHarte/ProcessorTests/issues/44
=> Add a between-instructions enforcement of SH = 1.

InstructionSets/M50740/Executor.cpp, InstructionSets/M50740/Executor.hpp, Machines/Apple/AppleIIgs/ADB.cpp
The mouse is now polled more than ~3 times/second, giving a fully interactive GS/OS (other than the keyboard).
=> Add basic ADB controller interrupts.

Machines/Apple/ADB/Keyboard.cpp, Machines/Apple/ADB/Keyboard.hpp
Seems to bring proper behaviour in GS/OS but not yet in BASIC.
=> Avoid flurry of startup events, repeats.

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj
Resolves #1143 and resolves #1118 (hopefully).
=> Add manual rpath for macOS 10.13.

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock SignalTests/Bridges/TestMachine6502.h, OSBindings/Mac/Clock SignalTests/Bridges/TestMachine6502.mm, OSBindings/Mac/Clock SignalTests/NeskellTests.swift, Processors/6502/6502.hpp, Processors/6502/Implementation/6502Implementation.hpp
Incorporating relevant Neskell tests to verify.
=> 6502: fix SH[S/X/Y/A]

Machines/Apple/AppleII/Video.hpp
This fixes the Apple II/II+/IIe floating bus issues I reported in #1180 and #1181.
=> Fix Apple II/II+/IIe floating bus issues

InstructionSets/x86/Flags.hpp, InstructionSets/x86/Implementation/PerformImplementation.hpp, InstructionSets/x86/Perform.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock SignalTests/8088Tests.mm
Purely clerical; not much to see here.
=> Commute: Status -> Flags as per usual x86 naming.

InstructionSets/x86/Implementation/BCD.hpp, InstructionSets/x86/Implementation/PerformImplementation.hpp, OSBindings/Mac/Clock SignalTests/8088Tests.mm
I strongly suspect I'm not going to be able to figure out AAM 0, which is undocumented behaviour on the 8086.
=> Correct 8086 DAA and DAS; unify those and AAA/AAS.

Machines/PCCompatible/DMA.hpp, Machines/PCCompatible/PCCompatible.cpp, Machines/PCCompatible/PIC.hpp, Machines/PCCompatible/PIT.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj
Lashes together enough of the PPI, DMA and PIT to get GLaBIOS to output via MDA its complete memory test and then fail only at the keyboard and FDC.
Likely next pull request: get some graphics output.
---
Specifically, the following text is the final set left in the MDA display area:
```
GLaBIOS [] The hero we need but don't deserve                                  
(C) 2022-23 640KB Released under GPLv3                                          
Boot   [ COLD ]                                                                 
RAM    [ 640 KB OK ]            Video  [ Mono ]                                 
CPU    [ 8088 ]                 FPU    [ None ]                                 
LPT    [ None ]                 COM    [ None ]                                 
FDD    [ 0 ] …
```
=> Add various other PC chips into the mix.

Machines/PCCompatible/PCCompatible.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/MachinePicker/MachinePicker.swift
Also: 
* implement PC speaker audio;
* allow the PC and IIgs permanently to show in macOS debug builds.
=> Standardise on the PIT clock as the definition of time.

Machines/PCCompatible/PCCompatible.cpp
Primarily by being overt in code about what is ignored.
=> Limit extraneous printing.

Components/68901/MFP68901.cpp, Components/68901/MFP68901.hpp, Machines/Amiga/Amiga.cpp, Machines/Apple/Macintosh/Macintosh.cpp, Machines/Atari/ST/AtariST.cpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, Processors/68000/68000.hpp, Processors/68000/Implementation/68000Implementation.hpp, Processors/68000/Implementation/68000Storage.hpp
Plus some minor ST-focussed optimisations. Nothing earth shattering.
It's likely the 68000 could be specific in a lot more places than currently; this potentially opens the floodgates on rolling improvements.
=> Sometimes provide 68000 bus operations at compile time.

Machines/PCCompatible/DMA.hpp, Machines/PCCompatible/KeyboardMapper.hpp, Machines/PCCompatible/PCCompatible.cpp
Which gets me into MS-DOS 3.21, amongst others.
=> Improves 8237 TC/EOP support enough for some multisector reads

Machines/PCCompatible/DMA.hpp, Machines/PCCompatible/Memory.hpp
=> Add missing <array> #includes

OSBindings/Mac/Clock Signal/Info.plist
=> Remove invalid uef.gz file type from Info.plist

Components/6845/CRTC6845.hpp, Machines/PCCompatible/PCCompatible.cpp
I'm pretty sure this completes the MDA video adaptor.
=> MDA: implement no cursor, blink attribute.

Components/8272/Status.hpp, Machines/PCCompatible/PCCompatible.cpp
At least, for now, asserting that all disks are read-only.
=> Respond appropriately if a write is attempted.

Analyser/Static/PCCompatible/Target.hpp, Machines/PCCompatible/CGA.hpp, Machines/PCCompatible/MDA.hpp, Machines/PCCompatible/PCCompatible.cpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.h, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, OSBindings/Mac/Clock Signal/MachinePicker/Base.lproj/MachinePicker.xib, OSBindings/Mac/Clock Signal/MachinePicker/MachinePicker.swift
This is as much about giving me something to profile with AT-style load as about user experience; I've yet to have complete thoughts on how it should factor in to static or dynamic analysis.
=> Add turbo option for PC execution.

Components/DiskII/DiskII.cpp, Storage/Disk/DiskImage/Formats/NIB.cpp, Storage/Disk/DiskImage/Formats/NIB.hpp
=> NIB: switch to a strategy supporting non-standard formats.

Machines/Apple/AppleII/Video.hpp
=> Don't disable the colour burst in mixed mode.

Processors/6502/Implementation/6502Implementation.hpp, Processors/6502/Implementation/6502Storage.cpp, Processors/6502/Implementation/6502Storage.hpp
Resolves #1211
Full list of required modifications:
=> Adjust 65c02 STA abs,x behaviour.

OSBindings/Qt/clksignal.pro, OSBindings/Qt/mainwindow.cpp, OSBindings/Qt/mainwindow.h, OSBindings/Qt/mainwindow.ui, OSBindings/Qt/scantargetwidget.cpp
At the same time, adding the PC as a configurable new machine.
=> Update to Qt 6.

OSBindings/Qt/clksignal.pro, OSBindings/Qt/mainwindow.cpp, OSBindings/Qt/mainwindow.h, OSBindings/Qt/mainwindow.ui
Now alongside Qt6 support, and purely because trying to get a working Snapcraft built against Qt6 proves to be near-impossible.
=> Reintroduce Qt5 support.

Analyser/Dynamic/MultiMachine/Implementation/MultiKeyboardMachine.cpp, Analyser/Dynamic/MultiMachine/Implementation/MultiKeyboardMachine.hpp, Inputs/Keyboard.cpp, Inputs/Keyboard.hpp, Machines/Apple/AppleII/AppleII.cpp, Machines/KeyboardMachine.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Machine/CSMachine.h, OSBindings/Mac/Clock Signal/Machine/CSMachine.mm, OSBindings/Qt/mainwindow.cpp, OSBindings/SDL/main.cpp
Resolves #1290.
Mild deviation from the real Apple II: your host machine's key repeat rate is used.
=> Indicate whether a keypress is a repeat. Treat appropriately in the Apple II.

Components/6845/CRTC6845.hpp, Machines/AmstradCPC/AmstradCPC.cpp, Machines/PCCompatible/CGA.hpp, Machines/PCCompatible/MDA.hpp
While adding an EGA type, though all it does is expand refresh addressing to 16-bit for now.
=> Make CRTC model part of type.

Machines/Electron/Electron.cpp
=> Don't page if acknowleding interrupts.

Machines/Apple/AppleIIgs/AppleIIgs.cpp, Machines/Apple/AppleIIgs/MemoryMap.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock SignalTests/EmuTOSTests.mm, OSBindings/Mac/Clock SignalTests/IIgsMemoryMapTests.mm, OSBindings/Mac/Clock SignalTests/QLTests.mm, OSBindings/Mac/Clock SignalTests/TestRunner68000.hpp
While also fixing the test target.
No progress on the immediate issue I was investigating though; this does not improve IIgs emulation.
=> Normalise IIgs memory map interface.

Machines/Apple/AppleIIgs/AppleIIgs.cpp, Machines/Apple/AppleIIgs/MemoryMap.cpp, Machines/Apple/AppleIIgs/MemoryMap.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj
... while also fixing a recently-introduced issue with physical addresses and ROM.
---
Noting that I still have doubts about whether physical or logical addresses are shadowed; not yet implementing the memory effects of the new video register may be hiding misdeeds here.
=> Clean up what there currently is of a IIgs.

Machines/Amiga/Blitter.hpp, Machines/Apple/AppleIIgs/AppleIIgs.cpp, Machines/Apple/AppleIIgs/MemoryMap.cpp, Machines/Apple/AppleIIgs/MemoryMap.hpp
=> Add missing include of cstdint.

ClockReceiver/DeferredQueue.hpp, Machines/Apple/ADB/ReactiveDevice.cpp, Machines/Apple/AppleII/AppleII.cpp, Machines/Apple/AppleII/Video.hpp, Machines/Apple/AppleII/VideoSwitches.hpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme
=> Apple II: Apply deferred video actions before getting vapour value.

InstructionSets/ARM/Status.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock SignalTests/ARMDecoderTests.mm
Will be merged as slightly speculative, as I'm still feeling my way around the architecture.
=> Add some degree of ARM 2 status flags.

Machines/Apple/AppleII/AppleII.cpp, Machines/Apple/AppleII/AuxiliaryMemorySwitches.hpp
=> Propagate reset to the auxiliary switches.

InstructionSets/ARM/Executor.hpp, InstructionSets/ARM/Registers.hpp, OSBindings/Mac/Clock SignalTests/ARMDecoderTests.mm
i.e. makes private the implementation detail of how shadow registers are handled.
=> Obscure storage for active registers.

InstructionSets/ARM/Disassembler.hpp, InstructionSets/ARM/Executor.hpp, InstructionSets/ARM/OperationMapper.hpp, Machines/Acorn/Archimedes/Archimedes.cpp
Plus optional high-level reimplementation of SWIs.
=> Provide hooks for implementing pipeline prefetch.

InstructionSets/ARM/Registers.hpp, Machines/Acorn/Archimedes/Archimedes.cpp, Machines/Acorn/Archimedes/Video.hpp
I've back-pedalled for now on pushing interrupts into the future in the queue because I'm unclear on the proper handling of edge cases.
=> Introduce some degree of an ARM pipeline.

Components/9918/Implementation/PersonalityTraits.hpp, InstructionSets/ARM/Executor.hpp, InstructionSets/ARM/Registers.hpp, Machines/Acorn/Archimedes/Archimedes.cpp, Machines/Apple/AppleIIgs/MemoryMap.hpp, Processors/68000/Implementation/68000Implementation.hpp
Including two actual, real bugs with ARM data aborts.
Resolves #1360 #1359 #1363
=> Resolve various warnings.

Machines/Acorn/Archimedes/Video.hpp
With caveats:
- I have no idea what the internal cause of variable colour-depth latencies is, and therefore don't model it correctly; and
- currently all pixel content is one pixel to the left of where it really should be.
And additional bonus:
- the border doesn't (inappropriate) clip the mouse cursor now; and
- whole-display crop is adjusted so that RISC OS wide modes fit.
=> Add various VIDC output latencies.

Machines/Acorn/Archimedes/Archimedes.cpp, Machines/Acorn/Archimedes/Video.hpp
As per the branch name, Zarch is the main famous offender here; the theory at play is that early, machine-speed dependent titles probably:
- use double (or beyond) buffering; and
- therefore their infeasible frame rate can be detected by watching for new frame start address sets that massively outnumber the number of actual frames.
If such a title is detected, something vaguely like original machine speed is adopted.
=> Add automatic runtime frame-rate limiter.

Analyser/Static/AmstradCPC/StaticAnalyser.cpp, Analyser/Static/ZXSpectrum/StaticAnalyser.cpp, Storage/Disk/Encodings/MFM/Parser.cpp, Storage/Disk/Encodings/MFM/Parser.hpp, Storage/Disk/Parsers/CPM.cpp, Storage/Disk/Parsers/CPM.hpp
=> Improve Spectrum +3 disk analysis.

Machines/Acorn/Electron/Electron.cpp, Machines/Acorn/Electron/Video.cpp
=> Electron: don't miss interrupts early in the frame.

Machines/Oric/Oric.cpp, Machines/Oric/Video.cpp, Machines/Oric/Video.hpp
Tested only against Oricium because it's the only title I'm aware of that uses this feature. Resolves #1398
(Also: reduces macro dependency and tweaks 60Hz frame length, resolving a very long-standing error there)
=> Add the Oric's v-sync hardware hack.

Analyser/Static/AmstradCPC/StaticAnalyser.cpp, Analyser/Static/ZXSpectrum/StaticAnalyser.cpp, Storage/Disk/Parsers/CPM.cpp, Storage/Disk/Parsers/CPM.hpp
With very minor style improvements.
=> Reduce costs of CPC disk analysis by not loading unused contents.

OSBindings/Mac/Clock Signal/Audio/CSAudioQueue.m
As well as being neater, this should help to avoid irritation in the debugger.
=> Remove macros from CoreAudio handler.

Machines/Commodore/Plus4/Video.hpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme
i.e. this fixes horizontal scrolling of the leftmost column inside a 38-column display.
=> Progress shifter outside of painted pixels.

Machines/Commodore/Plus4/Plus4.cpp
Thanks to the information discovered at https://plus4world.powweb.com/kb.php?id=500012
=> Add joystick input.

Machines/Commodore/Plus4/Video.hpp
So that demos and games that set a specific counter position can expect to trigger events exactly at those counter positions.
=> Restructure loop to perform events AT time, not upon reaching it.

Numeric/BitReverse.hpp, Numeric/CRC.hpp, OSBindings/Mac/Clock Signal.xcodeproj/xcshareddata/xcschemes/Clock Signal.xcscheme, OSBindings/Mac/Clock SignalTests/Bridges/MOS6522Bridge.mm, Storage/Tape/Parsers/Spectrum.cpp
=> Unify and simplify bit reversal functions.

Analyser/Static/Commodore/StaticAnalyser.cpp, Analyser/Static/StaticAnalyser.cpp, Machines/Commodore/Plus4/Plus4.cpp, Numeric/CRC.hpp, Outputs/Speaker/Implementation/LowpassSpeaker.hpp, SignalProcessing/FIRFilter.cpp, SignalProcessing/FIRFilter.hpp
That is, pending better analysis — whether static or dynamic.
Also perform some light-touch modernisation of the FIRFilter.
=> Withdraw PRG support for the Plus 4.

Components/9918/Implementation/9918.cpp, Components/9918/Implementation/Storage.hpp, OSBindings/Mac/Clock Signal/Base.lproj/MachineDocument.xib, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, OSBindings/Mac/Clock Signal/Views/CSScanTargetView.h, OSBindings/Mac/Clock Signal/Views/CSScanTargetView.m
=> Require direct mouseover for options; keep until mouse exits.

Analyser/Static/PCCompatible/Target.hpp, Machines/PCCompatible/CGA.hpp, Machines/PCCompatible/DMA.hpp, Machines/PCCompatible/KeyboardMapper.hpp, Machines/PCCompatible/MDA.hpp, Machines/PCCompatible/PCCompatible.cpp, Machines/PCCompatible/PIC.hpp, Machines/PCCompatible/PIT.hpp, Machines/PCCompatible/Segments.hpp, OSBindings/Mac/Clock Signal/Documents/MachineDocument.swift, Outputs/Log.hpp
This progresses the Phoenix BIOS that I'm using to POST code 27h, i.e.. next up is the AT keyboard controller.
I don't see anything listed in the POST codes about checking the IDE interface so it's possible that adding that will bring my reckoning with 16-bit protected mode. Time will tell.
=> Add second PIC and DMA controllers.

Components/8530/z8530.cpp, Machines/PCCompatible/CPUControl.hpp, Machines/PCCompatible/KeyboardController.hpp, Machines/PCCompatible/PCCompatible.cpp, Machines/PCCompatible/RTC.hpp, Machines/PCCompatible/Registers.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, Outputs/Log.hpp
I think this'll need to be revisited, but it seems to proceed to post-keyboard BIOS tests so I'm going to keep moving.
=> Implement some proportion of the AT keyboard controller.

OSBindings/Mac/Clock Signal/Base.lproj/Activity.xib, OSBindings/Mac/Clock Signal/Base.lproj/MachineDocument.xib, OSBindings/Mac/Clock Signal/Views/CSScanTargetView.m, Storage/MassStorage/SCSI/SCSI.cpp
Attempts to address #1493 though testing is still ongoing; the SCSI issue was then found quite by chance.
=> Correct potential SCSI crash; tweak macOS mouse behaviour.

OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock SignalTests/OPLTests.mm, Outputs/OpenGL/ScanTargetGLSLFragments.cpp, SignalProcessing/FIRFilter.cpp
In favour of C++20's std::numbers.
=> Eliminate all references to M_PI.

InstructionSets/x86/AccessType.hpp, InstructionSets/x86/Decoder.cpp, InstructionSets/x86/Decoder.hpp, InstructionSets/x86/Flags.hpp, InstructionSets/x86/Implementation/FlowControl.hpp, InstructionSets/x86/Implementation/LoadStore.hpp, InstructionSets/x86/Implementation/PerformImplementation.hpp, InstructionSets/x86/Implementation/Resolver.hpp, InstructionSets/x86/Instruction.cpp, InstructionSets/x86/Instruction.hpp, InstructionSets/x86/Model.hpp, InstructionSets/x86/Perform.hpp, Numeric/Carry.hpp
Primarily to document the `perform` interface, hopefully without omission.
This is my first go at these, so I'm sure improvements are possible.
=> Apply concepts to x86 interface.

InstructionSets/x86/Descriptors.hpp, InstructionSets/x86/Implementation/PerformImplementation.hpp, InstructionSets/x86/Perform.hpp, Machines/PCCompatible/LinearMemory.hpp, Machines/PCCompatible/SegmentedMemory.hpp
In PC AT BIOS terms, this passes the GPF test and gets into some LLDT shenanigans.
=> Implement per-access GPF checks.

InstructionSets/x86/Descriptors.hpp, InstructionSets/x86/Perform.hpp, InstructionSets/x86/Registers.hpp, Machines/PCCompatible/CPUControl.hpp, Machines/PCCompatible/LinearMemory.hpp, Machines/PCCompatible/PCCompatible.cpp, Machines/PCCompatible/SegmentedMemory.hpp, Machines/PCCompatible/Segments.hpp, Numeric/RegisterSizes.hpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Mac/Clock SignalTests/8088Tests.mm
At least: they build and run now. Preauthorisation testing is currently by the wayside.
Various tests are now failing, which is probably better dealt with case-by-case.
=> Revive x86 JSON tests

InstructionSets/x86/Instruction.cpp, Machines/PCCompatible/DMA.hpp, Machines/PCCompatible/KeyboardController.hpp, Machines/PCCompatible/MDA.hpp, Machines/PCCompatible/PCCompatible.cpp, Machines/PCCompatible/RTC.hpp
Also adjusts on-motherboard switches to stop specifying `MFG_TST`.
I now strongly suspect my barely-an-8042 to be problematic. So that's next on the chopping block.
=> Add MDA status register.

Machines/Acorn/BBCMicro/BBCMicro.cpp
As per comment: this ACIA is currently connected to nothing. It can't even generate interrupts.
But it seems to get the machine into a state where it routinely polls the ACIA and polls the ADC, and has the full text prompt printed on screen. So pixels are needed next, I think.
=> BBC: Add ACIA.

Machines/Acorn/BBCMicro/BBCMicro.cpp
The image is still rolling, but it's enough to try to get the keyboard working.
=> Hard-code Mode 0 but hence get some pixels.

Components/6845/CRTC6845.hpp, Components/uPD7002/uPD7002.cpp, Components/uPD7002/uPD7002.hpp, Machines/Acorn/BBCMicro/BBCMicro.cpp, OSBindings/Mac/Clock Signal.xcodeproj/project.pbxproj, OSBindings/Qt/clksignal.pro, OSBindings/SDL/SConstruct, cmake/CLK_SOURCES.cmake
Noting that it's probably a complete fiction that results don't appear at all until conversion is complete, then instantly appear in full.
=> Add the BBC's ADC.

Analyser/Static/Acorn/Target.hpp, Components/1770/1770.cpp, Machines/Acorn/BBCMicro/BBCMicro.cpp, Machines/Acorn/Electron/Plus3.cpp, Machines/Utility/ROMCatalogue.cpp, Machines/Utility/ROMCatalogue.hpp, OSBindings/Mac/Clock Signal/Machine/StaticAnalyser/CSStaticAnalyser.mm, Processors/6502/Implementation/6502Implementation.hpp, Processors/6502/Implementation/6502Storage.cpp, Processors/6502/Implementation/6502Storage.hpp
Surprise outcome: my 6502 wasn't setting the I flag on NMI. That's a decade-old latent bug.
=> Add 1770 DFS support.

Components/uPD7002/uPD7002.cpp, Components/uPD7002/uPD7002.hpp, Machines/Acorn/BBCMicro/BBCMicro.cpp, Machines/Acorn/BBCMicro/Keyboard.hpp
Its interrupt line is connected to CB2 on the system VIA, not directly to the CPU.
=> Correct uPD7002 interrupt wiring and behaviour.

Analyser/Static/Acorn/StaticAnalyser.cpp, Analyser/Static/Acorn/Target.hpp, Components/SAA5050/SAA5050.cpp, Machines/Acorn/BBCMicro/BBCMicro.cpp
Dynamic analysis may become necessary.
=> Poke around trying to find a way to discern BBC and Electron software.

Components/SAA5050/SAA5050.cpp, Inputs/Joystick.hpp
Specifically: avoid issue where pressing and then releasing one direction can cause the fact that you're pressing the other direction to be ignored.
=> Improve mapping of digital inputs to analogue joysticks.

Machines/Acorn/BBCMicro/BBCMicro.cpp
Which corrects Pharaoh's Curse.
=> Support CB2 output strobe as triggering lightpen capture.
